### ISSUE TITLE
[BUG]AssertionError: tools/pipeline_configs/local.gin   command not found: --configs

### ISSUE THREAD

**Issue by happyplacetraveler** [princeton-vl/infinigen#102]
**Describe the bug**
AssertionError: tools/pipeline_configs/local.gin
zsh: command not found: --configs

python -m tools.manage_datagen_jobs --output_folder outputs/hello_world --num_scenes 1 --specific_seed 0
--configs desert simple --pipeline_configs local_16GB monocular blender_gt --pipeline_overrides LocalScheduleHandler.use_gpu=False

**Steps to Reproduce**

enter command above

- What version of the code were you using? Tell us the output of `git log -n 1`
'''
$ git log -n 1

commit 6d0d34a115ed5f9e453fa010c1f4a9038e9dc5c3 (HEAD -> main, origin/main, origin/HEAD)
Author: lahavlipson <llipson@princeton.edu>
Date:   Mon Jul 3 15:43:58 2023 -0400

    Revert "Update requirements.txt"
    
    This reverts commit 941880a4a383ffb15bdc7b288fb1fa3b5f7f6ec1.
...
'''

- What command did you run?
```
python -m tools.manage_datagen_jobs --output_folder outputs/hello_world --num_scenes 1 --specific_seed 0
--configs desert simple --pipeline_configs local_16GB monocular blender_gt --pipeline_overrides LocalScheduleHandler.use_gpu=False
```

- What are your output logs? 
```
Add your logs here, preferably from a job run with --debug 
```
python -m tools.manage_datagen_jobs --output_folder outputs/hello_world --num_scenes 1 --specific_seed 0
--configs desert simple --pipeline_configs local_16GB monocular blender_gt --pipeline_overrides LocalScheduleHandler.use_gpu=False --debug
Traceback (most recent call last):
  File "/Volumes/ExtremePro/AI_Generators/miniconda3/envs/infinigen/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Volumes/ExtremePro/AI_Generators/miniconda3/envs/infinigen/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/Volumes/UnityAndAdobe/infinigen/worldgen/tools/manage_datagen_jobs.py", line 1037, in <module>
    assert os.path.exists(c), c
AssertionError: tools/pipeline_configs/local.gin
zsh: command not found: --configs

** (If this is your first time running Infinigen) What are the full output logs of `install.sh` ?**
```
<See attached> 

**Platform**
- OS & OS Version: MacOS 13.5 (ventura) 
- MacStudio M1 Max
- RAM (GB):32 gb

**Additional context**
Add any other context about the problem here.

The individual tasks # Generate a scene layout  # Populate unique assets & # Render RGB images seem to be working correctly.

**Comment by araistrick** [comment]
Hello, based on the error `command not found --configs` it seems your shell is somehow treating the two lines of the command as two separate commands rather than one full command. could you try copying them both onto the same line and running?

**Comment by araistrick** [comment]
Closing due to inactivity, let me know if the suggestion above does not help.
