### ISSUE TITLE
[BUG] Blender quit: found no acceptable zoff

### ISSUE THREAD

**Issue by essencejay** [princeton-vl/infinigen#121]
conditions:
 PS C:\Users\13120> wsl --version
WSL version： 1.2.5.0
core version： 5.15.90.1
WSLg version： 1.0.51
MSRDC version： 1.2.3770
Direct3D version： 1.608.2-61064218
DXCore version： 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows version： 10.0.19044.3086
PS C:\Users\13120> wsl -l -v
  NAME            STATE           VERSION
* Ubuntu-22.04    Running         2
  Ubuntu-20.04    Stopped         2

# echo $DISPLAY
:0

result：
[19:27:55.564] [placement.camera] [WARNING] | camera_pose_proposal found no acceptable zoff after headspace_retries=30
[19:28:02.534] [placement.camera] [WARNING] | camera_pose_proposal found no acceptable zoff after headspace_retries=30
[19:28:05.363] [placement.camera] [WARNING] | camera_pose_proposal found no acceptable zoff after headspace_retries=30
[19:28:15.822] [placement.camera] [WARNING] | camera_pose_proposal found no acceptable zoff after headspace_retries=30
[19:28:16.290] [placement.camera] [WARNING] | camera_pose_proposal found no acceptable zoff after headspace_retries=30
[19:28:24.636] [placement.camera] [WARNING] | camera_pose_proposal found no acceptable zoff after headspace_retries=30
[19:28:24.783] [placement.camera] [WARNING] | camera_pose_proposal found no acceptable zoff after headspace_retries=30
[19:28:59.177] [placement.camera] [WARNING] | camera_pose_proposal found no acceptable zoff after headspace_retries=30
Searching for camera viewpoints:   0%|                                                           | 0/20 [05:01<?, ?it/s]
[19:30:35.794] [times] [INFO] | [pose_cameras] failed with <class 'AssertionError'>
[19:30:35.794] [times] [INFO] | [MAIN TOTAL] failed with <class 'AssertionError'>
Error: Python: Traceback (most recent call last):
  File "/data/infinigen/worldgen/generate.py", line 410, in <module>
    main()
  File "/data/infinigen/worldgen/generate.py", line 400, in main
    infinigen.main(
  File "/data/infinigen/worldgen/core.py", line 433, in main
    execute_tasks(
  File "/data/infinigen/blender/3.3/python/lib/python3.10/site-packages/gin/config.py", line 1605, in gin_wrapper
    utils.augment_exception_message_and_reraise(e, err_str)
  File "/data/infinigen/blender/3.3/python/lib/python3.10/site-packages/gin/utils.py", line 41, in augment_exception_message_and_reraise
    raise proxy.with_traceback(exception.__traceback__) from None
  File "/data/infinigen/blender/3.3/python/lib/python3.10/site-packages/gin/config.py", line 1582, in gin_wrapper
    return fn(*new_args, **new_kwargs)
  File "/data/infinigen/worldgen/core.py", line 279, in execute_tasks
    compose_scene_func(output_folder, terrain, scene_seed)
  File "/data/infinigen/blender/3.3/python/lib/python3.10/site-packages/gin/config.py", line 1605, in gin_wrapper
    utils.augment_exception_message_and_reraise(e, err_str)
  File "/data/infinigen/blender/3.3/python/lib/python3.10/site-packages/gin/utils.py", line 41, in augment_exception_message_and_reraise
    raise proxy.with_traceback(exception.__traceback__) from None
  File "/data/infinigen/blender/3.3/python/lib/python3.10/site-packages/gin/config.py", line 1582, in gin_wrapper
    return fn(*new_args, **new_kwargs)
  File "/data/infinigen/worldgen/generate.py", line 166, in compose_scene
    p.run_stage('pose_cameras', lambda: cam_util.configure_cameras(
  File "/data/infinigen/worldgen/util/pipeline.py", line 73, in run_stage
    return fn(*args, **kwargs)
  File "/data/infinigen/worldgen/generate.py", line 166, in <lambda>
    p.run_stage('pose_cameras', lambda: cam_util.configure_cameras(
  File "/data/infinigen/blender/3.3/python/lib/python3.10/site-packages/gin/config.py", line 1605, in gin_wrapper
    utils.augment_exception_message_and_reraise(e, err_str)
  File "/data/infinigen/blender/3.3/python/lib/python3.10/site-packages/gin/utils.py", line 41, in augment_exception_message_and_reraise
    raise proxy.with_traceback(exception.__traceback__) from None
  File "/data/infinigen/blender/3.3/python/lib/python3.10/site-packages/gin/config.py", line 1582, in gin_wrapper
    return fn(*new_args, **new_kwargs)
  File "/data/infinigen/worldgen/placement/camera.py", line 403, in configure_cameras
    base_views = compute_base_views(dummy_camera, n_views=len(cam_rigs),
  File "/data/infinigen/blender/3.3/python/lib/python3.10/site-packages/gin/config.py", line 1605, in gin_wrapper
    utils.augment_exception_message_and_reraise(e, err_str)
  File "/data/infinigen/blender/3.3/python/lib/python3.10/site-packages/gin/utils.py", line 41, in augment_exception_message_and_reraise
    raise proxy.with_traceback(exception.__traceback__) from None
  File "/data/infinigen/blender/3.3/python/lib/python3.10/site-packages/gin/config.py", line 1582, in gin_wrapper
    return fn(*new_args, **new_kwargs)
  File "/data/infinigen/worldgen/placement/camera.py", line 369, in compute_base_views
    assert potential_views != [], "no camera view found"
AssertionError: no camera view found
  In call to configurable 'compute_base_views' (<function compute_base_views at 0x7fb17f2149d0>)
  In call to configurable 'configure_cameras' (<function configure_cameras at 0x7fb17f1ff010>)
  In call to configurable 'compose_scene' (<function compose_scene at 0x7fb1a80c3520>)
  In call to configurable 'execute_tasks' (<function execute_tasks at 0x7fb171f06cb0>)

Blender quit

**Comment by araistrick** [comment]
Could you send the me the command you ran and the full logs? I need to see what seed and scene type it chose. 

This is most likely a very rare scene / edge case, so I may debug this but for now you should try a different seed.

**Comment by essencejay** [comment]
> 
thanks. I try a different seed as follow and success:  
(infinigen) root@LAPTOP-K7MG1HCV:/data/infinigen/worldgen# $BLENDER -noaudio --background --python generate.py -d -- --seed 1213457 --task coarse -g desert.gin simple.gin --output_folder outputs/helloworld/coarse

and the scene is :
 [root] [WARNING] | Randomly selected scene_type='arctic'. IF THIS IS NOT INTENDED THEN YOU ARE MISSING SCENE CONFIGS

**Comment by essencejay** [comment]
sorry, when use seed value zero, it always outputs above the question. Although change seed value it works, but i want know why and becaues each seed produces a unique set of random values, which can result in vastly different outcomes.


(infinigen) root@LAPTOP-K7MG1HCV:/data/infinigen/worldgen# $BLENDER -noaudio --background --python generate.py -- --seed 0 --task coarse -g desert.gin simple.gin --output_folder outputs/helloworld/coarse
Blender 3.3.1 (hash b292cfe5a936 built 2022-10-05 00:14:35)
/run/user/0/gvfs/ non-existent directory
[00:15:30.550] [root] [INFO] | Converted args.seed='0' to scene_seed=0, parsed as hexadecimal
[00:15:30.551] [root] [WARNING] | Randomly selected scene_type='river'. IF THIS IS NOT INTENDED THEN YOU ARE MISSING SCENE CONFIGS
[00:15:30.577] [root] [INFO] | infinigen version 1.0.2
[00:15:30.577] [root] [INFO] | CUDA_VISIBLE_DEVICES=None
[00:15:30.577] [times] [INFO] | [MAIN TOTAL]
[00:15:30.578] [root] [INFO] | Processing frames 1 through 1 inclusive
[00:15:30.589] [times] [INFO] | [Create terrain]
[00:15:30.589] [root] [INFO] | Terrain using only on the fly on_the_fly_asset_folder=PosixPath('/data/infinigen/worldgen/outputs/helloworld/coarse/assets')
[00:19:47.603] [root] [INFO] | Terrain elements: ['landtiles', 'voronoi_rocks', 'atmosphere']
[00:19:47.603] [times] [INFO] | [Create terrain] finished in 0:04:17.014059
[00:19:47.605] [times] [INFO] | [season]
[00:19:47.606] [times] [INFO] | [season] finished in 0:00:00.000311
[00:19:47.606] [root] [INFO] | season='summer'
[00:19:47.606] [times] [INFO] | [terrain]
[00:19:47.608] [times] [INFO] | [meshing OpaqueTerrain]
[00:20:23.588] [times] [INFO] | [meshing OpaqueTerrain] finished in 0:00:35.979570
[00:20:23.589] [times] [INFO] | [meshing atmosphere]
[00:20:25.969] [times] [INFO] | [meshing atmosphere] finished in 0:00:02.380848
[00:20:26.651] [terrain] [INFO] | attribute='mountain_collection' will use material surfaces.templates.sandstone
[00:20:26.651] [terrain] [INFO] | attribute='eroded' will use material surfaces.templates.dirt
[00:20:26.652] [terrain] [INFO] | attribute='atmosphere' will use material surfaces.templates.atmosphere_light_haze
[00:20:26.805] [times] [INFO] | [meshing OpaqueTerrain]
[00:21:00.057] [times] [INFO] | [meshing OpaqueTerrain] finished in 0:00:33.252204
[00:21:13.178] [times] [INFO] | [terrain] finished in 0:01:25.571471
[00:21:13.232] [times] [INFO] | [forest_params]
[00:21:13.232] [times] [INFO] | [forest_params] finished in 0:00:00.000298
[00:21:13.233] [times] [INFO] | [bushes]
[00:21:13.236] [placement.factory] [INFO] | Generating collection of 3 assets from TreeFlowerFactory(543568399)
100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:00<00:00, 14.23it/s]
[00:21:22.335] [placement] [INFO] | Placing 16 placeholders for BushFactory(543568399)
100%|███████████████████████████████████████████████████████████████████████████| 16/16 [00:01<00:00, 12.56it/s]
[00:21:23.616] [placement.factory] [INFO] | Generating collection of 3 assets from TreeFlowerFactory(36234574)
100%|█████████████████████████████████████████████████████████████████████████████| 3/3 [00:00<00:00, 12.31it/s]
[00:21:34.254] [placement] [INFO] | Placing 4 placeholders for BushFactory(36234574)
100%|█████████████████████████████████████████████████████████████████████████████| 4/4 [00:00<00:00, 20.87it/s]
[00:21:34.458] [times] [INFO] | [bushes] finished in 0:00:21.225514
[00:21:34.461] [times] [INFO] | [cactus]
[00:21:35.161] [placement] [INFO] | Placing 1 placeholders for CactusFactory(543568399)
100%|████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 294.90it/s]
[00:21:36.193] [placement] [INFO] | Placing 1 placeholders for CactusFactory(36234574)
100%|████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 287.22it/s]
[00:21:37.623] [placement] [INFO] | Placing 18 placeholders for CactusFactory(1375975078)
100%|██████████████████████████████████████████████████████████████████████████| 18/18 [00:00<00:00, 248.17it/s]
[00:21:37.700] [times] [INFO] | [cactus] finished in 0:00:03.239480
[00:21:37.701] [times] [INFO] | [camera_preprocess]
[00:21:37.714] [times] [INFO] | [Building terrain BVHTree]
Warning: No mesh data to join
Warning: No mesh data to join
[00:21:37.863] [times] [INFO] | [Building terrain BVHTree] finished in 0:00:00.149156
[00:21:37.863] [times] [INFO] | [Building placeholders KDTree]
[00:21:37.863] [times] [INFO] | [Building placeholders KDTree] finished in 0:00:00.000109
[00:21:37.864] [times] [INFO] | [camera_preprocess] finished in 0:00:00.163108
[00:21:37.865] [times] [INFO] | [pose_cameras]
Searching for camera viewpoints:   0%|                                                   | 0/20 [00:00<?, ?it/s][00:21:38.847] [placement.camera] [WARNING] | camera_pose_proposal found no acceptable zoff after headspace_retries=30
[00:21:51.266] [placement.camera] [WARNING] | camera_pose_proposal found no acceptable zoff after headspace_retr

**Comment by essencejay** [comment]
According code in generate.py:
parser.add_argument('-g', '--gin_config', nargs='+', default=['base'],
                        help='Set of config files for gin (separated by spaces) '
                             'e.g. --gin_config file1 file2 (exclude .gin from path)')

when i change the command to follow and it work
   $BLENDER -noaudio --background --python generate.py -- --seed 0 --task coarse -g desert simple --output_folder outputs/helloworld/coarse

Or it random select a scene type not specified in the command -g.
