### ISSUE TITLE
[BUG] populate forest.gin

### ISSUE THREAD

**Issue by leatherking** [princeton-vl/infinigen#127]
**Describe the bug**
I try to run the helloworld example and replace the desert.gin with forest.gin. It works to generate directory coarse/ and I change the camera view of scene.blend in coarse/ and run populate task, report the bug. Additionally: I did this in desert scene and it worked.

**Steps to Reproduce**
- What version of the code were you using? Tell us the output of `git log -n 1`
'''
v1.0.2
...
'''

- What command did you run?
```
$BLENDER -noaudio --background --python generate.py -- --seed 0 --task populate fine_terrain -g forest.gin simple.gin --input_folder outputs/forest/coarse --output_folder outputs/forest/fine
```

- What are your output logs? 
```
[11:51:41.729] [times] [INFO] | [lichen] finished in 0:00:36.091010
[11:51:41.730] [times] [INFO] | [populate_carnivore]
[11:51:41.732] [times] [INFO] | [populate_carnivore] finished in 0:00:00.001762
[11:51:41.733] [times] [INFO] | [populate_herbivore]
[11:51:41.734] [times] [INFO] | [populate_herbivore] finished in 0:00:00.001642
[11:51:41.735] [times] [INFO] | [populate_bird]
[11:51:41.736] [times] [INFO] | [populate_bird] finished in 0:00:00.001639
[11:51:41.737] [times] [INFO] | [populate_fish]
[11:51:41.738] [times] [INFO] | [populate_fish] finished in 0:00:00.001645
[11:51:41.739] [times] [INFO] | [populate_snake]
[11:51:41.740] [times] [INFO] | [populate_snake] finished in 0:00:00.001640
[11:51:41.741] [times] [INFO] | [populate_beetles]
[11:51:41.743] [times] [INFO] | [populate_beetles] finished in 0:00:00.001635
[11:51:41.743] [times] [INFO] | [populate_flyingbird]
[11:51:41.745] [times] [INFO] | [populate_flyingbird] finished in 0:00:00.001642
[11:51:41.745] [times] [INFO] | [populate_dragonfly]
[11:51:41.747] [times] [INFO] | [populate_dragonfly] finished in 0:00:00.001717
[11:51:41.747] [times] [INFO] | [populate_crab]
[11:51:41.749] [times] [INFO] | [populate_crab] finished in 0:00:00.001634
[11:51:41.749] [times] [INFO] | [populate_crustacean]
[11:51:41.751] [times] [INFO] | [populate_crustacean] finished in 0:00:00.001662
[11:51:41.754] [terrain] [INFO] | attribute='ground_collection' will use material surfaces.templates.mud
[11:51:41.754] [terrain] [INFO] | attribute='mountain_collection' will use material surfaces.templates.soil
[11:51:41.755] [terrain] [INFO] | attribute='eroded' will use material surfaces.templates.cracked_ground
[11:51:41.755] [terrain] [INFO] | attribute='atmosphere' will use material surfaces.templates.atmosphere_light_haze
In view visible mesh angle resolution 90d/1080, about  0.24 marching cube per pixel
In view invisible mesh angle resolution 90d/270, about  0.06 marching cube per pixel
Out view mesh angle resolution 90d/135, about  0.03 marching cube per pixel
In view invisible mesh marching cube resolution 66x118x1068
[11:51:41.836] [times] [INFO] | [meshing OpaqueTerrain]
[11:51:41.836] [times] [INFO] | [OpaqueSphericalMesher: frontview_mesher]
[11:52:42.851] [times] [INFO] | [OpaqueSphericalMesher: frontview_mesher] finished in 0:01:01.014258
[11:52:42.851] [times] [INFO] | [OpaqueSphericalMesher: background_mesher]
[11:53:41.367] [times] [INFO] | [OpaqueSphericalMesher: background_mesher] finished in 0:00:58.516642
[11:53:41.526] [times] [INFO] | [meshing OpaqueTerrain] finished in 0:01:59.689243
In view mesh angle resolution 90d/15, about  0.00 marching cube per pixel
Out view mesh angle resolution 90d/15, about  0.00 marching cube per pixel
[11:53:41.535] [times] [INFO] | [meshing atmosphere]
[11:53:41.535] [times] [INFO] | [TransparentSphericalMesher]
[11:53:41.619] [times] [INFO] | [TransparentSphericalMesher] finished in 0:00:00.084623
[11:53:41.620] [times] [INFO] | [meshing atmosphere] finished in 0:00:00.084787
[11:53:56.474] [times] [INFO] | [MAIN TOTAL] failed with <class 'KeyError'>
Error: Python: Traceback (most recent call last):
  File "/home/mengyc/data/infinigen/worldgen/generate.py", line 410, in <module>
    main()
  File "/home/mengyc/data/infinigen/worldgen/generate.py", line 400, in main
    infinigen.main(
  File "/media/data/mengyc/infinigen/worldgen/core.py", line 433, in main
    execute_tasks(
  File "/media/data/mengyc/infinigen/blender/3.3/python/lib/python3.10/site-packages/gin/config.py", line 1605, in gin_wrapper
    utils.augment_exception_message_and_reraise(e, err_str)
  File "/media/data/mengyc/infinigen/blender/3.3/python/lib/python3.10/site-packages/gin/utils.py", line 41, in augment_exception_message_and_reraise
    raise proxy.with_traceback(exception.__traceback__) from None
  File "/media/data/mengyc/infinigen/blender/3.3/python/lib/python3.10/site-packages/gin/config.py", line 1582, in gin_wrapper
    return fn(*new_args, **new_kwargs)
  File "/media/data/mengyc/infinigen/worldgen/core.py", line 294, in execute_tasks
    terrain.fine_terrain(output_folder)
  File "/media/data/mengyc/infinigen/worldgen/terrain/core.py", line 261, in fine_terrain
    fine_meshes, _ = self.export(spherical=True, cameras=[bpy.context.scene.camera])
  File "/media/data/mengyc/infinigen/blender/3.3/python/lib/python3.10/site-packages/gin/config.py", line 1605, in gin_wrapper
    utils.augment_exception_message_and_reraise(e, err_str)
  File "/media/data/mengyc/infinigen/blender/3.3/python/lib/python3.10/site-packages/gin/utils.py", line 41, in augment_exception_message_and_reraise
    raise proxy.with_traceback(exception.__traceback__) from None
  File "/media/data/mengyc/infinigen/blender/3.3/python/lib/python3.10/site-packages/gin/config.py", line 1582, in gin_wrapper
    return fn(*new_args, **new_kwargs)
  File "/media/data/mengyc/infinigen/worldgen/terrain/core.py", line 162, in export
    surface_kernel = SurfaceKernel(surface.name, attribute, bpy.data.objects[mesh_name_unapplied].modifiers[surface.mod_name], self.device)
  File "/media/data/mengyc/infinigen/worldgen/terrain/surface_kernel/core.py", line 22, in __init__
    _, inputs, outputs = Kernelizer()(modifier)
  File "/media/data/mengyc/infinigen/worldgen/terrain/surface_kernel/kernelizer.py", line 331, in __call__
    code, imp_inputs, outputs = self.execute_node_tree(node_tree, collective_style=True)
  File "/media/data/mengyc/infinigen/worldgen/terrain/surface_kernel/kernelizer.py", line 323, in execute_node_tree
    code += self.code(nodes, links, inputs, imp_inputs, outputs, node_tree.name)
  File "/media/data/mengyc/infinigen/worldgen/terrain/surface_kernel/kernelizer.py", line 190, in code
    for p in NODE_ATTRS_AVAILABLE[head_node.bl_idname]]
KeyError: 'NodeUndefined'
  In call to configurable 'export' (<function Terrain.export at 0x7f1029aefa30>)
  In call to configurable 'execute_tasks' (<function execute_tasks at 0x7f10295e8700>)

Blender quit
```

** (If this is your first time running Infinigen) What are the full output logs of `install.sh` ?**
```
Add your install.sh logs here
```

**Platform**
- OS & OS Version:  Ubuntu 20.04.2 LTS
- GPU (?) : 3090
- GPU Driver Version (?) :
- RAM (GB): 64

**Additional context**

**Comment by araistrick** [comment]
Hello, this is a very unusual bug, usually NodeUndefined only comes up when switching between blender versions.

Could you post the full output logs? These ones are missing the beginning, and I would be interested to see what seed the pipeline chose so I can replicate.

**Comment by araistrick** [comment]
Closed due to inactivity - please reopen if you are still encountering issues.
