### ISSUE TITLE
[BUG] : second script in "helloworld" fails

### ISSUE THREAD

**Issue by cromagn** [princeton-vl/infinigen#128]
**Describe the bug**
Same as https://github.com/princeton-vl/infinigen/issues/34. 
When i run the second script in helloworld example, infinigen quit !!!

**Steps to Reproduce**
- What version of the code were you using? Tell us the output of `git log -n 1`
'''
commit b387b5a6002b2fd2898e78a664b5754ca01e7081 (HEAD -> main, tag: v1.0.2, origin/main, origin/HEAD)
Merge: 6d0d34a a3a5b57
Author: pvl-bot <136786582+pvl-bot@users.noreply.github.com>
Date:   Fri Jul 28 18:22:29 2023 -0400
Merge pull request #115 from princeton-vl/develop
 v1.0.2 - New documentation, plant improvements, disk and reproducibility improvements
...

- What command did you run?
```
$BLENDER -noaudio --background --python generate.py -- --seed 0 --task populate fine_terrain -g desert.gin simple.gin --input_folder outputs/helloworld/coarse --output_folder outputs/helloworld/fine 
```
- What are your output logs? 
With Debug
[logWithDebug.txt](https://github.com/princeton-vl/infinigen/files/12325172/logWithDebug.txt)
Dump
[Dump.txt](https://github.com/princeton-vl/infinigen/files/12325183/Dump.txt)

Without debug
```
$BLENDER -noaudio --background --python generate.py -- --seed 0 --task populate fine_terrain -g desert.gin simple.gin --input_folde[20:42:24.016] [times] [INFO] | [meshing atmosphere] finished in 0:00:00.122751
[20:42:51.830] [times] [INFO] | [Writing output blendfile to /home/ubuntu/infinigen/worldgen/outputs/helloworld/fine/scene.blend]
Error: No such file or directory
Error: No such file or directory
[20:42:51.879] [times] [INFO] | [Writing output blendfile to /home/ubuntu/infinigen/worldgen/outputs/helloworld/fine/scene.blend] failed with <class 'RuntimeError'>
[20:42:51.880] [times] [INFO] | [MAIN TOTAL] failed with <class 'RuntimeError'>
Error: Python: Traceback (most recent call last):
  File "/home/ubuntu/infinigen/worldgen/generate.py", line 410, in <module>
    main()
  File "/home/ubuntu/infinigen/worldgen/generate.py", line 400, in main
    infinigen.main(
  File "/home/ubuntu/infinigen/worldgen/core.py", line 433, in main
    execute_tasks(
  File "/home/ubuntu/infinigen/blender/3.3/python/lib/python3.10/site-packages/gin/config.py", line 1605, in gin_wrapper
    utils.augment_exception_message_and_reraise(e, err_str)
  File "/home/ubuntu/infinigen/blender/3.3/python/lib/python3.10/site-packages/gin/utils.py", line 41, in augment_exception_message_and_reraise
    raise proxy.with_traceback(exception.__traceback__) from None
  File "/home/ubuntu/infinigen/blender/3.3/python/lib/python3.10/site-packages/gin/config.py", line 1582, in gin_wrapper
    return fn(*new_args, **new_kwargs)
  File "/home/ubuntu/infinigen/worldgen/core.py", line 312, in execute_tasks
    bpy.ops.wm.save_mainfile(filepath=str(output_folder / output_blend_name))
  File "/home/ubuntu/infinigen/blender/3.3/scripts/modules/bpy/ops.py", line 113, in __call__
    ret = _op_call(self.idname_py(), None, kw)
RuntimeError: Error: No such file or directory

  In call to configurable 'execute_tasks' (<function execute_tasks at 0x7fce16abaa70>)r outputs/helloworld/coarse --output_folder outputs/helloworld/fine
```

**Platform**
5.19.0-1025-aws
Architecture:            x86_64
CPU op-mode(s):        32-bit, 64-bit
Address sizes:         46 bits physical, 48 bits virtual
Byte Order:            Little Endian
CPU(s):                  96
  On-line CPU(s) list:   0-95
Vendor ID:               GenuineIntel
  Model name:            Intel(R) Xeon(R) Platinum 8275CL CPU @ 3.00GHz
Virtualization features: 
  Hypervisor vendor:     KVM
  Virtualization type:   full
               total        used        free      shared  buff/cache   available
Mem:       193661276     1102304   190508660        1212     2050312   191311096
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.2 LTS
- GPU (?) : None
- GPU Driver Version (?) :
- RAM (GB):

**Comment by araistrick** [comment]
Hello - it seems part of the command you ran got cut off. Are you sure the command contained a full and valid --output_path? It seems here blender could not write to the specified path. If your path contains `outputs/` then make sure you ran `mkdir outputs`

**Comment by cromagn** [comment]
I m so stupid!
