### ISSUE TITLE
ModuleNotFoundError: No module named 'flip_fluids_addon'

### ISSUE THREAD

**Issue by yijiaguo02** [princeton-vl/infinigen#134]
The following command is sent: "nice -n 20 ../blender/blender --background -y -noaudio --python generate.py --threads 8 -- --input_folder /home/datasda/huliwen/my_videos/videos1114411/20bc1adb/coarse --output_folder /home/datasda/huliwen/my_videos/videos1114411/20bc1adb/coarse --seed 20bc1adb --task populate --task_uniqname populate -g kelp_forest simple.gin -p          LOG_DIR='/home/datasda/huliwen/my_videos/videos1114411/20bc1adb/logs'      execute_tasks.frame_range=[1, 192] execute_tasks.camera_id=[0, 0]"
Overriden parameters: ['', "        LOG_DIR='/home/datasda/huliwen/my_videos/videos1114411/20bc1adb/logs'", '    ', 'execute_tasks.frame_range=[1, 192]', 'execute_tasks.camera_id=[0, 0]']
Traceback (most recent call last):
  File "/home/huliwen/infinigen/blender/3.3/scripts/modules/addon_utils.py", line 333, in enable
    mod = __import__(module_name)
ModuleNotFoundError: No module named 'flip_fluids_addon'

Error: Traceback (most recent call last):
  File "/home/huliwen/infinigen/blender/3.3/scripts/modules/addon_utils.py", line 333, in enable
    mod = __import__(module_name)
ModuleNotFoundError: No module named 'flip_fluids_addon'

**Comment by louis-fashion-ai** [comment]
I encountered the similar problem，my program to generate images in one command crashed, reporting the error:[19:53:17.489] [root] [WARNING] | Re-initialized 0 as trusted. Do not run infinigen on untrusted blend files. 
[19:53:17.489] [root] [INFO] | Processing frames 48 through 48 inclusive
[19:53:17.530] [root] [WARNING] | Could not load addon "flip_fluids_addon"

**Comment by araistrick** [comment]
Hello, could you each please share the full command you ran and the full logs, and your platform info?

**Comment by AtalsZem** [comment]
> 

It's working for me. Thanks!

**Comment by AtalsZem** [comment]
> try "bash install.sh flip_fluids"

It's working for me. Thanks!

**Comment by araistrick** [comment]
To confirm, is this flip_fluids_error a fatal crash for you all? If so, what is your OS/platform? Installing flip_fluids is intended to be optional, and the ModuleError from failing to load flip fluids is explicitly try-catched in the code.

**Comment by yijiaguo02** [comment]
> 
I have tried "try "bash install.sh flip_fluids"with the same errors on Ubuntuntu. However, the Infinigen works well with "ModuleNotFoundError: No module named 'flip_fluids_addon.'" I can get right imgs and gts. I will show you more  details soon, according to when my severs back to work.
