### ISSUE TITLE
Issue running HelloWorld commands

### ISSUE THREAD

**Issue by samhita-m** [princeton-vl/infinigen#147]
# Describe the bug

Hi, I followed the instructions in the `Installation.md` and tried to test the `HelloWorld.md `but I'm getting "gin module not found error" as shown below. I tried conda install and pip install but they didn't help. Also restarted the terminal and my computer but they didn't help either.

### What version of the code were you using? 
'''
What is the output of `git log -n 1`?
'''

commit 0f208a8044c38a797f3383d7c7f7f7425154f25b (HEAD -> main, origin/main, origin/HEAD)
Author: Kaiyu Yang <kaiyuy@caltech.edu>
Date:   Mon Sep 4 08:06:38 2023 -1000

    Update ImplementingAssets.md (#142)

### What command did you run?
```
BLENDER -noaudio --background --python generate.py -- --seed 0 --task coarse -g desert simple --output_folder outputs/helloworld/coarse --debug

python -m tools.manage_datagen_jobs --output_folder outputs/hello_world --num_scenes 1 --specific_seed 0 \
--configs desert.gin simple.gin --pipeline_configs local_16GB.gin monocular.gin blender_gt.gin --pipeline_overrides LocalScheduleHandler.use_gpu=False --debug
```

### What are your FULL output logs?
When I run this command, following is the output in the terminal "BLENDER -noaudio --background --python generate.py -- --seed 0 --task coarse -g desert simple --output_folder outputs/helloworld/coarse --debug"

```
Blender 3.6.4 (hash 21bfc5e7fe3f built 2023-09-25 23:33:06)
Device with name Apple M2 supports metal minimum requirements
Error: Python: Traceback (most recent call last):
  File "/Users/samhitamarri/Downloads/Research/PlantCare/infinigen/worldgen/generate.py", line 14, in <module>
    import gin
ModuleNotFoundError: No module named 'gin'


Blender quit
```

I'm getting the following error when I try "python -m tools.manage_datagen_jobs --output_folder outputs/hello_world --num_scenes 1 --specific_seed 0 \
--configs desert.gin simple.gin --pipeline_configs local_16GB.gin monocular.gin blender_gt.gin --pipeline_overrides LocalScheduleHandler.use_gpu=False --debug" 

```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/Users/samhitamarri/Downloads/Research/PlantCare/infinigen/worldgen/tools/manage_datagen_jobs.py", line 15, in <module>
    import gin
ModuleNotFoundError: No module named 'gin'
```

### Platform
- OS & OS Version: macOS Sonoma (M2)
- GPU (?) :
- GPU Driver Version (?) :
- RAM (GB): 16 GB

# Additional context

**Comment by samhita-m** [comment]
Here is the logs.txt file. 

[logs.txt](https://github.com/princeton-vl/infinigen/files/12805764/logs.txt)

**Comment by TJKlein** [comment]
I have exactly the same problem.
