### ISSUE TITLE
name 'log_uniform' is not defined

### ISSUE THREAD

**Issue by wb175208** [princeton-vl/infinigen#149]
**$ sudo $BLENDER --background --python tools/generate_individual_assets.py -- -f BoulderPileFactory -n 4 --save_blend**
Blender 3.3.1 (hash b292cfe5a936 built 2022-10-05 00:14:35)
Traceback (most recent call last):
  File "/home/wb/work/infinigen/worldgen/tools/generate_individual_assets.py", line 61, in build_scene_asset
    asset = factory.spawn_asset(idx)
  File "/home/wb/work/infinigen/worldgen/placement/factory.py", line 102, in spawn_asset
    placeholder = self.spawn_placeholder(i=i, loc=loc, rot=rot)
  File "/home/wb/work/infinigen/worldgen/placement/factory.py", line 72, in spawn_placeholder
    obj = self.create_placeholder(i=i, loc=loc, rot=rot)
  File "/home/wb/work/infinigen/worldgen/assets/pile.py", line 55, in create_placeholder
    scale = [1, log_uniform(.4, .6), log_uniform(.2, .4), log_uniform(.2, .4), log_uniform(.2, .4),
NameError: name 'log_uniform' is not defined
BoulderPileFactory(0).spawn_asset(idx=0) FAILED!! name 'log_uniform' is not defined
name 'log_uniform' is not defined
Traceback (most recent call last):
  File "/home/wb/work/infinigen/worldgen/tools/generate_individual_assets.py", line 61, in build_scene_asset
    asset = factory.spawn_asset(idx)
  File "/home/wb/work/infinigen/worldgen/placement/factory.py", line 102, in spawn_asset
    placeholder = self.spawn_placeholder(i=i, loc=loc, rot=rot)
  File "/home/wb/work/infinigen/worldgen/placement/factory.py", line 72, in spawn_placeholder
    obj = self.create_placeholder(i=i, loc=loc, rot=rot)
  File "/home/wb/work/infinigen/worldgen/assets/pile.py", line 55, in create_placeholder
    scale = [1, log_uniform(.4, .6), log_uniform(.2, .4), log_uniform(.2, .4), log_uniform(.2, .4),
NameError: name 'log_uniform' is not defined
BoulderPileFactory(1).spawn_asset(idx=1) FAILED!! name 'log_uniform' is not defined
name 'log_uniform' is not defined
Traceback (most recent call last):
  File "/home/wb/work/infinigen/worldgen/tools/generate_individual_assets.py", line 61, in build_scene_asset
    asset = factory.spawn_asset(idx)
  File "/home/wb/work/infinigen/worldgen/placement/factory.py", line 102, in spawn_asset
    placeholder = self.spawn_placeholder(i=i, loc=loc, rot=rot)
  File "/home/wb/work/infinigen/worldgen/placement/factory.py", line 72, in spawn_placeholder
    obj = self.create_placeholder(i=i, loc=loc, rot=rot)
  File "/home/wb/work/infinigen/worldgen/assets/pile.py", line 55, in create_placeholder
    scale = [1, log_uniform(.4, .6), log_uniform(.2, .4), log_uniform(.2, .4), log_uniform(.2, .4),
NameError: name 'log_uniform' is not defined
BoulderPileFactory(2).spawn_asset(idx=2) FAILED!! name 'log_uniform' is not defined
name 'log_uniform' is not defined
Traceback (most recent call last):
  File "/home/wb/work/infinigen/worldgen/tools/generate_individual_assets.py", line 61, in build_scene_asset
    asset = factory.spawn_asset(idx)
  File "/home/wb/work/infinigen/worldgen/placement/factory.py", line 102, in spawn_asset
    placeholder = self.spawn_placeholder(i=i, loc=loc, rot=rot)
  File "/home/wb/work/infinigen/worldgen/placement/factory.py", line 72, in spawn_placeholder
    obj = self.create_placeholder(i=i, loc=loc, rot=rot)
  File "/home/wb/work/infinigen/worldgen/assets/pile.py", line 55, in create_placeholder
    scale = [1, log_uniform(.4, .6), log_uniform(.2, .4), log_uniform(.2, .4), log_uniform(.2, .4),
NameError: name 'log_uniform' is not defined
BoulderPileFactory(3).spawn_asset(idx=3) FAILED!! name 'log_uniform' is not defined
name 'log_uniform' is not defined
No images found

Blender quit

**Comment by araistrick** [comment]
Hello, this part of the code is not actively used in the current version of the main infinigen renderer and it appears now has some bugs. If your goal is to generate one of every asset you can simply skip this one. Otherwise, I think you could fix it by adding `from util.random import log_uniform`, this will be fixed in v1.1 which I hope to release next week.
