### ISSUE TITLE
error occured when render RGB images

### ISSUE THREAD

**Issue by oceanliubuaa** [princeton-vl/infinigen#154]
# Describe the bug
After successfully installed infinigen, I tried HelloWorld demo. An error 'Failed to create OptiX denoiser' occured when running the third command:
# Render RGB images
$BLENDER -noaudio --background --python generate.py -- --seed 0 --task render -g desert.gin simple.gin --input_folder outputs/hello_world/fine --output_folder outputs/hello_world/frames

## Steps to Reproduce
following the steps in helloworld.md

### What version of the code were you using? 
main branch

What is the output of `git log -n 1`?
commit 0f208a8044c38a797f3383d7c7f7f7425154f25b (HEAD -> main, origin/v1.1, origin/main, origin/HEAD)
Author: Kaiyu Yang <kaiyuy@caltech.edu>
Date:   Mon Sep 4 08:06:38 2023 -1000

    Update ImplementingAssets.md (#142)

### What command did you run?
$BLENDER -noaudio --background --python generate.py -- --seed 0 --task render -g desert.gin simple.gin --input_folder outputs/hello_world/fine --output_folder outputs/hello_world/frames

### What are your FULL output logs?
Fra:1 Mem:15519.08M (Peak 16484.66M) | Time:03:09.61 | Mem:5852.08M, Peak:5852.08M | Scene, ViewLayer | Updating Device | Writing constant memory
Fra:1 Mem:15527.01M (Peak 16484.66M) | Time:03:09.62 | Mem:5852.08M, Peak:5852.08M | Scene, ViewLayer | Sample 0/64
Fra:1 Mem:15986.16M (Peak 16484.66M) | Time:03:09.86 | Remaining:00:14.96 | Mem:5852.08M, Peak:5852.08M | Scene, ViewLayer | Sample 1/64
Fra:1 Mem:15986.16M (Peak 16489.13M) | Time:03:10.35 | Remaining:00:22.75 | Mem:5852.08M, Peak:6310.87M | Scene, ViewLayer | Sample 2/64
Fra:1 Mem:15986.16M (Peak 16489.13M) | Time:03:10.99 | Remaining:00:27.77 | Mem:5852.08M, Peak:6310.87M | Scene, ViewLayer | Sample 3/64
Fra:1 Mem:15986.16M (Peak 16489.13M) | Time:03:11.13 | Remaining:00:17.75 | Mem:5852.08M, Peak:6310.87M | Scene, ViewLayer | Sample 5/64
Fra:1 Mem:15986.16M (Peak 16489.13M) | Time:03:13.97 | Remaining:00:01.44 | Mem:5852.08M, Peak:6310.87M | Scene, ViewLayer | Sample 48/64
Failed to create OptiX denoiser

Refer to the Cycles GPU rendering documentation for possible solutions:
https://docs.blender.org/manual/en/latest/render/cycles/gpu_rendering.html

E1017 15:37:27.419275 590570 device_impl.cpp:1166] OptiX denoiser creation has failed.
Fra:1 Mem:16816.74M (Peak 17220.16M) | Time:03:16.32 | Mem:5852.08M, Peak:6310.87M | Scene, ViewLayer | Sample 64/64
Fra:1 Mem:16816.74M (Peak 17220.16M) | Time:03:16.32 | Mem:5852.08M, Peak:6310.87M | Scene, ViewLayer | Failed to create OptiX denoiser
Error: Failed to create OptiX denoiser
Error: Failed to create OptiX denoiser
[15:37:29.971] [times] [INFO] | [Actual rendering] failed with <class 'RuntimeError'>
[15:37:29.973] [times] [INFO] | [Render Frames] failed with <class 'RuntimeError'>
[15:37:29.973] [times] [INFO] | [MAIN TOTAL] failed with <class 'RuntimeError'>
Error: Python: Traceback (most recent call last):
  File "/data/infinigen/worldgen/generate.py", line 441, in <module>
    main()
  File "/data/infinigen/worldgen/generate.py", line 431, in main
    infinigen.main(
  File "/data/infinigen/worldgen/core.py", line 459, in main
    execute_tasks(
  File "/data/infinigen/blender/3.3/python/lib/python3.10/site-packages/gin/config.py", line 1605, in gin_wrapper
    utils.augment_exception_message_and_reraise(e, err_str)
  File "/data/infinigen/blender/3.3/python/lib/python3.10/site-packages/gin/utils.py", line 41, in augment_exception_message_and_reraise
    raise proxy.with_traceback(exception.__traceback__) from None
  File "/data/infinigen/blender/3.3/python/lib/python3.10/site-packages/gin/config.py", line 1582, in gin_wrapper
    return fn(*new_args, **new_kwargs)
  File "/data/infinigen/worldgen/core.py", line 369, in execute_tasks
    render(scene_seed, output_folder=output_folder, camera_id=camera_id, resample_idx=resample_idx)
  File "/data/infinigen/blender/3.3/python/lib/python3.10/site-packages/gin/config.py", line 1605, in gin_wrapper
    utils.augment_exception_message_and_reraise(e, err_str)
  File "/data/infinigen/blender/3.3/python/lib/python3.10/site-packages/gin/utils.py", line 41, in augment_exception_message_and_reraise
    raise proxy.with_traceback(exception.__traceback__) from None
  File "/data/infinigen/blender/3.3/python/lib/python3.10/site-packages/gin/config.py", line 1582, in gin_wrapper
    return fn(*new_args, **new_kwargs)
  File "/data/infinigen/worldgen/core.py", line 217, in render
    render_image_func(frames_folder=Path(output_folder), camera_id=camera_id)
  File "/data/infinigen/blender/3.3/python/lib/python3.10/site-packages/gin/config.py", line 670, in scoping_wrapper
    return fn_or_cls(*args, **kwargs)
  File "/data/infinigen/blender/3.3/python/lib/python3.10/site-packages/gin/config.py", line 1605, in gin_wrapper
    utils.augment_exception_message_and_reraise(e, err_str)
  File "/data/infinigen/blender/3.3/python/lib/python3.10/site-packages/gin/utils.py", line 41, in augment_exception_message_and_reraise
    raise proxy.with_traceback(exception.__traceback__) from None
  File "/data/infinigen/blender/3.3/python/lib/python3.10/site-packages/gin/config.py", line 1582, in gin_wrapper
    return fn(*new_args, **new_kwargs)
  File "/data/infinigen/worldgen/rendering/render.py", line 309, in render_image
    bpy.ops.render.render(animation=True)
  File "/data/infinigen/blender/3.3/scripts/modules/bpy/ops.py", line 113, in __call__
    ret = _op_call(self.idname_py(), None, kw)
RuntimeError: Error: Failed to create OptiX denoiser

  In call to configurable 'render_image' (<function render_image at 0x7f758e04a320>) in scope 'full'
  In call to configurable 'render' (<function render at 0x7f758e04b490>)
  In call to configurable 'execute_tasks' (<function execute_tasks at 0x7f758e04bc70>)

Blender quit

### Platform
- OS & OS Version: Ubuntu 22.04
- GPU (?) :
- GPU Driver Version (?) :535.104.05
- RAM (GB):

# Additional context

**Comment by oceanliubuaa** [comment]
BTW the first two commands (coarse and fine) worked normally.
