### ISSUE TITLE
glm error and configuration error

### ISSUE THREAD

**Issue by Asianfleet** [princeton-vl/infinigen#168]
# Describe the bug
fatal error occured during the compilation

### What version of the code were you using? 
the latest version

### command
```
bash install.sh
```

### What are your FULL output logs?
```
bash install.sh
Submodule 'process_mesh/dependencies/argparse' (https://github.com/p-ranav/argparse.git) registered for path 'process_mesh/dependencies/argparse'
....................................
--2023-11-12 23:18:39--  https://download.blender.org/release/Blender3.3/blender-3.3.1-linux-x64.tar.xz
Connecting to 172.20.64.1:7890... connected.
Proxy request sent, awaiting response... 200 OK
Length: 204144236 (195M) [application/octet-stream]
Saving to: ‘blender.tar.xz’

blender.tar.xz                100%[=================================================>] 194.69M   745KB/s    in 3m 8s

2023-11-12 23:21:49 (1.03 MB/s) - ‘blender.tar.xz’ saved [204144236/204144236]

....................................
Requirement already satisfied: pycparser==2.21 in /home/lenovo/anaconda3/lib/python3.11/site-packages (from -r ./requirements.txt (line 23)) (2.21)
Collecting json5==0.9.10 (from -r ./requirements.txt (line 24))
  Using cached json5-0.9.10-py2.py3-none-any.whl (19 kB)
Collecting google-images-search==1.4.4 (from -r ./requirements.txt (line 25))
  Using cached Google_Images_Search-1.4.4-py2.py3-none-any.whl (12 kB)
Collecting landlab==2.4.1 (from -r ./requirements.txt (line 26))
  Using cached landlab-2.4.1.tar.gz (1.2 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
#________________________________________________error1______________________________________________________
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [36 lines of output]
      <string>:6: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
      Traceback (most recent call last):
        File "/home/lenovo/anaconda3/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/home/lenovo/anaconda3/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/home/lenovo/anaconda3/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-z95191jb/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 355, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-z95191jb/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 325, in _get_build_requires
          self.run_setup()
        File "/tmp/pip-build-env-z95191jb/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 507, in run_setup
          super(_BuildMetaLegacyBackend, self).run_setup(setup_script=setup_script)
        File "/tmp/pip-build-env-z95191jb/overlay/lib/python3.11/site-packages/setuptools/build_meta.py", line 341, in run_setup
          exec(code, locals())
        File "<string>", line 39, in <module>
        File "/tmp/pip-build-env-z95191jb/overlay/lib/python3.11/site-packages/setuptools/__init__.py", line 103, in setup
          return distutils.core.setup(**attrs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-z95191jb/overlay/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 159, in setup
          dist.parse_config_files()
        File "/tmp/pip-build-env-z95191jb/overlay/lib/python3.11/site-packages/setuptools/dist.py", line 653, in parse_config_files
          pyprojecttoml.apply_configuration(self, filename, ignore_option_errors)
        File "/tmp/pip-build-env-z95191jb/overlay/lib/python3.11/site-packages/setuptools/config/pyprojecttoml.py", line 66, in apply_configuration
          config = read_configuration(filepath, True, ignore_option_errors, dist)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-z95191jb/overlay/lib/python3.11/site-packages/setuptools/config/pyprojecttoml.py", line 127, in read_configuration
          validate(subset, filepath)
        File "/tmp/pip-build-env-z95191jb/overlay/lib/python3.11/site-packages/setuptools/config/pyprojecttoml.py", line 55, in validate
          raise ValueError(f"{error}\n{summary}") from None
      ValueError: invalid pyproject.toml config: `project`.
      configuration error: `project` must contain ['name'] properties
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
Requirement already satisfied: fake-bpy-module-latest in /home/lenovo/anaconda3/lib/python3.11/site-packages (20231111)
--2023-11-12 23:23:09--  https://www.python.org/ftp/python/3.10.2/Python-3.10.2.tgz
Connecting to 172.20.64.1:7890... connected.
Proxy request sent, awaiting response... 200 OK
Length: 25067363 (24M) [application/octet-stream]
Saving to: ‘Python-3.10.2.tgz’

Python-3.10.2.tgz             100%[=================================================>]  23.91M  21.7MB/s    in 1.1s

2023-11-12 23:23:11 (21.7 MB/s) - ‘Python-3.10.2.tgz’ saved [25067363/25067363]

Looking in links: /tmp/tmp9vsb8mhs
Processing /tmp/tmp9vsb8mhs/setuptools-58.1.0-py3-none-any.whl
Processing /tmp/tmp9vsb8mhs/pip-21.2.4-py3-none-any.whl
Installing collected packages: setuptools, pip
....................................
You should consider upgrading via the '/home/lenovo/AI_Pkgs/infinigen/blender/3.3/python/bin/python3.10 -m pip install --upgrade pip' command.
compiled lib/cuda/utils/FastNoiseLite.so
compiled lib/cuda/elements/voronoi_rocks.so
compiled lib/cuda/elements/upsidedown_mountains.so
compiled lib/cuda/elements/ground.so
compiled lib/cuda/elements/warped_rocks.so
compiled lib/cuda/elements/mountains.so
compiled lib/cuda/elements/landtiles.so
compiled lib/cuda/elements/atmosphere.so
compiled lib/cuda/elements/waterbody.so
compiled lib/cuda/surfaces/chunkyrock.so
compiled lib/cuda/surfaces/cobble_stone.so
compiled lib/cuda/surfaces/cracked_ground.so
compiled lib/cuda/surfaces/dirt.so
compiled lib/cuda/surfaces/ice.so
compiled lib/cuda/surfaces/mountain.so
compiled lib/cuda/surfaces/mud.so
compiled lib/cuda/surfaces/sand.so
compiled lib/cuda/surfaces/sandstone.so
compiled lib/cuda/surfaces/snow.so
compiled lib/cuda/surfaces/soil.so
compiled lib/cuda/surfaces/stone.so
compiled lib/cpu/utils/FastNoiseLite.so
compiled lib/cpu/elements/voronoi_rocks.so
compiled lib/cpu/elements/upsidedown_mountains.so
compiled lib/cpu/elements/ground.so
compiled lib/cpu/elements/warped_rocks.so
compiled lib/cpu/elements/mountains.so
compiled lib/cpu/elements/landtiles.so
compiled lib/cpu/elements/atmosphere.so
compiled lib/cpu/elements/waterbody.so
compiled lib/cpu/surfaces/chunkyrock.so
compiled lib/cpu/surfaces/cobble_stone.so
compiled lib/cpu/surfaces/cracked_ground.so
compiled lib/cpu/surfaces/dirt.so
compiled lib/cpu/surfaces/ice.so
compiled lib/cpu/surfaces/mountain.so
compiled lib/cpu/surfaces/mud.so
compiled lib/cpu/surfaces/sand.so
compiled lib/cpu/surfaces/sandstone.so
compiled lib/cpu/surfaces/snow.so
compiled lib/cpu/surfaces/soil.so
compiled lib/cpu/surfaces/stone.so
compiled lib/cpu/meshing/cube_spherical_mesher.so
compiled lib/cpu/meshing/frontview_spherical_mesher.so
compiled lib/cpu/meshing/uniform_mesher.so
compiled lib/cpu/meshing/utils.so
#____________________________________________error2_______________________________________________________
In file included from source/cpu/soil_machine/SoilMachine.cpp:18:
source/cpu/soil_machine/layermap.h:37:10: fatal error: glm/glm.hpp: No such file or directory
   37 | #include <glm/glm.hpp>
      |          ^~~~~~~~~~~~~
compilation terminated.
Compiling /home/lenovo/AI_Pkgs/infinigen/worldgen/terrain/marching_cubes/_marching_cubes_lewiner_cy.pyx because it changed.
[1/1] Cythonizing /home/lenovo/AI_Pkgs/infinigen/worldgen/terrain/marching_cubes/_marching_cubes_lewiner_cy.pyx
running build_ext
running build_src
build_src
building extension "marching_cubes._marching_cubes_lewiner_cy" sources
build_src: building npy-pkg config files
customize UnixCCompiler
customize UnixCCompiler using build_ext
CCompilerOpt.cc_test_flags[1013] : testing flags (-march=native)
C compiler: gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -I/home/sybren/buildbot-builder/linux_glibc217_x86_64_cmake/build_deps/deps/Release/sqlite/include -I/home/sybren/buildbot-builder/linux_glibc217_x86_64_cmake/build_deps/deps/Release/bzip2/include -I/home/sybren/buildbot-builder/linux_glibc217_x86_64_cmake/build_deps/deps/Release/lzma/include -I/home/sybren/buildbot-builder/linux_glibc217_x86_64_cmake/build_deps/deps/Release/zlib/include -fPIC -fPIC -fPIC

creating /tmp/tmp9gjejabh/home
creating /tmp/tmp9gjejabh/home/lenovo
creating /tmp/tmp9gjejabh/home/lenovo/AI_Pkgs
creating /tmp/tmp9gjejabh/home/lenovo/AI_Pkgs/infinigen
creating /tmp/tmp9gjejabh/home/lenovo/AI_Pkgs/infinigen/blender
creating /tmp/tmp9gjejabh/home/lenovo/AI_Pkgs/infinigen/blender/3.3
creating /tmp/tmp9gjejabh/home/lenovo/AI_Pkgs/infinigen/blender/3.3/python
creating /tmp/tmp9gjejabh/home/lenovo/AI_Pkgs/infinigen/blender/3.3/python/lib
creating /tmp/tmp9gjejabh/home/lenovo/AI_Pkgs/infinigen/blender/3.3/python/lib/python3.10
creating /tmp/tmp9gjejabh/home/lenovo/AI_Pkgs/infinigen/blender/3.3/python/lib/python3.10/site-packages
creating /tmp/tmp9gjejabh/home/lenovo/AI_Pkgs/infinigen/blender/3.3/python/lib/python3.10/site-packages/numpy
creating /tmp/tmp9gjejabh/home/lenovo/AI_Pkgs/infinigen/blender/3.3/python/lib/python3.10/site-packages/numpy/distutils
creating /tmp/tmp9gjejabh/home/lenovo/AI_Pkgs/infinigen/blender/3.3/python/lib/python3.10/site-packages/numpy/distutils/checks
compile options: '-I/home/lenovo/AI_Pkgs/infinigen/blender/3.3/python/include/python3.10 -c'
extra options: '-march=native'
CCompilerOpt.cc_test_flags[1013] : testing flags (-O3)
C compiler: gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -I/home/sybren/buildbot-builder/linux_glibc217_x86_64_cmake/build_deps/deps/Release/sqlite/include -I/home/sybren/buildbot-builder/linux_glibc217_x86_64_cmake/build_deps/deps/Release/bzip2/include -I/home/sybren/buildbot-builder/linux_glibc217_x86_64_cmake/build_deps/deps/Release/lzma/include -I/home/sybren/buildbot-builder/linux_glibc217_x86_64_cmake/build_deps/deps/Release/zlib/include -fPIC -fPIC -fPIC

compile options: '-I/home/lenovo/AI_Pkgs/infinigen/blender/3.3/python/include/python3.10 -c'
extra options: '-O3'
CCompilerOpt.cc_test_flags[1013] : testing flags (-Werror)
C compiler: gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -I/home/sybren/buildbot-builder/linux_glibc217_x86_64_cmake/build_deps/deps/Release/sqlite/include -I/home/sybren/buildbot-builder/linux_glibc217_x86_64_cmake/build_deps/deps/Release/bzip2/include -I/home/sybren/buildbot-builder/linux_glibc217_x86_64_cmake/build_deps/deps/Release/lzma/include -I/home/sybren/buildbot-builder/linux_glibc217_x86_64_cmake/build_deps/deps/Release/zlib/include -fPIC -fPIC -fPIC

compile options: '-I/home/lenovo/AI_Pkgs/infinigen/blender/3.3/python/include/python3.10 -c'
extra options: '-Werror'
CCompilerOpt.__init__[1701] : check requested baseline
CCompilerOpt.cc_test_flags[1013] : testing flags (-msse)
C compiler: gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -I/home/sybren/buildbot-builder/linux_glibc217_x86_64_cmake/build_deps/deps/Release/sqlite/include -I/home/sybren/buildbot-builder/linux_glibc217_x86_64_cmake/build_deps/deps/Release/bzip2/include -I/home/sybren/buildbot-builder/linux_glibc217_x86_64_cmake/build_deps/deps/Release/lzma/include -I/home/sybren/buildbot-builder/linux_glibc217_x86_64_cmake/build_deps/deps/Release/zlib/include -fPIC -fPIC -fPIC

compile options: '-I/home/lenovo/AI_Pkgs/infinigen/blender/3.3/python/include/python3.10 -c'
extra options: '-msse'
CCompilerOpt.cc_test_flags[1013] : testing flags (-msse2)
C compiler: gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -I/home/sybren/buildbot-builder/linux_glibc217_x86_64_cmake/build_deps/deps/Release/sqlite/include -I/home/sybren/buildbot-builder/linux_glibc217_x86_64_cmake/build_deps/deps/Release/bzip2/include -I/home/sybren/buildbot-builder/linux_glibc217_x86_64_cmake/build_deps/deps/Release/lzma/include -I/home/sybren/buildbot-builder/linux_glibc217_x86_64_cmake/build_deps/deps/Release/zlib/include -fPIC -fPIC -fPIC

compile options: '-I/home/lenovo/AI_Pkgs/infinigen/blender/3.3/python/include/python3.10 -c'
extra options: '-msse2'
CCompilerOpt.feature_test[1466] : testing feature 'SSE2' with flags (-msse -msse2)
C compiler: gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -I/home/sybren/buildbot-builder/linux_glibc217_x86_64_cmake/build_deps/deps/Release/sqlite/include -I/home/sybren/buildbot-builder/linux_glibc217_x86_64_cmake/build_deps/deps/Release/bzip2/include -I/home/sybren/buildbot-builder/linux_glibc217_x86_64_cmake/build_deps/deps/Release/lzma/include -I/home/sybren/buildbot-builder/linux_glibc217_x86_64_cmake/build_deps/deps/Release/zlib/include -fPIC -fPIC -fPIC

compile options: '-I/home/lenovo/AI_Pkgs/infinigen/blender/3.3/python/include/python3.10 -c'
extra options: '-msse -msse2 -Werror'
CCompilerOpt.feature_test[1466] : testing feature 'SSE' with flags (-msse -msse2)
C compiler: gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -I/home/sybren/buildbot-builder/linux_glibc217_x86_64_cmake/build_deps/deps/Release/sqlite/include -I/home/sybren/buildbot-builder/linux_glibc217_x86_64_cmake/build_deps/deps/Release/bzip2/include -I/home/sybren/buildbot-builder/linux_glibc217_x86_64_cmake/build_deps/deps/Release/lzma/include -I/home/sybren/buildbot-builder/linux_glibc217_x86_64_cmake/build_deps/deps/Release/zlib/include -fPIC -fPIC -fPIC

compile options: '-I/home/lenovo/AI_Pkgs/infinigen/blender/3.3/python/include/python3.10 -c'
extra options: '-msse -msse2 -Werror'
CCompilerOpt.cc_test_flags[1013] : testing flags (-msse3)
C compiler: gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -I/home/sybren/buildbot-builder/linux_glibc217_x86_64_cmake/build_deps/deps/Release/sqlite/include -I/home/sybren/buildbot-builder/linux_glibc217_x86_64_cmake/build_deps/deps/Release/bzip2/include -I/home/sybren/buildbot-builder/linux_glibc217_x86_64_cmake/build_deps/deps/Release/lzma/include -I/home/sybren/buildbot-builder/linux_glibc217_x86_64_cmake/build_deps/deps/Release/zlib/include -fPIC -fPIC -fPIC

compile options: '-I/home/lenovo/AI_Pkgs/infinigen/blender/3.3/python/include/python3.10 -c'
extra options: '-msse3'
CCompilerOpt.feature_test[1466] : testing feature 'SSE3' with flags (-msse -msse2 -msse3)
C compiler: gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -I/home/sybren/buildbot-builder/linux_glibc217_x86_64_cmake/build_deps/deps/Release/sqlite/include -I/home/sybren/buildbot-builder/linux_glibc217_x86_64_cmake/build_deps/deps/Release/bzip2/include -I/home/sybren/buildbot-builder/linux_glibc217_x86_64_cmake/build_deps/deps/Release/lzma/include -I/home/sybren/buildbot-builder/linux_glibc217_x86_64_cmake/build_deps/deps/Release/zlib/include -fPIC -fPIC -fPIC

compile options: '-I/home/lenovo/AI_Pkgs/infinigen/blender/3.3/python/include/python3.10 -c'
extra options: '-msse -msse2 -msse3 -Werror'
CCompilerOpt.__init__[1710] : check requested dispatch-able features
CCompilerOpt.cc_test_flags[1013] : testing flags (-mssse3)
C compiler: gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -I/home/sybren/buildbot-builder/linux_glibc217_x86_64_cmake/build_deps/deps/Release/sqlite/include -I/home/sybren/buildbot-builder/linux_glibc217_x86_64_cmake/build_deps/deps/Release/bzip2/include -I/home/sybren/buildbot-builder/linux_glibc217_x86_64_cmake/build_deps/deps/Release/lzma/include -I/home/sybren/buildbot-builder/linux_glibc217_x86_64_cmake/build_deps/deps/Release/zlib/include -fPIC -fPIC -fPIC

compile options: '-I/home/lenovo/AI_Pkgs/infinigen/blender/3.3/python/include/python3.10 -c'
extra options: '-mssse3'
CCompilerOpt.cc_test_flags[1013] : testing flags (-msse4.1)
C compiler: gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -I/home/sybren/buildbot-builder/linux_glibc217_x86_64_cmake/build_deps/deps/Release/sqlite/include -I/home/sybren/buildbot-builder/linux_glibc217_x86_64_cmake/build_deps/deps/Release/bzip2/include -I/home/sybren/buildbot-builder/linux_glibc217_x86_64_cmake/build_deps/deps/Release/lzma/include -I/home/sybren/buildbot-builder/linux_glibc217_x86_64_cmake/build_deps/deps/Release/zlib/include -fPIC -fPIC -fPIC

compile options: '-I/home/lenovo/AI_Pkgs/infinigen/blender/3.3/python/include/python3.10 -c'
extra options: '-msse4.1'
CCompilerOpt.feature_test[1466] : testing feature 'SSE41' with flags (-msse -msse2 -msse3 -mssse3 -msse4.1)
C compiler: gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -I/home/sybren/buildbot-builder/linux_glibc217_x86_64_cmake/build_deps/deps/Release/sqlite/include -I/home/sybren/buildbot-builder/linux_glibc217_x86_64_cmake/build_deps/deps/Release/bzip2/include -I/home/sybren/buildbot-builder/linux_glibc217_x86_64_cmake/build_deps/deps/Release/lzma/include -I/home/sybren/buildbot-builder/linux_glibc217_x86_64_cmake/build_deps/deps/Release/zlib/include -fPIC -fPIC -fPIC

....................................

creating build/temp.linux-x86_64-3.10/marching_cubes
compile options: '-I/home/lenovo/AI_Pkgs/infinigen/blender/3.3/python/lib/python3.10/site-packages/numpy/core/include -I/home/lenovo/AI_Pkgs/infinigen/blender/3.3/python/lib/python3.10/site-packages/numpy/core/include -Ibuild/src.linux-x86_64-3.10/numpy/distutils/include -I/home/lenovo/AI_Pkgs/infinigen/blender/3.3/python/include/python3.10 -c'
extra options: '-msse -msse2 -msse3'
gcc: ./marching_cubes/_marching_cubes_lewiner_cy.c
In file included from /home/lenovo/AI_Pkgs/infinigen/blender/3.3/python/lib/python3.10/site-packages/numpy/core/include/numpy/ndarraytypes.h:1969,
                 from /home/lenovo/AI_Pkgs/infinigen/blender/3.3/python/lib/python3.10/site-packages/numpy/core/include/numpy/ndarrayobject.h:12,
                 from /home/lenovo/AI_Pkgs/infinigen/blender/3.3/python/lib/python3.10/site-packages/numpy/core/include/numpy/arrayobject.h:4,
                 from ./marching_cubes/_marching_cubes_lewiner_cy.c:694:
/home/lenovo/AI_Pkgs/infinigen/blender/3.3/python/lib/python3.10/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:17:2: warning: #warning "Using deprecated NumPy API, disable it with " "#define NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
   17 | #warning "Using deprecated NumPy API, disable it with " \
      |  ^~~~~~~
gcc -pthread -shared -L/home/sybren/buildbot-builder/linux_glibc217_x86_64_cmake/build_deps/deps/Release/ffi/lib -L/home/sybren/buildbot-builder/linux_glibc217_x86_64_cmake/build_deps/deps/Release/sqlite/lib -L/home/sybren/buildbot-builder/linux_glibc217_x86_64_cmake/build_deps/deps/Release/bzip2/lib -L/home/sybren/buildbot-builder/linux_glibc217_x86_64_cmake/build_deps/deps/Release/lzma/lib -L/home/sybren/buildbot-builder/linux_glibc217_x86_64_cmake/build_deps/deps/Release/zlib/lib build/temp.linux-x86_64-3.10/marching_cubes/_marching_cubes_lewiner_cy.o -o ./_marching_cubes_lewiner_cy.cpython-310-x86_64-linux-gnu.so

########### EXT COMPILER OPTIMIZATION ###########
Platform      :
  Architecture: x64
  Compiler    : gcc

CPU baseline  :
  Requested   : 'min'
  Enabled     : SSE SSE2 SSE3
  Flags       : -msse -msse2 -msse3
  Extra checks: none

CPU dispatch  :
  Requested   : 'max -xop -fma4'
  Enabled     : SSSE3 SSE41 POPCNT SSE42 AVX F16C FMA3 AVX2 AVX512F AVX512CD AVX512_KNL AVX512_KNM AVX512_SKX AVX512_CLX AVX512_CNL AVX512_ICL
  Generated   : none
CCompilerOpt.cache_flush[809] : write cache to path -> /home/lenovo/AI_Pkgs/infinigen/worldgen/terrain/build/temp.linux-x86_64-3.10/ccompiler_opt_cache_ext.py
/home/lenovo/AI_Pkgs/infinigen
/home/lenovo/AI_Pkgs/infinigen/worldgen/assets/creatures/geometry/cpp_utils/setup_linux.py:1: DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives
  from distutils.core import setup, Extension
Compiling bnurbs.pyx because it changed.
[1/1] Cythonizing bnurbs.pyx
/home/lenovo/AI_Pkgs/infinigen/blender/3.3/python/lib/python3.10/site-packages/Cython/Compiler/Main.py:369: FutureWarning: Cython directive 'language_level' not set, using 2 for now (Py2). This will change in a later release! File: /home/lenovo/AI_Pkgs/infinigen/worldgen/assets/creatures/geometry/cpp_utils/bnurbs.pyx
  tree = Parsing.p_module(s, pxd, full_module_name)
warning: bnurbs.pyx:86:7: Non-trivial type declarators in shared declaration (e.g. mix of pointers and values). Each pointer declaration should be on its own line.
warning: bnurbs.pyx:86:14: Non-trivial type declarators in shared declaration (e.g. mix of pointers and values). Each pointer declaration should be on its own line.
warning: bnurbs.pyx:99:8: Non-trivial type declarators in shared declaration (e.g. mix of pointers and values). Each pointer declaration should be on its own line.
warning: bnurbs.pyx:99:17: Non-trivial type declarators in shared declaration (e.g. mix of pointers and values). Each pointer declaration should be on its own line.
running build_ext
building 'bnurbs' extension
creating build
creating build/temp.linux-x86_64-3.10
gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -I/home/sybren/buildbot-builder/linux_glibc217_x86_64_cmake/build_deps/deps/Release/sqlite/include -I/home/sybren/buildbot-builder/linux_glibc217_x86_64_cmake/build_deps/deps/Release/bzip2/include -I/home/sybren/buildbot-builder/linux_glibc217_x86_64_cmake/build_deps/deps/Release/lzma/include -I/home/sybren/buildbot-builder/linux_glibc217_x86_64_cmake/build_deps/deps/Release/zlib/include -fPIC -fPIC -fPIC -I/home/lenovo/AI_Pkgs/infinigen/blender/3.3/python/lib/python3.10/site-packages/numpy/core/include -I/home/lenovo/AI_Pkgs/infinigen/blender/3.3/python/include/python3.10 -c bnurbs.c -o build/temp.linux-x86_64-3.10/bnurbs.o
In file included from /home/lenovo/AI_Pkgs/infinigen/blender/3.3/python/lib/python3.10/site-packages/numpy/core/include/numpy/ndarraytypes.h:1969,
                 from /home/lenovo/AI_Pkgs/infinigen/blender/3.3/python/lib/python3.10/site-packages/numpy/core/include/numpy/ndarrayobject.h:12,
                 from /home/lenovo/AI_Pkgs/infinigen/blender/3.3/python/lib/python3.10/site-packages/numpy/core/include/numpy/arrayobject.h:4,
                 from bnurbs.c:703:
/home/lenovo/AI_Pkgs/infinigen/blender/3.3/python/lib/python3.10/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:17:2: warning: #warning "Using deprecated NumPy API, disable it with " "#define NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
   17 | #warning "Using deprecated NumPy API, disable it with " \
      |  ^~~~~~~
gcc -pthread -shared -L/home/sybren/buildbot-builder/linux_glibc217_x86_64_cmake/build_deps/deps/Release/ffi/lib -L/home/sybren/buildbot-builder/linux_glibc217_x86_64_cmake/build_deps/deps/Release/sqlite/lib -L/home/sybren/buildbot-builder/linux_glibc217_x86_64_cmake/build_deps/deps/Release/bzip2/lib -L/home/sybren/buildbot-builder/linux_glibc217_x86_64_cmake/build_deps/deps/Release/lzma/lib -L/home/sybren/buildbot-builder/linux_glibc217_x86_64_cmake/build_deps/deps/Release/zlib/lib build/temp.linux-x86_64-3.10/bnurbs.o -o /home/lenovo/AI_Pkgs/infinigen/worldgen/assets/creatures/geometry/cpp_utils/bnurbs.cpython-310-x86_64-linux-gnu.so
/home/lenovo/AI_Pkgs/infinigen
```

### Platform
- OS & OS Version: win 22H2
- GPU (?) :3080 laptop
- GPU Driver Version (?) :536.67
- RAM (GB):64

**Comment by araistrick** [comment]
I dont have exact instructions for how to resolve this on windows/wsl, but broadly speaking you will need to look into installing libglm, either via [conda](https://anaconda.org/conda-forge/glm) or your package manager, and make sure that glm/glm.hpp is in your $PATH. Glm is a strict dependency for our 

It may also be worth retrying the command without changes but on our latest 1.0.4.1 version, since I updated the version of landlab we use, which could (?) resolve this.

You also have the option of trying out our rc_1.1.1 branch's MINIMAL_INSTALL variant if a version without terrain/opengl ground truth would interest you.

**Comment by RodenLuo** [comment]
Installed on WSL2 a few weeks ago. Didn't encounter error1. But error 2 was solved by `sudo apt-get install libglm-dev`. This type of error is usually a good case to test GPT's power... https://chat.openai.com/share/64f17f57-034b-4f00-ba2a-0a7802c7b236

**Comment by araistrick** [comment]
Awesome, sorry this prereq wasnt in the instructions, it will be added in 1.1.1
