### ISSUE TITLE
TypeError: 'numpy._DTypeMeta' object is not subscriptable

### ISSUE THREAD

**Issue by shawh-sugon** [princeton-vl/infinigen#172]
# Describe the bug
After the installation is completed, execute `$BLENDER -noaudio --background --python generate.py -- --seed 0 --task coarse -g desert.gin simple.gin --output_folder outputs/hello_world/coarse` to report an error; the error message is as follows：

```
TypeError: 'numpy._DTypeMeta' object is not subscriptable
```

### What version of the code were you using? 
'''
What is the output of `git log -n 1`?
'''
~~~shell
commit a8ba86a394f8757586b4fb15252a3282e56a91de (HEAD -> main, tag: v1.0.4, origin/main, origin/HEAD)
Merge: 0f208a8 359f08e
Author: Alex Raistrick <araistrick@princeton.edu>
Date:   Mon Oct 16 15:58:16 2023 -0400

    Merge pull request #87 from princeton-vl/rc_1.0.4

    v1.0.4 - Pregenerated download tools, ground truth updates, render throughput improvements
~~~

### What command did you run?
```
$BLENDER -noaudio --background --python generate.py -- --seed 0 --task coarse -g desert.gin simple.gin --output_folder outputs/hello_world/coarse
```

### What are your FULL output logs?
```
Blender 3.3.1 (hash b292cfe5a936 built 2022-10-05 00:14:35)
Error: Python: Traceback (most recent call last):
  File "/home/yzhj/data/project/infinigen/worldgen/generate.py", line 20, in <module>
    from terrain import Terrain
  File "/home/yzhj/data/project/infinigen/worldgen/terrain/__init__.py", line 7, in <module>
    from .core import Terrain
  File "/home/yzhj/data/project/infinigen/worldgen/terrain/core.py", line 16, in <module>
    from terrain.scene import scene, transfer_scene_info
  File "/home/yzhj/data/project/infinigen/worldgen/terrain/scene.py", line 10, in <module>
    from terrain.elements.landtiles import LandTiles, Volcanos, FloatingIce
  File "/home/yzhj/data/project/infinigen/worldgen/terrain/elements/landtiles.py", line 12, in <module>
    from terrain.assets.landtiles import assets_to_data, landtile_asset
  File "/home/yzhj/data/project/infinigen/worldgen/terrain/assets/landtiles/__init__.py", line 7, in <module>
    from .core import assets_to_data, landtile_asset
  File "/home/yzhj/data/project/infinigen/worldgen/terrain/assets/landtiles/core.py", line 15, in <module>
    from .ant_landscape import ant_landscape_asset
  File "/home/yzhj/data/project/infinigen/worldgen/terrain/assets/landtiles/ant_landscape.py", line 13, in <module>
    from terrain.land_process.snowfall import run_snowfall
  File "/home/yzhj/data/project/infinigen/worldgen/terrain/land_process/snowfall.py", line 10, in <module>
    from landlab import RasterModelGrid
  File "/home/yzhj/data/project/infinigen/blender/3.3/python/lib/python3.10/site-packages/landlab/__init__.py", line 17, in <module>
    from .core.model_component import Component
  File "/home/yzhj/data/project/infinigen/blender/3.3/python/lib/python3.10/site-packages/landlab/core/model_component.py", line 36, in <module>
    from ..field import FieldError
  File "/home/yzhj/data/project/infinigen/blender/3.3/python/lib/python3.10/site-packages/landlab/field/__init__.py", line 2, in <module>
    from .graph_field import GraphFields
  File "/home/yzhj/data/project/infinigen/blender/3.3/python/lib/python3.10/site-packages/landlab/field/graph_field.py", line 2, in <module>
    import xarray as xr
  File "/home/yzhj/data/project/infinigen/blender/3.3/python/lib/python3.10/site-packages/xarray/__init__.py", line 3, in <module>
    from xarray import testing, tutorial
  File "/home/yzhj/data/project/infinigen/blender/3.3/python/lib/python3.10/site-packages/xarray/testing.py", line 11, in <module>
    from xarray.core.coordinates import Coordinates
  File "/home/yzhj/data/project/infinigen/blender/3.3/python/lib/python3.10/site-packages/xarray/core/coordinates.py", line 16, in <module>
    from xarray.core.alignment import Aligner
  File "/home/yzhj/data/project/infinigen/blender/3.3/python/lib/python3.10/site-packages/xarray/core/alignment.py", line 24, in <module>
    from xarray.core.variable import Variable, as_compatible_data, calculate_dimensions
  File "/home/yzhj/data/project/infinigen/blender/3.3/python/lib/python3.10/site-packages/xarray/core/variable.py", line 48, in <module>
    from xarray.namedarray.core import NamedArray
  File "/home/yzhj/data/project/infinigen/blender/3.3/python/lib/python3.10/site-packages/xarray/namedarray/core.py", line 24, in <module>
    from xarray.namedarray._typing import (
  File "/home/yzhj/data/project/infinigen/blender/3.3/python/lib/python3.10/site-packages/xarray/namedarray/_typing.py", line 28, in <module>
    _DType = TypeVar("_DType", bound=np.dtype[Any])
TypeError: 'numpy._DTypeMeta' object is not subscriptable

Blender quit

```

### If this is your first time running Infinigen, what are the full output logs of `install.sh` ?**
```
########### EXT COMPILER OPTIMIZATION ###########
Platform      :
  Architecture: x64
  Compiler    : gcc

CPU baseline  :
  Requested   : 'min'
  Enabled     : SSE SSE2 SSE3
  Flags       : -msse -msse2 -msse3
  Extra checks: none

CPU dispatch  :
  Requested   : 'max -xop -fma4'
  Enabled     : SSSE3 SSE41 POPCNT SSE42 AVX F16C FMA3 AVX2 AVX512F AVX512CD AVX512_KNL AVX512_KNM AVX512_SKX AVX512_CLX AVX512_CNL AVX512_ICL
  Generated   : none
CCompilerOpt.cache_flush[809] : write cache to path -> /home/yzhj/data/project/infinigen/worldgen/terrain/build/temp.linux-x86_64-3.10/ccompiler_opt_cache_ext.py
/home/yzhj/data/project/infinigen
/home/yzhj/data/project/infinigen/worldgen/assets/creatures/geometry/cpp_utils/setup_linux.py:1: DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives
  from distutils.core import setup, Extension
Compiling bnurbs.pyx because it changed.
[1/1] Cythonizing bnurbs.pyx
/home/yzhj/data/project/infinigen/blender/3.3/python/lib/python3.10/site-packages/Cython/Compiler/Main.py:369: FutureWarning: Cython directive 'language_level' not set, using 2 for now (Py2). This will change in a later release! File: /home/yzhj/data/project/infinigen/worldgen/assets/creatures/geometry/cpp_utils/bnurbs.pyx
  tree = Parsing.p_module(s, pxd, full_module_name)
warning: bnurbs.pyx:86:7: Non-trivial type declarators in shared declaration (e.g. mix of pointers and values). Each pointer declaration should be on its own line.
warning: bnurbs.pyx:86:14: Non-trivial type declarators in shared declaration (e.g. mix of pointers and values). Each pointer declaration should be on its own line.
warning: bnurbs.pyx:99:8: Non-trivial type declarators in shared declaration (e.g. mix of pointers and values). Each pointer declaration should be on its own line.
warning: bnurbs.pyx:99:17: Non-trivial type declarators in shared declaration (e.g. mix of pointers and values). Each pointer declaration should be on its own line.
running build_ext
building 'bnurbs' extension
creating build
creating build/temp.linux-x86_64-3.10
gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -I/home/sybren/buildbot-builder/linux_glibc217_x86_64_cmake/build_deps/deps/Release/sqlite/include -I/home/sybren/buildbot-builder/linux_glibc217_x86_64_cmake/build_deps/deps/Release/bzip2/include -I/home/sybren/buildbot-builder/linux_glibc217_x86_64_cmake/build_deps/deps/Release/lzma/include -I/home/sybren/buildbot-builder/linux_glibc217_x86_64_cmake/build_deps/deps/Release/zlib/include -fPIC -fPIC -fPIC -I/home/yzhj/data/project/infinigen/blender/3.3/python/lib/python3.10/site-packages/numpy/core/include -I/home/yzhj/data/project/infinigen/blender/3.3/python/include/python3.10 -c bnurbs.c -o build/temp.linux-x86_64-3.10/bnurbs.o
In file included from /home/yzhj/data/project/infinigen/blender/3.3/python/lib/python3.10/site-packages/numpy/core/include/numpy/ndarraytypes.h:1969,
                 from /home/yzhj/data/project/infinigen/blender/3.3/python/lib/python3.10/site-packages/numpy/core/include/numpy/ndarrayobject.h:12,
                 from /home/yzhj/data/project/infinigen/blender/3.3/python/lib/python3.10/site-packages/numpy/core/include/numpy/arrayobject.h:4,
                 from bnurbs.c:703:
/home/yzhj/data/project/infinigen/blender/3.3/python/lib/python3.10/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:17:2: warning: #warning "Using deprecated NumPy API, disable it with " "#define NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
   17 | #warning "Using deprecated NumPy API, disable it with " \
      |  ^~~~~~~
gcc -pthread -shared -L/home/sybren/buildbot-builder/linux_glibc217_x86_64_cmake/build_deps/deps/Release/ffi/lib -L/home/sybren/buildbot-builder/linux_glibc217_x86_64_cmake/build_deps/deps/Release/sqlite/lib -L/home/sybren/buildbot-builder/linux_glibc217_x86_64_cmake/build_deps/deps/Release/bzip2/lib -L/home/sybren/buildbot-builder/linux_glibc217_x86_64_cmake/build_deps/deps/Release/lzma/lib -L/home/sybren/buildbot-builder/linux_glibc217_x86_64_cmake/build_deps/deps/Release/zlib/lib build/temp.linux-x86_64-3.10/bnurbs.o -o /home/yzhj/data/project/infinigen/worldgen/assets/creatures/geometry/cpp_utils/bnurbs.cpython-310-x86_64-linux-gnu.so
/home/yzhj/data/project/infinigen
```

### Platform
- OS & OS Version: Ubuntu 22.04.3 LTS
- GPU (?) : GeForce RTX 3070 Lite Hash Rate
- GPU Driver Version (?) : NVIDIA-SMI 525.147.05   Driver Version: 525.147.05   CUDA Version: 12.0
- RAM (GB): 32G

# Additional context

**Comment by MultiTrickFox** [comment]
Same issue but with Osx M1

**Comment by araistrick** [comment]
Hello, I have updated our numpy version on #176 which should fix this issue.
