### ISSUE TITLE
how can i launch UI?

### ISSUE THREAD

**Issue by DeanXLiu** [princeton-vl/infinigen#186]
I installed infinigen as a Blender Python script, Normal install, and how can i launch UI? I executed python -m infinigen.launch_blender and faild, The error is as follows:

/data/infinigen/blender/blender --python /data/infinigen/infinigen/tools/blendscript_import_infinigen.py
GHOST/Wayland: error: XDG_RUNTIME_DIR not set in the environment.
GHOST: failed to initialize display for back-end(s): ['WAYLAND', 'X11']
GHOST: unable to initialize, exiting!

my install log is in the annex
[logs.txt](https://github.com/princeton-vl/infinigen/files/13713357/logs.txt)

**Comment by DeanXLiu** [comment]
I installed again, error like this:


Failed to build infinigen
ERROR: Could not build wheels for infinigen, which is required to install pyproject.toml-based projects
Exception information:
Traceback (most recent call last):
  File "/opt/infinigen/blender/3.6/python/lib/python3.10/site-packages/pip/_internal/cli/base_command.py", line 180, in exc_logging_wrapper
    status = run_func(*args)
  File "/opt/infinigen/blender/3.6/python/lib/python3.10/site-packages/pip/_internal/cli/req_command.py", line 245, in wrapper
    return func(self, options, args)
  File "/opt/infinigen/blender/3.6/python/lib/python3.10/site-packages/pip/_internal/commands/install.py", line 429, in run
    raise InstallationError(
pip._internal.exceptions.InstallationError: Could not build wheels for infinigen, which is required to install pyproject.toml-based projects
Remote version of pip: 23.3.2
Local version of pip:  23.3.2
Was pip installed by pip? True
Removed build tracker: '/tmp/pip-build-tracker-s6vyb9iu'

**Comment by yyyybq** [comment]
Have  the bug be solved? Thanks!
