### ISSUE TITLE
hello world error

### ISSUE THREAD

**Issue by DeanXLiu** [princeton-vl/infinigen#187]
when I run python -m infinigen_examples.generate_nature --seed 0 --task coarse -g desert.gin simple.gin --output_folder outputs/hello_world/coarse

error like this:

you are using blender=4.0.0 which is not supported please use 3.6.0

**Comment by araistrick** [comment]
Hello, could you share what installation method and logs you used? 

Both our pyproject.toml (for pip installation) and interactive_blender.sh scripts explicitly specify to download bpy==3.6.0, so if they downloaded 4.0 somehow then something weird has gone on. If you installed bpy manually you may need to erase that installation and use our provided installation methods.

**Comment by DeanXLiu** [comment]
I changed bpy to 3.6.0, and run the  frist code successful, but when I run python -m infinigen_examples.generate_nature --seed 0 --task populate fine_terrain -g desert.gin simple.gin --input_folder outputs/hello_world/coarse --output_folder outputs/hello_world/fine

error like this:

[08:58:17.962] [infinigen.times] [INFO] | [meshing OpaqueTerrain]
[08:58:17.962] [infinigen.times] [INFO] | [OpaqueSphericalMesher: frontview_mesher]
[08:59:19.212] [infinigen.times] [INFO] | [OpaqueSphericalMesher: frontview_mesher] failed with <class 'AttributeError'>
[08:59:19.212] [infinigen.times] [INFO] | [meshing OpaqueTerrain] failed with <class 'AttributeError'>
[08:59:19.212] [infinigen.times] [INFO] | [MAIN TOTAL] failed with <class 'AttributeError'>
Traceback (most recent call last):
  File "/root/anaconda3/envs/infinigen3/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/root/anaconda3/envs/infinigen3/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/media/huanqiu/e36b882f-b751-4f41-a460-3fa43a79ff32/infinigen3/infinigen/infinigen_examples/generate_nature.py", line 438, in <module>
    main(args)
  File "/media/huanqiu/e36b882f-b751-4f41-a460-3fa43a79ff32/infinigen3/infinigen/infinigen_examples/generate_nature.py", line 409, in main
    execute_tasks.main(
  File "/media/huanqiu/e36b882f-b751-4f41-a460-3fa43a79ff32/infinigen3/infinigen/infinigen/core/execute_tasks.py", line 421, in main
    execute_tasks(
  File "/root/anaconda3/envs/infinigen3/lib/python3.10/site-packages/gin/config.py", line 1605, in gin_wrapper
    utils.augment_exception_message_and_reraise(e, err_str)
  File "/root/anaconda3/envs/infinigen3/lib/python3.10/site-packages/gin/utils.py", line 41, in augment_exception_message_and_reraise
    raise proxy.with_traceback(exception.__traceback__) from None
  File "/root/anaconda3/envs/infinigen3/lib/python3.10/site-packages/gin/config.py", line 1582, in gin_wrapper
    return fn(*new_args, **new_kwargs)
  File "/media/huanqiu/e36b882f-b751-4f41-a460-3fa43a79ff32/infinigen3/infinigen/infinigen/core/execute_tasks.py", line 344, in execute_tasks
    terrain.fine_terrain(output_folder, optimize_terrain_diskusage=optimize_terrain_diskusage)
  File "/media/huanqiu/e36b882f-b751-4f41-a460-3fa43a79ff32/infinigen3/infinigen/infinigen/terrain/core.py", line 266, in fine_terrain
    fine_meshes, _ = self.export(spherical=True, cameras=[bpy.context.scene.camera])
  File "/root/anaconda3/envs/infinigen3/lib/python3.10/site-packages/gin/config.py", line 1605, in gin_wrapper
    utils.augment_exception_message_and_reraise(e, err_str)
  File "/root/anaconda3/envs/infinigen3/lib/python3.10/site-packages/gin/utils.py", line 41, in augment_exception_message_and_reraise
    raise proxy.with_traceback(exception.__traceback__) from None
  File "/root/anaconda3/envs/infinigen3/lib/python3.10/site-packages/gin/config.py", line 1582, in gin_wrapper
    return fn(*new_args, **new_kwargs)
  File "/media/huanqiu/e36b882f-b751-4f41-a460-3fa43a79ff32/infinigen3/infinigen/infinigen/terrain/core.py", line 123, in export
    mesh = mesher([element for element in opaque_elements])
  File "/media/huanqiu/e36b882f-b751-4f41-a460-3fa43a79ff32/infinigen3/infinigen/infinigen/terrain/mesher/spherical_mesher.py", line 108, in __call__
    mesh1 = self.frontview_mesher(kernels)
  File "/media/huanqiu/e36b882f-b751-4f41-a460-3fa43a79ff32/infinigen3/infinigen/infinigen/terrain/mesher/frontview_spherical_mesher.py", line 234, in __call__
    catted_mesh = Mesh.cat([mesh, *meshes])
  File "/media/huanqiu/e36b882f-b751-4f41-a460-3fa43a79ff32/infinigen3/infinigen/infinigen/terrain/utils/mesh.py", line 231, in cat
    faces = np.zeros((0, 3), dtype=np.int)
  File "/root/anaconda3/envs/infinigen3/lib/python3.10/site-packages/numpy/__init__.py", line 324, in __getattr__
    raise AttributeError(__former_attrs__[attr])
AttributeError: module 'numpy' has no attribute 'int'.
`np.int` was a deprecated alias for the builtin `int`. To avoid this error in existing code, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  In call to configurable 'export' (<function Terrain.export at 0x7fcbf557acb0>)
  In call to configurable 'execute_tasks' (<function execute_tasks at 0x7fcbf51c6cb0>)
Error: Not freed memory blocks: 1, total unfreed memory 0.132236 MB



my first time install log:
[logs2.txt](https://github.com/princeton-vl/infinigen/files/13747212/logs2.txt)
 then I change async to async_(/OpenGL/GL/SGIX/async.py)
 
 and second time install log:
[logs3.txt](https://github.com/princeton-vl/infinigen/files/13747220/logs3.txt)
