### ISSUE TITLE
运行资产生成出错

### ISSUE THREAD

**Issue by ry1213428** [princeton-vl/infinigen#188]
>>> from infinigen.assets.scatters import seashells
>>> seashells.apply(bpy.context.active_object)
Traceback (most recent call last):
  File "<blender_console>", line 1, in <module>
  File "/home/zz/infinigen/infinigen/assets/scatters/seashells.py", line 19, in apply
    factories = list(MolluskFactory(np.random.randint(1e5)) for _ in range(n_species))
  File "/home/zz/infinigen/infinigen/assets/scatters/seashells.py", line 19, in <genexpr>
    factories = list(MolluskFactory(np.random.randint(1e5)) for _ in range(n_species))
  File "/home/zz/infinigen/infinigen/assets/mollusk/generate.py", line 38, in __init__
    self.material = surface.shaderfunc_to_material(self.shader_mollusk, base_hue, self.factory.ratio,
  File "/home/zz/infinigen/infinigen/core/surface.py", line 180, in shaderfunc_to_material
    material.node_tree.nodes.remove(material.node_tree.nodes['Principled BSDF'])  # remove the default BSDF
KeyError: 'bpy_prop_collection[key]: key "Principled BSDF" not found'

**Comment by araistrick** [comment]
Hello, what version of `bpy` are you using? This issue would mostly arrise if using a version other than `bpy==3.6.0`

**Comment by araistrick** [comment]
Closing due to inactivity
