### ISSUE TITLE
CalledProcessError: Failed building editable for infinigen (WSL2)

### ISSUE THREAD

**Issue by CreativeNick** [princeton-vl/infinigen#194]
# Describe the bug
Hey all, I followed the instructions in `Installation.md` but when running `bash scripts/install/interactive_blender.sh` I receive a CalledProcessError. I am running this via Windows WSL2 x86_64 and am using Ubuntu 22.04.3 LTS. I made sure all packages, etc were fully updated. I've attempted this multiple times and also tried different methods, resetting my Ubuntu each time to make sure one attempt doesn't affect the other.

### What command did you run?
`bash scripts/install/interactive_blender.sh`
 
### Error section from output logs
```
...
...
      In file included from source/cpu/soil_machine/SoilMachine.cpp:18:
      source/cpu/soil_machine/layermap.h:37:10: fatal error: glm/glm.hpp: No such file or directory
         37 | #include <glm/glm.hpp>
            |          ^~~~~~~~~~~~~
      compilation terminated.
      make: *** [Makefile:11: terrain] Error 1
      Traceback (most recent call last):
        File "/home/nick/infinigen/blender/3.6/python/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/home/nick/infinigen/blender/3.6/python/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/home/nick/infinigen/blender/3.6/python/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 273, in build_editable
          return hook(wheel_directory, config_settings, metadata_directory)
        File "/tmp/pip-build-env-hrumx92y/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 436, in build_editable
          return self._build_with_temp_dir(
        File "/tmp/pip-build-env-hrumx92y/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 389, in _build_with_temp_dir
          self.run_setup()
        File "/tmp/pip-build-env-hrumx92y/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 44, in <module>
        File "/home/nick/infinigen/blender/3.6/python/lib/python3.10/subprocess.py", line 526, in run
          raise CalledProcessError(retcode, process.args,
      subprocess.CalledProcessError: Command '['make', 'terrain']' returned non-zero exit status 2.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building editable for infinigen
Failed to build infinigen
ERROR: Could not build wheels for infinigen, which is required to install pyproject.toml-based projects
``` 

### Full install logs.txt**
[logs.txt](https://github.com/princeton-vl/infinigen/files/14155586/logs.txt)

### Platform
- OS & OS Version: Windows 11
- GPU: NVIDIA GeForce RTX 3080
- GPU Driver Version: Version 551.23
- RAM (GB): 16

# Additional context
As mentioned above, I am using Windows WSL2 to run this.

I also attempted to run `python -m infinigen.launch_blender` to see what would happen, and when I tried to interact with Blender the screen would glitch out entirely. I'm not entirely sure what's causing this but I assume it's caused by the error above.

Here's a screenshot of what the Blender UI looks like after launching it.
![image](https://github.com/princeton-vl/infinigen/assets/43157506/4ef81e64-486c-4378-9002-0c4377891848)

**Comment by araistrick** [comment]
Hello, it seems glm is missing, you will need to find a way to install it for WSL2. If possible I recommend retrying using the conda dependency installation method recently added to our Install docs. I believe conda is well supported on WSL2, and I believe it has a package you can install for glm. So if you add conda to your build paths as shown in Installation.md it should work.
