### ISSUE TITLE
Gnerater river (fluid) faild in the corse generation stage

### ISSUE THREAD

**Issue by iYuqinL** [princeton-vl/infinigen#204]
# Describe the bug

Generate the river (fluid) scene faild, and throw a camera view error:

## Steps to Reproduce

run the command to reproduce:

```bash
python3 -m infinigen_examples.generate_nature --seed 61fc9999 --task coarse --task_uniqname coarse --output_folder outputs/river --config river.gin simulated_river.gin fast_terrain_assets.gin  --overrides execute_tasks.frame_range=\[100,244\] execute_tasks.camera_id=\[0,\ 0\]
```

### What version of the code were you using? 

331b4e5e8b3d84f8a31f395c8a344df20844195e

<img width="1022" alt="image" src="https://github.com/princeton-vl/infinigen/assets/25427848/3004e766-b370-4d6d-a605-e99f85e251cc">

### What command did you run?

```bash
python3 -m infinigen_examples.generate_nature --seed 61fc9999 --task coarse --task_uniqname coarse --output_folder outputs/river --config river.gin simulated_river.gin fast_terrain_assets.gin  --overrides execute_tasks.frame_range=\[100,244\] execute_tasks.camera_id=\[0,\ 0\]
```

### What are your FULL output logs?

```plaintext
[12:06:14.345] [infinigen.times] [INFO] | [bushes] finished in 0:00:08.120638
[12:06:14.358] [infinigen.times] [INFO] | [camera_preprocess]
[12:06:14.387] [infinigen.times] [INFO] | [Building placeholders KDTree]
[12:06:14.387] [infinigen.core.placement.camera] [INFO] | Building placeholder kd for 184 objects
[12:06:14.409] [infinigen.times] [INFO] | [Building placeholders KDTree] finished in 0:00:00.021952
[12:06:14.409] [infinigen.times] [INFO] | [Building terrain BVHTree]
[12:06:14.837] [infinigen.times] [INFO] | [Building terrain BVHTree] finished in 0:00:00.428547
[12:06:14.840] [infinigen.times] [INFO] | [camera_preprocess] finished in 0:00:00.481410
[12:06:14.840] [infinigen.times] [INFO] | [pose_cameras]
Searching for camera viewpoints:   0%|                                                                                                                       | 0/1 [09:07<?, ?it/s]
[12:15:22.389] [infinigen.times] [INFO] | [pose_cameras] failed with <class 'ValueError'>
[12:15:22.390] [infinigen.times] [INFO] | [MAIN TOTAL] failed with <class 'ValueError'>
Traceback (most recent call last):
  File "/mnt/Nerf001/rain/.anaconda3/envs/infinigen/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/mnt/Nerf001/rain/.anaconda3/envs/infinigen/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/mnt/Nerf001/rain/Projects/openSrc/infinigen/infinigen_examples/generate_nature.py", line 438, in <module>
    main(args)
  File "/mnt/Nerf001/rain/Projects/openSrc/infinigen/infinigen_examples/generate_nature.py", line 409, in main
    execute_tasks.main(
  File "/mnt/Nerf001/rain/Projects/openSrc/infinigen/infinigen/core/execute_tasks.py", line 418, in main
    execute_tasks(
  File "/mnt/Nerf001/rain/.anaconda3/envs/infinigen/lib/python3.10/site-packages/gin/config.py", line 1605, in gin_wrapper
    utils.augment_exception_message_and_reraise(e, err_str)
  File "/mnt/Nerf001/rain/.anaconda3/envs/infinigen/lib/python3.10/site-packages/gin/utils.py", line 41, in augment_exception_message_and_reraise
    raise proxy.with_traceback(exception.__traceback__) from None
  File "/mnt/Nerf001/rain/.anaconda3/envs/infinigen/lib/python3.10/site-packages/gin/config.py", line 1582, in gin_wrapper
    return fn(*new_args, **new_kwargs)
  File "/mnt/Nerf001/rain/Projects/openSrc/infinigen/infinigen/core/execute_tasks.py", line 328, in execute_tasks
    compose_scene_func(output_folder, scene_seed)
  File "/mnt/Nerf001/rain/.anaconda3/envs/infinigen/lib/python3.10/site-packages/gin/config.py", line 1605, in gin_wrapper
    utils.augment_exception_message_and_reraise(e, err_str)
  File "/mnt/Nerf001/rain/.anaconda3/envs/infinigen/lib/python3.10/site-packages/gin/utils.py", line 41, in augment_exception_message_and_reraise
    raise proxy.with_traceback(exception.__traceback__) from None
  File "/mnt/Nerf001/rain/.anaconda3/envs/infinigen/lib/python3.10/site-packages/gin/config.py", line 1582, in gin_wrapper
    return fn(*new_args, **new_kwargs)
  File "/mnt/Nerf001/rain/Projects/openSrc/infinigen/infinigen_examples/generate_nature.py", line 176, in compose_scene
    p.run_stage(
  File "/mnt/Nerf001/rain/Projects/openSrc/infinigen/infinigen/core/util/pipeline.py", line 76, in run_stage
    ret = fn(*args, **kwargs)
  File "/mnt/Nerf001/rain/Projects/openSrc/infinigen/infinigen_examples/generate_nature.py", line 178, in <lambda>
    lambda: cam_util.configure_cameras(camera_rigs, bbox, scene_preprocessed),
  File "/mnt/Nerf001/rain/.anaconda3/envs/infinigen/lib/python3.10/site-packages/gin/config.py", line 1605, in gin_wrapper
    utils.augment_exception_message_and_reraise(e, err_str)
  File "/mnt/Nerf001/rain/.anaconda3/envs/infinigen/lib/python3.10/site-packages/gin/utils.py", line 41, in augment_exception_message_and_reraise
    raise proxy.with_traceback(exception.__traceback__) from None
  File "/mnt/Nerf001/rain/.anaconda3/envs/infinigen/lib/python3.10/site-packages/gin/config.py", line 1582, in gin_wrapper
    return fn(*new_args, **new_kwargs)
  File "/mnt/Nerf001/rain/Projects/openSrc/infinigen/infinigen/core/placement/camera.py", line 462, in configure_cameras
    base_views = compute_base_views(
  File "/mnt/Nerf001/rain/.anaconda3/envs/infinigen/lib/python3.10/site-packages/gin/config.py", line 1605, in gin_wrapper
    utils.augment_exception_message_and_reraise(e, err_str)
  File "/mnt/Nerf001/rain/.anaconda3/envs/infinigen/lib/python3.10/site-packages/gin/utils.py", line 41, in augment_exception_message_and_reraise
    raise proxy.with_traceback(exception.__traceback__) from None
  File "/mnt/Nerf001/rain/.anaconda3/envs/infinigen/lib/python3.10/site-packages/gin/config.py", line 1582, in gin_wrapper
    return fn(*new_args, **new_kwargs)
  File "/mnt/Nerf001/rain/Projects/openSrc/infinigen/infinigen/core/placement/camera.py", line 413, in compute_base_views
    raise ValueError(f'Could not find {n_views} camera views')
ValueError: Could not find 1 camera views
  In call to configurable 'compute_base_views' (<function compute_base_views at 0x7f3acca6c820>)
  In call to configurable 'configure_cameras' (<function configure_cameras at 0x7f3acca36d40>)
  In call to configurable 'compose_scene' (<function compose_scene at 0x7f3dba0cb6d0>)
  In call to configurable 'execute_tasks' (<function execute_tasks at 0x7f3ac362d630>)
```

### Platform
- OS & OS Version:  Ubuntu 20.04
- GPU (?) : nvidia-A100
- GPU Driver Version (?) : 530
- RAM (GB): 256 GB

**Comment by araistrick** [comment]
Hello, please try again with another seed, camera selection can sometimes fail due to an unlucky configuration - this is expected and for now we expect users to just try new seeds, since no one seed is special. We will update the docs to a different seed if the current version has this issue with the provided seed. 

Camera selection is particularly restricted for rivers though, @karhankayan we may need to check its still working in general and not always failing.

**Comment by karhankayan** [comment]
I believe this is an actual bug. The river terrains seem to have changed, and thus the simulated rivers + camera positioning is broken. I will debug this.

**Comment by karhankayan** [comment]
This issue is caused by point 3 [here](https://github.com/princeton-vl/infinigen/issues/262#issuecomment-2228729008). I will close once we patch it.
