### ISSUE TITLE
compile_terrain error during install

### ISSUE THREAD

**Issue by xi-zc** [princeton-vl/infinigen#206]
# Describe the bug
error when compile_terrain.sh in pip install -e .
## Steps to Reproduce
pip install -e .
### What version of the code were you using? 
latest

### What command did you run?
sudo apt-get install wget cmake g++ libgles2-mesa-dev libglew-dev libglfw3-dev libglm-dev
git clone https://github.com/princeton-vl/infinigen.git
cd infinigen
conda create --name infinigen python=3.10
conda activate infinigen
pip install -e .

### What are your FULL output logs?
pip install -e .
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Obtaining file:///home/cscg-east92007/disk8/xzc/software/infinigen
  Installing build dependencies ... done
  Checking if build backend supports build_editable ... done
  Getting requirements to build editable ... done
  Installing backend dependencies ... done
  Preparing editable metadata (pyproject.toml) ... done
Collecting bpy==3.6.0 (from infinigen==1.2.4)
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/9c/cf/536e231d0fff186e46668ae701f6788cdd740ff48545dadfad234bb0255b/bpy-3.6.0-cp310-cp310-manylinux_2_28_x86_64.whl (371.4 MB)
Collecting einops (from infinigen==1.2.4)
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/29/0b/2d1c0ebfd092e25935b86509a9a817159212d82aa43d7fb07eca4eeff2c2/einops-0.7.0-py3-none-any.whl (44 kB)
Collecting flow-vis (from infinigen==1.2.4)
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/24/ba/60c0a8289196778998c98d3d61c73fa401619e89174e9ab91c946219d537/flow_vis-0.1-py3-none-any.whl (4.4 kB)
Collecting frozendict (from infinigen==1.2.4)
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/2e/78/e362b0dc75855807d48c273a69e9e60b61ed9003c0553f5ea0071528df7a/frozendict-2.4.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (116 kB)
Collecting geomdl (from infinigen==1.2.4)
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/48/32/559b938e6654ecdf87d256ac2bfd9a25464560a312a58aaf25076d0ce48e/geomdl-5.3.1-py2.py3-none-any.whl (147 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 147.6/147.6 kB 5.1 MB/s eta 0:00:00
Collecting gin-config>=0.5.0 (from infinigen==1.2.4)
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/11/8f/9f1894efa1bb15e98613244b24dfbacfe2309e0ac3cfc27d4c608c2270d2/gin_config-0.5.0-py3-none-any.whl (61 kB)
Collecting imageio (from infinigen==1.2.4)
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/02/25/66533a8390e3763cf8254dee143dbf8a830391ea60d2762512ba7f9ddfbe/imageio-2.34.0-py3-none-any.whl (313 kB)
Collecting matplotlib (from infinigen==1.2.4)
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/c1/f2/325897d6c498278b0f8b460d44b516f5db865ddb4ba9018e9fe58a3e4633/matplotlib-3.8.3-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (11.6 MB)
Collecting numpy (from infinigen==1.2.4)
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/4b/d7/ecf66c1cd12dc28b4040b15ab4d17b773b87fa9d29ca16125de01adb36cd/numpy-1.26.4-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (18.2 MB)
Collecting opencv-python (from infinigen==1.2.4)
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/d9/64/7fdfb9386511cd6805451e012c537073a79a958a58795c4e602e538c388c/opencv_python-4.9.0.80-cp37-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (62.2 MB)
Collecting psutil (from infinigen==1.2.4)
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/c5/4f/0e22aaa246f96d6ac87fe5ebb9c5a693fbe8877f537a1022527c47ca43c5/psutil-5.9.8-cp36-abi3-manylinux_2_12_x86_64.manylinux2010_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (288 kB)
Collecting scikit-image (from infinigen==1.2.4)
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/f1/6c/49f5a0ce8ddcdbdac5ac69c129654938cc6de0a936303caa6cad495ceb2a/scikit_image-0.22.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (14.7 MB)
Collecting scikit-learn (from infinigen==1.2.4)
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/bc/b9/6a637668d69de04b7f8b917e837aff282950601f09998a5f6c9f23f6642d/scikit_learn-1.4.1.post1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (12.1 MB)
Collecting scipy (from infinigen==1.2.4)
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/f5/aa/8e6071a5e4dca4ec68b5b22e4991ee74c59c5d372112b9c236ec1faff57d/scipy-1.12.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (38.4 MB)
Collecting submitit (from infinigen==1.2.4)
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/eb/db/64ade58ecdd41b2fae6174ab9d3dd62112c0cc0b3f71d5672cd29877f197/submitit-1.5.1-py3-none-any.whl (74 kB)
Collecting tqdm (from infinigen==1.2.4)
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/2a/14/e75e52d521442e2fcc9f1df3c5e456aead034203d4797867980de558ab34/tqdm-4.66.2-py3-none-any.whl (78 kB)
Collecting trimesh (from infinigen==1.2.4)
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/e8/90/607b1c39f8e67d519c1d146082fd170132f39e3433092e88b36719380466/trimesh-4.1.8-py3-none-any.whl (690 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 690.6/690.6 kB 13.1 MB/s eta 0:00:00
Collecting pandas (from infinigen==1.2.4)
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/19/df/8d789d96a9e338cf28cb7978fa93ef5da53137624b7ef032f30748421c2b/pandas-2.2.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (13.0 MB)
Collecting landlab>=2.6.0 (from infinigen==1.2.4)
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/dc/45/78115597d156053874bd44baa99d2016ff4f8cbdca9ff62b0aca47779dc3/landlab-2.7.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (10.8 MB)
Collecting pycparser (from infinigen==1.2.4)
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/62/d5/5f610ebe421e85889f2e55e33b7f9a6795bd982198517d912eb1c76e1a53/pycparser-2.21-py2.py3-none-any.whl (118 kB)
Collecting pyrender (from infinigen==1.2.4)
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/28/88/174c28b9d3d03cf6d8edb6f637458f30f1cf1a2bd7a617cbd9dadb1740f6/pyrender-0.1.45-py3-none-any.whl (1.2 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.2/1.2 MB 11.8 MB/s eta 0:00:00
Collecting vnoise (from infinigen==1.2.4)
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/2e/f8/db4e04f4466a356137eb79152f1f8562d5052e223c44f67adb796f66b07d/vnoise-0.1.0-py3-none-any.whl (6.9 kB)
Collecting cython (from bpy==3.6.0->infinigen==1.2.4)
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/4a/58/03fc975d1e2ebed9c7bd469a91820b1a673e26e2d9b52303bda7ae0afaf8/Cython-3.0.9-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.6 MB)
Collecting requests (from bpy==3.6.0->infinigen==1.2.4)
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/70/8e/0e2d847013cb52cd35b38c009bb167a1a26b2ce6cd6965bf26b47bc0bf44/requests-2.31.0-py3-none-any.whl (62 kB)
Collecting zstandard (from bpy==3.6.0->infinigen==1.2.4)
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/c9/79/07f6d2670fa2708ae3b79aabb82da78e9cbdb08d9bafadf8638d356775ff/zstandard-0.22.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (5.4 MB)
Collecting bmipy (from landlab>=2.6.0->infinigen==1.2.4)
  Using cached bmipy-2.0.1-py3-none-any.whl
Collecting netcdf4 (from landlab>=2.6.0->infinigen==1.2.4)
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/aa/5a/3bcfa7eb0101c7f64cf86616b3613548a45272906f22b45940934016c597/netCDF4-1.6.5-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (5.5 MB)
Collecting pyyaml (from landlab>=2.6.0->infinigen==1.2.4)
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/29/61/bf33c6c85c55bc45a29eee3195848ff2d518d84735eb0e2d8cb42e0d285e/PyYAML-6.0.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (705 kB)
Collecting pyshp!=2.3.0 (from landlab>=2.6.0->infinigen==1.2.4)
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/98/2f/68116db5b36b895c0450e3072b8cb6c2fac0359279b182ea97014d3c8ac0/pyshp-2.3.1-py2.py3-none-any.whl (46 kB)
Collecting rich-click (from landlab>=2.6.0->infinigen==1.2.4)
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/ea/6a/89ee4e245a8c21791d7db3669931948f237a421fafec72de6d1e7e25f3b2/rich_click-1.7.3-py3-none-any.whl (32 kB)
Collecting statsmodels (from landlab>=2.6.0->infinigen==1.2.4)
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/39/88/d8cd64c8c56131a796215ce7f80ebb73e97200e6e6de26580cd20ae56e3e/statsmodels-0.14.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (10.8 MB)
Collecting xarray>=0.16 (from landlab>=2.6.0->infinigen==1.2.4)
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/47/f6/f2d4a0a2a4eb6fc427f1e482987e24104c9710c4244c76ea75b55243ada0/xarray-2024.2.0-py3-none-any.whl (1.1 MB)
Collecting pillow>=8.3.2 (from imageio->infinigen==1.2.4)
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/cb/c3/98faa3e92cf866b9446c4842f1fe847e672b2f54e000cb984157b8095797/pillow-10.2.0-cp310-cp310-manylinux_2_28_x86_64.whl (4.5 MB)
Collecting contourpy>=1.0.1 (from matplotlib->infinigen==1.2.4)
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/58/56/e2c43dcfa1f9c7db4d5e3d6f5134b24ed953f4e2133a4b12f0062148db58/contourpy-1.2.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (310 kB)
Collecting cycler>=0.10 (from matplotlib->infinigen==1.2.4)
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/e7/05/c19819d5e3d95294a6f5947fb9b9629efb316b96de511b418c53d245aae6/cycler-0.12.1-py3-none-any.whl (8.3 kB)
Collecting fonttools>=4.22.0 (from matplotlib->infinigen==1.2.4)
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/a6/ba/5eac3e9c9bbc2dea3606e46de08bcef0908d74e7ccf89a71701b95a16747/fonttools-4.49.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (4.6 MB)
Collecting kiwisolver>=1.3.1 (from matplotlib->infinigen==1.2.4)
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/6f/40/4ab1fdb57fced80ce5903f04ae1aed7c1d5939dda4fd0c0aa526c12fe28a/kiwisolver-1.4.5-cp310-cp310-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (1.6 MB)
Collecting packaging>=20.0 (from matplotlib->infinigen==1.2.4)
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/49/df/1fceb2f8900f8639e278b056416d49134fb8d84c5942ffaa01ad34782422/packaging-24.0-py3-none-any.whl (53 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 53.5/53.5 kB 8.5 MB/s eta 0:00:00
Collecting pyparsing>=2.3.1 (from matplotlib->infinigen==1.2.4)
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/9d/ea/6d76df31432a0e6fdf81681a895f009a4bb47b3c39036db3e1b528191d52/pyparsing-3.1.2-py3-none-any.whl (103 kB)
Collecting python-dateutil>=2.7 (from matplotlib->infinigen==1.2.4)
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/ec/57/56b9bcc3c9c6a792fcbaf139543cee77261f3651ca9da0c93f5c1221264b/python_dateutil-2.9.0.post0-py2.py3-none-any.whl (229 kB)
Collecting pytz>=2020.1 (from pandas->infinigen==1.2.4)
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/9c/3d/a121f284241f08268b21359bd425f7d4825cffc5ac5cd0e1b3d82ffd2b10/pytz-2024.1-py2.py3-none-any.whl (505 kB)
Collecting tzdata>=2022.7 (from pandas->infinigen==1.2.4)
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/65/58/f9c9e6be752e9fcb8b6a0ee9fb87e6e7a1f6bcab2cdc73f02bb7ba91ada0/tzdata-2024.1-py2.py3-none-any.whl (345 kB)
Collecting freetype-py (from pyrender->infinigen==1.2.4)
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/5f/34/76cfe866e482745ea8c9956b0be6198fd72d08d2be77b71596afdb8cd89f/freetype_py-2.4.0-py3-none-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_12_x86_64.manylinux2010_x86_64.whl (1.0 MB)
Collecting networkx (from pyrender->infinigen==1.2.4)
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/d5/f0/8fbc882ca80cf077f1b246c0e3c3465f7f415439bdea6b899f6b19f61f70/networkx-3.2.1-py3-none-any.whl (1.6 MB)
Collecting pyglet>=1.4.10 (from pyrender->infinigen==1.2.4)
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/58/2e/d866d8c26532633e83f1854e65ebbdf3eaf43b0096f7907019e72877b90d/pyglet-2.0.14-py3-none-any.whl (876 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 876.8/876.8 kB 9.2 MB/s eta 0:00:00
Collecting PyOpenGL==3.1.0 (from pyrender->infinigen==1.2.4)
  Using cached PyOpenGL-3.1.0-py3-none-any.whl
Collecting six (from pyrender->infinigen==1.2.4)
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/d9/5a/e7c31adbe875f2abbb91bd84cf2dc52d792b5a01506781dbcf25c91daf11/six-1.16.0-py2.py3-none-any.whl (11 kB)
Collecting tifffile>=2022.8.12 (from scikit-image->infinigen==1.2.4)
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/cd/0b/33610b4d0d1bb83a6bfd20ed838f52e02a44e9b439116cd4f3d424e81a80/tifffile-2024.2.12-py3-none-any.whl (224 kB)
Collecting lazy_loader>=0.3 (from scikit-image->infinigen==1.2.4)
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/a1/c3/65b3814e155836acacf720e5be3b5757130346670ac454fee29d3eda1381/lazy_loader-0.3-py3-none-any.whl (9.1 kB)
Collecting joblib>=1.2.0 (from scikit-learn->infinigen==1.2.4)
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/10/40/d551139c85db202f1f384ba8bcf96aca2f329440a844f924c8a0040b6d02/joblib-1.3.2-py3-none-any.whl (302 kB)
Collecting threadpoolctl>=2.0.0 (from scikit-learn->infinigen==1.2.4)
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/b1/2c/f504e55d98418f2fcf756a56877e6d9a45dd5ed28b3d7c267b300e85ad5b/threadpoolctl-3.3.0-py3-none-any.whl (17 kB)
Collecting cloudpickle>=1.2.1 (from submitit->infinigen==1.2.4)
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/96/43/dae06432d0c4b1dc9e9149ad37b4ca8384cf6eb7700cd9215b177b914f0a/cloudpickle-3.0.0-py3-none-any.whl (20 kB)
Collecting typing_extensions>=3.7.4.2 (from submitit->infinigen==1.2.4)
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/f9/de/dc04a3ea60b22624b51c703a84bbe0184abcd1d0b9bc8074b5d6b7ab90bb/typing_extensions-4.10.0-py3-none-any.whl (33 kB)
Requirement already satisfied: setuptools in /home/cscg-east92007/anaconda3/envs/infinigen/lib/python3.10/site-packages (from vnoise->infinigen==1.2.4) (68.2.2)
Collecting black (from bmipy->landlab>=2.6.0->infinigen==1.2.4)
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/46/b8/70a3cab340301d480f601d483452e6e68da61202abad881f1a91250c2d27/black-24.2.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (1.7 MB)
Collecting click (from bmipy->landlab>=2.6.0->infinigen==1.2.4)
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/00/2e/d53fa4befbf2cfa713304affc7ca780ce4fc1fd8710527771b58311a3229/click-8.1.7-py3-none-any.whl (97 kB)
Collecting jinja2 (from bmipy->landlab>=2.6.0->infinigen==1.2.4)
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/30/6d/6de6be2d02603ab56e72997708809e8a5b0fbfee080735109b40a3564843/Jinja2-3.1.3-py3-none-any.whl (133 kB)
Collecting cftime (from netcdf4->landlab>=2.6.0->infinigen==1.2.4)
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/fd/c6/03abb5b3e66ca8914b7a4f17ceca72a9b773f11530e973882695bcf2ee5e/cftime-1.6.3-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (1.3 MB)
Collecting certifi (from netcdf4->landlab>=2.6.0->infinigen==1.2.4)
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/ba/06/a07f096c664aeb9f01624f858c3add0a4e913d6c96257acb4fce61e7de14/certifi-2024.2.2-py3-none-any.whl (163 kB)
Collecting charset-normalizer<4,>=2 (from requests->bpy==3.6.0->infinigen==1.2.4)
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/da/f1/3702ba2a7470666a62fd81c58a4c40be00670e5006a67f4d626e57f013ae/charset_normalizer-3.3.2-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (142 kB)
Collecting idna<4,>=2.5 (from requests->bpy==3.6.0->infinigen==1.2.4)
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/c2/e7/a82b05cf63a603df6e68d59ae6a68bf5064484a0718ea5033660af4b54a9/idna-3.6-py3-none-any.whl (61 kB)
Collecting urllib3<3,>=1.21.1 (from requests->bpy==3.6.0->infinigen==1.2.4)
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/a2/73/a68704750a7679d0b6d3ad7aa8d4da8e14e151ae82e6fee774e6e0d05ec8/urllib3-2.2.1-py3-none-any.whl (121 kB)
Collecting rich>=10.7.0 (from rich-click->landlab>=2.6.0->infinigen==1.2.4)
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/87/67/a37f6214d0e9fe57f6ae54b2956d550ca8365857f42a1ce0392bb21d9410/rich-13.7.1-py3-none-any.whl (240 kB)
Collecting patsy>=0.5.4 (from statsmodels->landlab>=2.6.0->infinigen==1.2.4)
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/43/f3/1d311a09c34f14f5973bb0bb0dc3a6e007e1eda90b5492d082689936ca51/patsy-0.5.6-py2.py3-none-any.whl (233 kB)
Collecting markdown-it-py>=2.2.0 (from rich>=10.7.0->rich-click->landlab>=2.6.0->infinigen==1.2.4)
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/42/d7/1ec15b46af6af88f19b8e5ffea08fa375d433c998b8a7639e76935c14f1f/markdown_it_py-3.0.0-py3-none-any.whl (87 kB)
Collecting pygments<3.0.0,>=2.13.0 (from rich>=10.7.0->rich-click->landlab>=2.6.0->infinigen==1.2.4)
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/97/9c/372fef8377a6e340b1704768d20daaded98bf13282b5327beb2e2fe2c7ef/pygments-2.17.2-py3-none-any.whl (1.2 MB)
Collecting mypy-extensions>=0.4.3 (from black->bmipy->landlab>=2.6.0->infinigen==1.2.4)
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/2a/e2/5d3f6ada4297caebe1a2add3b126fe800c96f56dbe5d1988a2cbe0b267aa/mypy_extensions-1.0.0-py3-none-any.whl (4.7 kB)
Collecting pathspec>=0.9.0 (from black->bmipy->landlab>=2.6.0->infinigen==1.2.4)
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/cc/20/ff623b09d963f88bfde16306a54e12ee5ea43e9b597108672ff3a408aad6/pathspec-0.12.1-py3-none-any.whl (31 kB)
Collecting platformdirs>=2 (from black->bmipy->landlab>=2.6.0->infinigen==1.2.4)
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/55/72/4898c44ee9ea6f43396fbc23d9bfaf3d06e01b83698bdf2e4c919deceb7c/platformdirs-4.2.0-py3-none-any.whl (17 kB)
Collecting tomli>=1.1.0 (from black->bmipy->landlab>=2.6.0->infinigen==1.2.4)
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/97/75/10a9ebee3fd790d20926a90a2547f0bf78f371b2f13aa822c759680ca7b9/tomli-2.0.1-py3-none-any.whl (12 kB)
Collecting MarkupSafe>=2.0 (from jinja2->bmipy->landlab>=2.6.0->infinigen==1.2.4)
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/7c/52/2b1b570f6b8b803cef5ac28fdf78c0da318916c7d2fe9402a84d591b394c/MarkupSafe-2.1.5-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (25 kB)
Collecting mdurl~=0.1 (from markdown-it-py>=2.2.0->rich>=10.7.0->rich-click->landlab>=2.6.0->infinigen==1.2.4)
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/b3/38/89ba8ad64ae25be8de66a6d463314cf1eb366222074cfda9ee839c56a4b4/mdurl-0.1.2-py3-none-any.whl (10.0 kB)
Building wheels for collected packages: infinigen
  Building editable for infinigen (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Building editable for infinigen (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [30 lines of output]
      rm -rf infinigen/terrain/*.egg-info
      rm -rf infinigen/terrain/__pycache__
      rm -rf infinigen/terrain/build
      bash scripts/install/compile_terrain.sh
      /usr/include/c++/11/bits/std_function.h:435:145: error: parameter packs not expanded with ‘...’:
        435 |         function(_Functor&& __f)
            |                                                                                                                                                 ^
      /usr/include/c++/11/bits/std_function.h:435:145: note:         ‘_ArgTypes’
      /usr/include/c++/11/bits/std_function.h:530:146: error: parameter packs not expanded with ‘...’:
        530 |         operator=(_Functor&& __f)
            |                                                                                                                                                  ^
      /usr/include/c++/11/bits/std_function.h:530:146: note:         ‘_ArgTypes’
      make: *** [Makefile:11：terrain] 错误 1
      Traceback (most recent call last):
        File "/home/cscg-east92007/anaconda3/envs/infinigen/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/home/cscg-east92007/anaconda3/envs/infinigen/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/home/cscg-east92007/anaconda3/envs/infinigen/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 273, in build_editable
          return hook(wheel_directory, config_settings, metadata_directory)
        File "/tmp/pip-build-env-42h71294/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 443, in build_editable
          return self._build_with_temp_dir(
        File "/tmp/pip-build-env-42h71294/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 395, in _build_with_temp_dir
          self.run_setup()
        File "/tmp/pip-build-env-42h71294/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 44, in <module>
        File "/home/cscg-east92007/anaconda3/envs/infinigen/lib/python3.10/subprocess.py", line 526, in run
          raise CalledProcessError(retcode, process.args,
      subprocess.CalledProcessError: Command '['make', 'terrain']' returned non-zero exit status 2.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building editable for infinigen
Failed to build infinigen
ERROR: Could not build wheels for infinigen, which is required to install pyproject.toml-based projects

### If this is your first time running Infinigen, what are the full install logs?**
Run `pip install -vv -e . > logs.txt 2>&1` and send logs.txt as an attachment.
[logs.txt](https://github.com/princeton-vl/infinigen/files/14550011/logs.txt)

### Platform
- OS & OS Version: ubuntu 20.04
- GPU (?) :NVIDIA TITAN RTX
- GPU Driver Version (?) :535.86.10
- RAM (GB):33Gi

**Comment by araistrick** [comment]
@mazeyu please take a look

**Comment by mazeyu** [comment]
seems gcc version is not high enough, can you try update to gcc11 and g++11

**Comment by FrankFeng-23** [comment]
> seems gcc version is not high enough, can you try update to gcc11 and g++11

Hi, I ran into the same problem. I tried updating gcc, g++ to 11, and then to 12. Neither of them works.... I'm using a Mac x86_64 (Intel). Any suggestions would be appreciated!

**Comment by mazeyu** [comment]
I tried on an Intel Mac too but got no errors, though I noticed your /usr/include is not on my Mac. So, unfortunately, I don't know what is going on either. Mac can be tricky to install and I recommend using a Linux machine. We would also appreciate helps from other people.

**Comment by xi-zc** [comment]
> seems gcc version is not high enough, can you try update to gcc11 and g++11
Thanks for advise, but it's already 11, what should I try next
g++ --version
g++ (Ubuntu 11.4.0-2ubuntu1~20.04) 11.4.0

**Comment by xi-zc** [comment]
> seems gcc version is not high enough, can you try update to gcc11 and g++11

Thanks for advise, but it's already 11, what should I try next
g++ --version
g++ (Ubuntu 11.4.0-2ubuntu1~20.04) 11.4.0

**Comment by mazeyu** [comment]
seems like the cuda compiler is too new, please try modifying this line to be 
```
alias nx="$nvcc_location -O3 -Xcompiler -fPIC -shared -std=c++11"
```
https://github.com/princeton-vl/infinigen/blob/5132903cd68704367d1c44c841e5163158e0f33d/scripts/install/compile_terrain.sh#L41

**Comment by davshus** [comment]
For me, the issue was that the g++ version was too new -- similar to https://github.com/NVlabs/instant-ngp/issues/119. I actually had to downgrade to g++ 10.

What fixed it for me was:
```
apt install gcc-10 g++-10
NVCC_PREPEND_FLAGS='-ccbin /usr/bin/g++-10' pip install -v -e ".[terrain,vis]"
```
FWIW my driver version is 560.35.03 and my nvcc version is 11.5.

**Comment by shenglih** [comment]
```apt install gcc-10 g++-10
NVCC_PREPEND_FLAGS='-ccbin /usr/bin/g++-10' pip install -v -e ".[terrain,vis]"```fixed mine too!

**Comment by yunho-c** [comment]
I encountered the same error (`scripts/install/compile_terrain.sh: line 138: install.sh: No such file or directory`)—it was due to uninitialized git submodules (specifically, OcMesher). If anyone encounter this error, see if `infinigen/infinigen/OcMesher` directory is empty. If so, run `git submodule init && git submodule update`. If you see contents, great. If not, try cloning `infinigen` from scratch again.
