### ISSUE TITLE
Error on Creating high quality videos

### ISSUE THREAD

**Issue by TomTomTommi** [princeton-vl/infinigen#224]
# Describe the bug
 
I successfully run the Hello World demo. But following the Example Commands to generate high quality videos,
```
python -m infinigen.datagen.manage_jobs --output_folder outputs/my_videos --num_scenes 500     --pipeline_config slurm monocular_video cuda_terrain opengl_gt     --cleanup big_files --warmup_sec 60000 --config video high_quality_terrain
```

but an error occur:
```
WARNING:root:SMB_AUTH envvar is not set, smb_client upload will not work. Ignore this message if not using upload
WARNING:infinigen.datagen.job_funcs:process_mesh_path=PosixPath('/home/jj323/PycharmProjects/infinigen/infinigen/datagen/customgt/build/customgt') does not exist, if opengl_gt is enabled it will fail
/home/jj323/anaconda3/envs/infinigen/lib/python3.10/site-packages/numpy/core/getlimits.py:549: UserWarning: The value of the smallest subnormal for <class 'numpy.float64'> type is zero.
  setattr(self, word, getattr(machar, word).flat[0])
/home/jj323/anaconda3/envs/infinigen/lib/python3.10/site-packages/numpy/core/getlimits.py:89: UserWarning: The value of the smallest subnormal for <class 'numpy.float64'> type is zero.
  return self._float_to_str(self.smallest_subnormal)
Using get_slurm_banned_nodes()=[]
outputs/my_videos 04/23 05:59PM -> 04/23 05:59PM
Traceback (most recent call last):
  File "/home/jj323/anaconda3/envs/infinigen/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/jj323/anaconda3/envs/infinigen/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/jj323/PycharmProjects/infinigen/infinigen/datagen/manage_jobs.py", line 812, in <module>
    main(args)
  File "/home/jj323/anaconda3/envs/infinigen/lib/python3.10/site-packages/gin/config.py", line 1605, in gin_wrapper
    utils.augment_exception_message_and_reraise(e, err_str)
  File "/home/jj323/anaconda3/envs/infinigen/lib/python3.10/site-packages/gin/utils.py", line 41, in augment_exception_message_and_reraise
    raise proxy.with_traceback(exception.__traceback__) from None
  File "/home/jj323/anaconda3/envs/infinigen/lib/python3.10/site-packages/gin/config.py", line 1582, in gin_wrapper
    return fn(*new_args, **new_kwargs)
  File "/home/jj323/PycharmProjects/infinigen/infinigen/datagen/manage_jobs.py", line 675, in main
    manage_datagen_jobs(all_scenes, elapsed=(now-start_time).total_seconds())
  File "/home/jj323/anaconda3/envs/infinigen/lib/python3.10/site-packages/gin/config.py", line 1605, in gin_wrapper
    utils.augment_exception_message_and_reraise(e, err_str)
  File "/home/jj323/anaconda3/envs/infinigen/lib/python3.10/site-packages/gin/utils.py", line 41, in augment_exception_message_and_reraise
    raise proxy.with_traceback(exception.__traceback__) from None
  File "/home/jj323/anaconda3/envs/infinigen/lib/python3.10/site-packages/gin/config.py", line 1582, in gin_wrapper
    return fn(*new_args, **new_kwargs)
  File "/home/jj323/PycharmProjects/infinigen/infinigen/datagen/manage_jobs.py", line 608, in manage_datagen_jobs
    control_state = compute_control_state(args, totals, elapsed, num_concurrent)
  File "/home/jj323/PycharmProjects/infinigen/infinigen/datagen/manage_jobs.py", line 567, in compute_control_state
    num_concurrent = int(os.environ[NUM_CONCURRENT_ENVVAR])
  File "/home/jj323/anaconda3/envs/infinigen/lib/python3.10/os.py", line 679, in __getitem__
    raise KeyError(key) from None
KeyError: 'INFINIGEN_NUMCONCURRENT_TARGET'
  In call to configurable 'manage_datagen_jobs' (<function manage_datagen_jobs at 0x7f2ff5133130>)
  In call to configurable 'main' (<function main at 0x7f2ff51330a0>)
```

All the commands in `ConfiguringInfinigen.md` have the same error.

### Platform
- OS & OS Version: Ubuntu 20.04
- GPU : RTX4090
- GPU Driver Version: Nvidia driver 535
- RAM (GB):32

**Comment by araistrick** [comment]
Hello - are you running on a slurm cluster? if so just set `export INFINIGEN_NUM_CONCURRENT_TARGET=100` or something similar to specify how many jobs you wish to run in paralell. I need to add better docs / eliminate this variable.

If you are not using a slurm cluster, please replace `slurm` with `local_128GB` or some other option, and read ConfiguringInfinigen.md for more on what this means.

**Comment by TomTomTommi** [comment]
Following your advice, I tried to replace `slurm` with `local_16GB`, and currently the output is as follows:
```
outputs/my_videos 04/24 10:18AM -> 04/24 03:59PM
============================================================
control_state/curr_concurrent_max : 1
control_state/disk_usage       : 0.26
control_state/n_in_flight      : 1
control_state/try_to_launch    : 0
control_state/will_launch      : 0
crashed/coarse                 : 69
crashed/fineterrain            : 8
crashed/total                  : 77
running/coarse                 : 1
running/total                  : 1
succeeded/coarse               : 8
succeeded/total                : 8
```
It is still running. I wonder if this is correct. Why is the crashes so high? Plus, according to other issues, the GPU consumption should be about 20GB. But I found my GPU usage is quite low.
```
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.171.04             Driver Version: 535.171.04   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA GeForce RTX 4090        Off | 00000000:01:00.0  On |                  Off |
|  0%   34C    P8              20W / 500W |    641MiB / 24564MiB |      4%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+

+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
|    0   N/A  N/A      1142      G   /usr/lib/xorg/Xorg                           59MiB |
|    0   N/A  N/A      1868      G   /usr/lib/xorg/Xorg                          192MiB |
|    0   N/A  N/A      1999      G   /usr/bin/gnome-shell                        164MiB |
|    0   N/A  N/A      3672      G   ...erProcess --variations-seed-version       81MiB |
|    0   N/A  N/A     11672      G   /opt/teamviewer/tv_bin/TeamViewer            23MiB |
|    0   N/A  N/A   1517432      G   ...seed-version=20240416-180159.777000       68MiB |
+---------------------------------------------------------------------------------------+

```
The CPU usage is full. 
```
    PID USER      PRI  NI  VIRT   RES   SHR S CPU% MEM%   TIME+  Command
1882020 jj323      39  19 4361M 1752M  209M R 100.  5.5 10:25.98 /home/jj323/anaconda3/envs/infinigen/bin/python -m infin
```
I am sure to involve `cuda_terrain ` in the command. What is the problem?
