### ISSUE TITLE
Known parameter setting in compile_opengl.sh

### ISSUE THREAD

**Issue by Monad-Cube** [princeton-vl/infinigen#226]
when make customgt, it will return "make: *** [Makefile:14: customgt] Error 174",

i think it is the unset parameters of -in and -out in "compile_opengl.sh", but I don't know what shoul i set
./build/customgt -in x -out x --frame 0

**Comment by Monad-Cube** [comment]
im working on a gpu machine, i run `bash scripts/install/compile_opengl.sh`, it finished with > [100%] Built target fast_obj_lib.

But when I run pip -t `INFINIGEN_INSTALL_CUSTOMGT=True pip install -e .`, i export the following log:

------------------------------------------The Logs--------------------------------------------
Building wheels for collected packages: infinigen
  Building editable for infinigen (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Building editable for infinigen (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [102 lines of output]
      rm -rf infinigen/terrain/*.egg-info
      rm -rf infinigen/terrain/__pycache__
      rm -rf infinigen/terrain/build
      bash scripts/install/compile_terrain.sh
      compiled lib/cuda/utils/FastNoiseLite.so
      compiled lib/cuda/elements/voronoi_rocks.so
      compiled lib/cuda/elements/upsidedown_mountains.so
      compiled lib/cuda/elements/ground.so
      compiled lib/cuda/elements/warped_rocks.so
      compiled lib/cuda/elements/mountains.so
      compiled lib/cuda/elements/landtiles.so
      compiled lib/cuda/elements/atmosphere.so
      compiled lib/cuda/elements/waterbody.so
      compiled lib/cuda/surfaces/chunkyrock.so
      compiled lib/cuda/surfaces/cobble_stone.so
      compiled lib/cuda/surfaces/cracked_ground.so
      compiled lib/cuda/surfaces/dirt.so
      compiled lib/cuda/surfaces/ice.so
      compiled lib/cuda/surfaces/mountain.so
      compiled lib/cuda/surfaces/mud.so
      compiled lib/cuda/surfaces/sand.so
      compiled lib/cuda/surfaces/sandstone.so
      compiled lib/cuda/surfaces/snow.so
      compiled lib/cuda/surfaces/soil.so
      compiled lib/cuda/surfaces/stone.so
      compiled lib/cpu/utils/FastNoiseLite.so
      compiled lib/cpu/elements/voronoi_rocks.so
      compiled lib/cpu/elements/upsidedown_mountains.so
      compiled lib/cpu/elements/ground.so
      compiled lib/cpu/elements/warped_rocks.so
      compiled lib/cpu/elements/mountains.so
      compiled lib/cpu/elements/landtiles.so
      compiled lib/cpu/elements/atmosphere.so
      compiled lib/cpu/elements/waterbody.so
      compiled lib/cpu/surfaces/chunkyrock.so
      compiled lib/cpu/surfaces/cobble_stone.so
      compiled lib/cpu/surfaces/cracked_ground.so
      compiled lib/cpu/surfaces/dirt.so
      compiled lib/cpu/surfaces/ice.so
      compiled lib/cpu/surfaces/mountain.so
      compiled lib/cpu/surfaces/mud.so
      compiled lib/cpu/surfaces/sand.so
      compiled lib/cpu/surfaces/sandstone.so
      compiled lib/cpu/surfaces/snow.so
      compiled lib/cpu/surfaces/soil.so
      compiled lib/cpu/surfaces/stone.so
      compiled lib/cpu/meshing/cube_spherical_mesher.so
      compiled lib/cpu/meshing/frontview_spherical_mesher.so
      compiled lib/cpu/meshing/uniform_mesher.so
      compiled lib/cpu/meshing/utils.so
      compiled lib/cpu/soil_machine/SoilMachine.so
      /workspace/xx/projects/infinigen
      /workspace/xx/projects/infinigen
      bash scripts/install/compile_opengl.sh
      -- Configuring done
      -- Generating done
      -- Build files have been written to: /workspace/xx/projects/infinigen/infinigen/datagen/customgt/build
      gmake[1]: Entering directory '/workspace/xx/projects/infinigen/infinigen/datagen/customgt/build'
      gmake[2]: Entering directory '/workspace/xx/projects/infinigen/infinigen/datagen/customgt/build'
      gmake[3]: Entering directory '/workspace/xx/projects/infinigen/infinigen/datagen/customgt/build'
      Consolidate compiler generated dependencies of target cnpy
      gmake[3]: Leaving directory '/workspace/xx/projects/infinigen/infinigen/datagen/customgt/build'
      [  9%] Built target cnpy
      gmake[3]: Entering directory '/workspace/xx/projects/infinigen/infinigen/datagen/customgt/build'
      Consolidate compiler generated dependencies of target customgt
      gmake[3]: Leaving directory '/workspace/xx/projects/infinigen/infinigen/datagen/customgt/build'
      [ 72%] Built target customgt
      gmake[3]: Entering directory '/workspace/xx/projects/infinigen/infinigen/datagen/customgt/build'
      Consolidate compiler generated dependencies of target cnpy-static
      gmake[3]: Leaving directory '/workspace/xx/projects/infinigen/infinigen/datagen/customgt/build'
      [ 81%] Built target cnpy-static
      gmake[3]: Entering directory '/workspace/xx/projects/infinigen/infinigen/datagen/customgt/build'
      Consolidate compiler generated dependencies of target example1
      gmake[3]: Leaving directory '/workspace/xx/projects/infinigen/infinigen/datagen/customgt/build'
      [ 90%] Built target example1
      gmake[3]: Entering directory '/workspace/xx/projects/infinigen/infinigen/datagen/customgt/build'
      Consolidate compiler generated dependencies of target fast_obj_lib
      gmake[3]: Leaving directory '/workspace/xx/projects/infinigen/infinigen/datagen/customgt/build'
      [100%] Built target fast_obj_lib
      gmake[2]: Leaving directory '/workspace/xx/projects/infinigen/infinigen/datagen/customgt/build'
      gmake[1]: Leaving directory '/workspace/xx/projects/infinigen/infinigen/datagen/customgt/build'
      make: *** [Makefile:14: customgt] Error 174
      Traceback (most recent call last):
        File "/media/anaconda3/envs/infinigen/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/media/anaconda3/envs/infinigen/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/media/anaconda3/envs/infinigen/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 273, in build_editable
          return hook(wheel_directory, config_settings, metadata_directory)
        File "/tmp/pip-build-env-i87z_4ut/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 443, in build_editable
          return self._build_with_temp_dir(
        File "/tmp/pip-build-env-i87z_4ut/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 395, in _build_with_temp_dir
          self.run_setup()
        File "/tmp/pip-build-env-i87z_4ut/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 46, in <module>
        File "/media/anaconda3/envs/infinigen/lib/python3.10/subprocess.py", line 526, in run
          raise CalledProcessError(retcode, process.args,
      subprocess.CalledProcessError: Command '['make', 'customgt']' returned non-zero exit status 2.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building editable for infinigen
Failed to build infinigen
ERROR: Could not build wheels for infinigen, which is required to install pyproject.toml-based projects
