### ISSUE TITLE
CalledProcessError: Failed building editable for infinigen (WSL2) 

### ISSUE THREAD

**Issue by SearAbbas** [princeton-vl/infinigen#254]
# Describe the bug
Hey all, I followed the instructions in Installation.md for installing Infinigen as a Blender Python script, but when running bash scripts/install/interactive_blender.sh I receive a CalledProcessError. I am running this via Windows WSL2 x86_64 and am using Ubuntu 20.04.3. 

### What version of the code were you using? 
Tell us the commit & commit hash from `git log`
infinigen-1.3.4

### What command did you run?
bash scripts/install/interactive_blender.sh

### Error section from output logs
infinigen/assets/creatures/util/geometry/cpp_utils/bnurbs.c:38:10: fatal error: Python.h: No such file or directory
         38 | #include "Python.h"
            |          ^~~~~~~~~~
      compilation terminated.
      Traceback (most recent call last):
        File "/tmp/pip-build-env-34l_7ee9/overlay/lib/python3.10/site-packages/setuptools/_distutils/unixccompiler.py", line 188, in _compile
          self.spawn(compiler_so + cc_args + [src, '-o', obj] + extra_postargs)
        File "/tmp/pip-build-env-34l_7ee9/overlay/lib/python3.10/site-packages/setuptools/_distutils/ccompiler.py", line 1041, in spawn
          spawn(cmd, dry_run=self.dry_run, **kwargs)
        File "/tmp/pip-build-env-34l_7ee9/overlay/lib/python3.10/site-packages/setuptools/_distutils/spawn.py", line 68, in spawn
          raise DistutilsExecError(f"command {cmd!r} failed with exit code {exitcode}")
      distutils.errors.DistutilsExecError: command '/usr/bin/gcc' failed with exit code 1
      
      During handling of the above exception, another exception occurred:
      
      Traceback (most recent call last):
        File "/tmp/pip-build-env-34l_7ee9/overlay/lib/python3.10/site-packages/setuptools/command/editable_wheel.py", line 155, in run
          self._create_wheel_file(bdist_wheel)
        File "/tmp/pip-build-env-34l_7ee9/overlay/lib/python3.10/site-packages/setuptools/command/editable_wheel.py", line 357, in _create_wheel_file
          files, mapping = self._run_build_commands(dist_name, unpacked, lib, tmp)
        File "/tmp/pip-build-env-34l_7ee9/overlay/lib/python3.10/site-packages/setuptools/command/editable_wheel.py", line 280, in _run_build_commands
          self._run_build_subcommands()
        File "/tmp/pip-build-env-34l_7ee9/overlay/lib/python3.10/site-packages/setuptools/command/editable_wheel.py", line 307, in _run_build_subcommands
          self.run_command(name)
        File "/tmp/pip-build-env-34l_7ee9/overlay/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 316, in run_command
          self.distribution.run_command(command)
        File "/tmp/pip-build-env-34l_7ee9/overlay/lib/python3.10/site-packages/setuptools/dist.py", line 968, in run_command
          super().run_command(command)
        File "/tmp/pip-build-env-34l_7ee9/overlay/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/tmp/pip-build-env-34l_7ee9/overlay/lib/python3.10/site-packages/setuptools/command/build_ext.py", line 91, in run
          _build_ext.run(self)
        File "/tmp/pip-build-env-34l_7ee9/overlay/lib/python3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 359, in run
          self.build_extensions()
        File "/tmp/pip-build-env-34l_7ee9/overlay/lib/python3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 479, in build_extensions
          self._build_extensions_serial()
        File "/tmp/pip-build-env-34l_7ee9/overlay/lib/python3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 505, in _build_extensions_serial
          self.build_extension(ext)
        File "/tmp/pip-build-env-34l_7ee9/overlay/lib/python3.10/site-packages/setuptools/command/build_ext.py", line 252, in build_extension
          _build_ext.build_extension(self, ext)
        File "/tmp/pip-build-env-34l_7ee9/overlay/lib/python3.10/site-packages/Cython/Distutils/build_ext.py", line 135, in build_extension
          super(build_ext, self).build_extension(ext)
        File "/tmp/pip-build-env-34l_7ee9/overlay/lib/python3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 560, in build_extension
          objects = self.compiler.compile(
        File "/tmp/pip-build-env-34l_7ee9/overlay/lib/python3.10/site-packages/setuptools/_distutils/ccompiler.py", line 600, in compile
          self._compile(obj, src, ext, cc_args, extra_postargs, pp_opts)
        File "/tmp/pip-build-env-34l_7ee9/overlay/lib/python3.10/site-packages/setuptools/_distutils/unixccompiler.py", line 190, in _compile
          raise CompileError(msg)
      distutils.errors.CompileError: command '/usr/bin/gcc' failed with exit code 1
      /tmp/pip-build-env-34l_7ee9/overlay/lib/python3.10/site-packages/setuptools/_distutils/dist.py:988: _DebuggingTips: Problem in editable installation.
      !!
      
              ********************************************************************************
              An error happened while installing `infinigen` in editable mode.
      
              The following steps are recommended to help debug this problem:
      
              - Try to install the project normally, without using the editable mode.
                Does the error still persist?
                (If it does, try fixing the problem before attempting the editable mode).
              - If you are using binary extensions, make sure you have all OS-level
                dependencies installed (e.g. compilers, toolchains, binary libraries, ...).
              - Try the latest version of setuptools (maybe the error was already fixed).
              - If you (or your project dependencies) are using any setuptools extension
                or customization, make sure they support the editable mode.
      
              After following the steps above, if the problem still persists and
              you think this is related to how setuptools handles editable installations,
              please submit a reproducible example
              (see https://stackoverflow.com/help/minimal-reproducible-example) to:
      
                  https://github.com/pypa/setuptools/issues
      
              See https://setuptools.pypa.io/en/latest/userguide/development_mode.html for details.
              ********************************************************************************
      
      !!
        cmd_obj.run()
      error: command '/usr/bin/gcc' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building editable for infinigen
Failed to build infinigen
ERROR: Could not build wheels for infinigen, which is required to install pyproject.toml-based projects

### What are your FULL output logs?
[logs.txt](https://github.com/user-attachments/files/15836215/logs.txt)

### If this is your first time running Infinigen, what are the full install logs?**
[logs2.txt](https://github.com/user-attachments/files/15836221/logs2.txt)

### Platform
- OS & OS Version: Windows 11
- GPU (?) : NVIDIA GeForce RTX 3080
- GPU Driver Version (?) :Driver Version: Version 551.23
- RAM (GB):32

# Additional context
The same problem is on the Ubuntu 24.04.

**Comment by hurjunhwa** [comment]
Hi @SearAbbas Can I ask how you resolve this problem?

**Comment by hurjunhwa** [comment]
Just leaving a comment for future reference;
In my case, Python.h was under a different directory (**$CONDA_PREFIX/include/python3.10**), so had to include it manually.


export C_INCLUDE_PATH=$CONDA_PREFIX/include:$CONDA_PREFIX/**include/python3.10**:$C_INCLUDE_PATH
export CPLUS_INCLUDE_PATH=$CONDA_PREFIX/include:$CONDA_PREFIX/**include/python3.10**:$CPLUS_INCLUDE_PATH

I am using anaconda installed python on Linux. The correct directory may differ from OS to Os. You can manually search it and add the paths to the C_INCLUDE_PATH and CPLUS_INCLUDE_PATH paths.

[Related post](https://github.com/ContinuumIO/anaconda-issues/issues/11430)
