### ISSUE TITLE
Where to find local_256.gin?

### ISSUE THREAD

**Issue by janismdhanbad** [princeton-vl/infinigen#265]
Hello authors, thanks for the amazing work! I was trying to generate an indoor dataset using the command mentioned here: https://github.com/princeton-vl/infinigen/blob/main/docs/HelloRoom.md#generating-scenes-automatically but I get the following error:

```
Traceback (most recent call last):
  File "/home/janpreet/miniconda3/envs/infinigen/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/janpreet/miniconda3/envs/infinigen/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/mnt/data/personal_experiments/synthetic_data_rendering/infinigen/infinigen/datagen/manage_jobs.py", line 870, in <module>
    infinigen.core.init.apply_gin_configs(
  File "/home/janpreet/.local/lib/python3.10/site-packages/gin/config.py", line 1605, in gin_wrapper
    utils.augment_exception_message_and_reraise(e, err_str)
  File "/home/janpreet/.local/lib/python3.10/site-packages/gin/utils.py", line 41, in augment_exception_message_and_reraise
    raise proxy.with_traceback(exception.__traceback__) from None
  File "/home/janpreet/.local/lib/python3.10/site-packages/gin/config.py", line 1582, in gin_wrapper
    return fn(*new_args, **new_kwargs)
  File "/mnt/data/personal_experiments/synthetic_data_rendering/infinigen/infinigen/core/init.py", line 178, in apply_gin_configs
    configs = [find_config(g) for g in ['base.gin'] + configs]
  File "/mnt/data/personal_experiments/synthetic_data_rendering/infinigen/infinigen/core/init.py", line 178, in <listcomp>
    configs = [find_config(g) for g in ['base.gin'] + configs]
  File "/mnt/data/personal_experiments/synthetic_data_rendering/infinigen/infinigen/core/init.py", line 176, in find_config
    raise FileNotFoundError(f'Could not find {p} or {p.stem} in any of {search_paths}')
FileNotFoundError: Could not find local_256.gin or local_256 in any of [PosixPath('/mnt/data/personal_experiments/synthetic_data_rendering/infinigen/infinigen/datagen/configs'), PosixPath('/mnt/data/personal_experiments/synthetic_data_rendering/infinigen'), PosixPath('.')]
  In call to configurable 'apply_gin_configs' (<function apply_gin_configs at 0x718d115a2830>)
```
I think the code is missing local_256.gin? 
Thanks!

## Steps to Reproduce
- run the following command:
`screen python -m infinigen.datagen.manage_jobs --output_folder outputs/my_dataset --num_scenes 1000 --pipeline_configs local_256.gin monocular.gin blender_gt.gin indoor_background_configs.gin --configs singleroom.gin --pipeline_overrides get_cmd.driver_script='infinigen_examples.generate_indoors' manage_datagen_jobs.num_concurrent=16 --overrides compose_indoors.restrict_single_supported_roomtype=True ` 

### What version of the code were you using? 
commit hash: fb7991e06580639202a4687937082cb63e931eb0

### What command did you run?
`screen python -m infinigen.datagen.manage_jobs --output_folder outputs/my_dataset --num_scenes 1000 --pipeline_configs local_256.gin monocular.gin blender_gt.gin indoor_background_configs.gin --configs singleroom.gin --pipeline_overrides get_cmd.driver_script='infinigen_examples.generate_indoors' manage_datagen_jobs.num_concurrent=16 --overrides compose_indoors.restrict_single_supported_roomtype=True
`

### What are your FULL output logs?
[logs.txt](https://github.com/user-attachments/files/15963342/logs.txt)

### If this is your first time running Infinigen, what are the full install logs?**
Run `pip install -vv -e . > logs.txt 2>&1` and send logs.txt as an attachment.

### Platform
- OS & OS Version: Ubuntu 22.04.4 LTS
- GPU (?) : Nvidia RTX 3090
- GPU Driver Version (?) : 535.171.04
- RAM (GB): 64 GB

# Additional context

**Comment by araistrick** [comment]
Apologies, this is a typo, it should be local_256GB.gin. I will patch it shortly.
