### ISSUE TITLE
Exporting Error for individual export

### ISSUE THREAD

**Issue by lastbasket** [princeton-vl/infinigen#271]
Traceback (most recent call last):
  File "/home/lastbasket/miniconda3/envs/infinigen/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/lastbasket/miniconda3/envs/infinigen/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/lastbasket/code/polar_dataset/infinigen/infinigen/tools/export.py", line 906, in <module>
    main(args)
  File "/home/lastbasket/code/polar_dataset/infinigen/infinigen/tools/export.py", line 874, in main
    subprocess.call(['zip', '-r', str(folder.with_suffix('.zip')), str(folder)]) 
AttributeError: 'NoneType' object has no attribute 'with_suffix'

It seems like the problem of the missing return of individual export of: 
https://github.com/princeton-vl/infinigen/blob/967970e6cbb3239af6ce87f2e1eb289c2616fb88/infinigen/tools/export.py#L827-L843

**Comment by araistrick** [comment]
Should be resolved by https://github.com/princeton-vl/infinigen/pull/280, please update to v1.5.1
