### ISSUE TITLE
Factory ModuleNotFound errors when generating individual ALL_ASSETS

### ISSUE THREAD

**Issue by haoliu-meta** [princeton-vl/infinigen#278]
# Describe the bug
Running individual asset generation with `ALL_ASSETS` results in `ModuleNotFoundError` for some factory classes.

## Steps to Reproduce
```
python -m infinigen_examples.generate_individual_assets --output_folder ~/infinigen_outputs/ -f SingleCabinetBaseFactory -n 1 --render image --export fbx
```

### What version of the code were you using? 
v1.4.0, `fb7991e06580639202a4687937082cb63e931eb0`

### What are your FULL output logs?
```
Traceback (most recent call last):                                                                                                                                                                             
  File "~/.conda/envs/infinigen/lib/python3.10/runpy.py", line 196, in _run_module_as_main                                                                                                          
    return _run_code(code, main_globals, None,                                                                                                                                                                 
  File "~/.conda/envs/infinigen/lib/python3.10/runpy.py", line 86, in _run_code                                                                                                                     
    exec(code, run_globals)                                                                                                                                                                                    
  File "~/infinigen/infinigen_examples/generate_individual_assets.py", line 514, in <module>                                                                                                        
    main(args)                                                                                                                                                                                                 
  File "~/infinigen/infinigen_examples/generate_individual_assets.py", line 416, in main                                                                                                            
    mapfunc(build_and_save_asset, targets, args)                                                                                                                                                               
  File "~/infinigen/infinigen_examples/generate_individual_assets.py", line 349, in mapfunc                                                                                                         
    return [f(i) for i in its]                                                                                                                                                                                 
  File "~/infinigen/infinigen_examples/generate_individual_assets.py", line 349, in <listcomp>                                                                                                      
    return [f(i) for i in its]                                                                                                                                                                                 
  File "~/infinigen/infinigen_examples/generate_individual_assets.py", line 196, in build_and_save_asset                                                                                            
    asset = build_scene_asset(args, factory_name, idx)                                                                                                                                                         
  File "~/infinigen/infinigen_examples/generate_individual_assets.py", line 65, in build_scene_asset                                                                                                
    raise ModuleNotFoundError(f'{factory_name} not Found.')                                                                                                                                                    
ModuleNotFoundError: SingleCabinetBaseFactory not Found.  
```

### Platform
- OS & OS Version:  Linux

# Additional context
Seems to be that certain `__init__.py` files are missing some factory classes. e.g. `SingleCabinetBaseFactory` is missing in `infinigen/assets/shelves/__init__.py`

**Comment by araistrick** [comment]
Should be resolved by #280, please update to v1.5.1
