### ISSUE TITLE
Numpy ModuleNotFound error

### ISSUE THREAD

**Issue by frankclong** [princeton-vl/infinigen#279]
# Describe the bug
ModuleNotFound error when running HelloRoom after installing dependencies. I attempted to downgrade numpy version but got a gxx package not found error.

### What version of the code were you using? 
`931d1e5be4d05d92ab120863b4179307165dd4f3` 

### What command did you run?
```python -m infinigen_examples.generate_indoors --seed 0 --task coarse --output_folder outputs/indoors/coarse -g overhead_singleroom.gin -p compose_indoors.terrain_enabled=False  compose_indoors.solve_max_rooms=1```

### What are your FULL output logs?
Traceback (most recent call last):
  File "/home/frank/miniconda3/envs/infinigen/lib/jvm/languages/python/lib/python3.10/site-packages/numpy/core/__init__.py", line 24, in <module>
    from . import multiarray
  File "/home/frank/miniconda3/envs/infinigen/lib/jvm/languages/python/lib/python3.10/site-packages/numpy/core/multiarray.py", line 10, in <module>
    from . import overrides
  File "/home/frank/miniconda3/envs/infinigen/lib/jvm/languages/python/lib/python3.10/site-packages/numpy/core/overrides.py", line 8, in <module>
    from numpy.core._multiarray_umath import (
ModuleNotFoundError: No module named 'numpy.core._multiarray_umath'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/frank/miniconda3/envs/infinigen/lib/jvm/languages/python/lib/python3.10/site-packages/numpy/__init__.py", line 130, in <module>
    from numpy.__config__ import show as show_config
  File "/home/frank/miniconda3/envs/infinigen/lib/jvm/languages/python/lib/python3.10/site-packages/numpy/__config__.py", line 4, in <module>
    from numpy.core._multiarray_umath import (
  File "/home/frank/miniconda3/envs/infinigen/lib/jvm/languages/python/lib/python3.10/site-packages/numpy/core/__init__.py", line 50, in <module>
    raise ImportError(msg)
ImportError:

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy C-extensions failed. This error can happen for
many reasons, often due to issues with your setup or how NumPy was
installed.

We have compiled some common reasons and troubleshooting tips at:

    https://numpy.org/devdocs/user/troubleshooting-importerror.html

Please note and check the following:

  * The Python version is: Python3.10 from "/home/frank/miniconda3/envs/infinigen/bin/python"
  * The NumPy version is: "1.26.4"

and make sure that they are the versions you expect.
Please carefully study the documentation linked above for further help.

Original error was: No module named 'numpy.core._multiarray_umath'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/frank/miniconda3/envs/infinigen/lib/jvm/languages/python/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/frank/miniconda3/envs/infinigen/lib/jvm/languages/python/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/frank/infinigen/infinigen_examples/generate_indoors.py", line 9, in <module>
    from numpy import deg2rad
  File "/home/frank/miniconda3/envs/infinigen/lib/jvm/languages/python/lib/python3.10/site-packages/numpy/__init__.py", line 135, in <module>
    raise ImportError(msg) from e
ImportError: Error importing numpy: you should not try to import numpy from
        its source directory; please exit the numpy source tree, and relaunch
        your python interpreter from there.

### Platform
- OS & OS Version: WSL for Windows (Ubuntu)
- GPU (?) :
- GPU Driver Version (?) :
- RAM (GB):

**Comment by araistrick** [comment]
Please provide your full installation logs, ie `pip install -e . -v > logs.txt 2>&1`
