### ISSUE TITLE
UShapedStaircaseFactory: AttributeError: module 'infinigen.assets.materials.fabrics' has no attribute 'apply'

### ISSUE THREAD

**Issue by haoliu-meta** [princeton-vl/infinigen#281]
# Describe the bug
When generating individual assets, `UShapedStaircaseFactory` fails with `AttributeError: module 'infinigen.assets.materials.fabrics' has no attribute 'apply'`

## Steps to Reproduce
```
python -m infinigen_examples.generate_individual_assets --output_folder ~/infinigen_outputs/ -f UShapedStaircaseFactory -n 1 --render image --export fbx
```

### What version of the code were you using? 
Tell us the commit & commit hash from `git log`
`c537e245f3e475e89f975a51279ed1d8bff622ac`

### What are your FULL output logs?
```
~/.conda/envs/infinigen/lib/python3.10/site-packages/numpy/core/getlimits.py:549: UserWarning: The value of the smallest subnormal for <class 'numpy.float64'> type is zero.
  setattr(self, word, getattr(machar, word).flat[0])
~/.conda/envs/infinigen/lib/python3.10/site-packages/numpy/core/getlimits.py:89: UserWarning: The value of the smallest subnormal for <class 'numpy.float64'> type is zero.
  return self._float_to_str(self.smallest_subnormal)
~/.conda/envs/infinigen/lib/python3.10/site-packages/numpy/core/getlimits.py:549: UserWarning: The value of the smallest subnormal for <class 'numpy.float32'> type is zero.
  setattr(self, word, getattr(machar, word).flat[0])
~/.conda/envs/infinigen/lib/python3.10/site-packages/numpy/core/getlimits.py:89: UserWarning: The value of the smallest subnormal for <class 'numpy.float32'> type is zero.
  return self._float_to_str(self.smallest_subnormal)
[17:05:19.558] [acceleratesupport] [INFO] | No OpenGL_accelerate module loaded: No module named 'OpenGL_accelerate'
[17:05:20.035] [init] [INFO] | Available devices have types=['CPU']
[17:05:20.035] [init] [WARNING] | Render will use CPU-only, only found types=['CPU']
[17:05:20.043] [generate_individual_assets] [INFO] | Building scene for UShapedStaircaseFactory 0
[17:05:20.136] [nurbs] [WARNING] | Failed to import compiled `bnurbs` package, either installation failed or we are running a minimal install
[17:05:20.181] [generate_individual_assets] [INFO] | Found UShapedStaircaseFactory in ~/infinigen/infinigen/assets/objects/elements
Traceback (most recent call last):
  File "~/.conda/envs/infinigen/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "~/.conda/envs/infinigen/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "~/infinigen/infinigen_examples/generate_individual_assets.py", line 711, in <module>
    main(args)
  File "~/infinigen/infinigen_examples/generate_individual_assets.py", line 517, in main
    mapfunc(build_and_save_asset, targets, args)
  File "~/infinigen/infinigen_examples/generate_individual_assets.py", line 437, in mapfunc
    return [f(i) for i in its]
  File "~/infinigen/infinigen_examples/generate_individual_assets.py", line 437, in <listcomp>
    return [f(i) for i in its]
  File "~/infinigen/infinigen_examples/generate_individual_assets.py", line 263, in build_and_save_asset
    asset = build_scene_asset(args, factory_name, idx)
  File "~/infinigen/infinigen_examples/generate_individual_assets.py", line 102, in build_scene_asset
    fac.finalize_assets(asset)
  File "~/infinigen/infinigen/assets/objects/elements/staircases/straight.py", line 627, in finalize_assets
    self.side_surface.apply(assets, selection="sides")
AttributeError: module 'infinigen.assets.materials.fabrics' has no attribute 'apply'
Error: Not freed memory blocks: 29666, total unfreed memory 18.783276 MB
```

### Platform
- OS & OS Version: Linux
- GPU (?) : N/A

**Comment by araistrick** [comment]
I believe this should be fixed on latest `main`.
