### ISSUE TITLE
TypeError: AntSwarmFactory.__init__() missing 1 required positional argument: 'bvh'

### ISSUE THREAD

**Issue by haoliu-meta** [princeton-vl/infinigen#282]
# Describe the bug
When generating individual assets of `AntSwarmFactory`, the script fails with `TypeError: AntSwarmFactory.__init__() missing 1 required positional argument: 'bvh'`

## Steps to Reproduce
```
python -m infinigen_examples.generate_individual_assets --output_folder ~/infinigen_outputs/ -f AntSwarmFactory -n 1 --render image --export fbx
```

### What version of the code were you using? 
Tell us the commit & commit hash from `git log`
v1.5.1: `c537e245f3e475e89f975a51279ed1d8bff622ac`

### What are your FULL output logs?
```
$ python -m infinigen_examples.generate_individual_assets --output_folder ~/infinigen_outputs/ -f AntSwarmFactory -n 1 --render image --export fbx
Failed to open dir (No such file or directory): /run/user/135395/gvfs/
~/.conda/envs/infinigen/lib/python3.10/site-packages/numpy/core/getlimits.py:549: UserWarning: The value of the smallest subnormal for <class 'numpy.float64'> type is zero.
  setattr(self, word, getattr(machar, word).flat[0])
~/.conda/envs/infinigen/lib/python3.10/site-packages/numpy/core/getlimits.py:89: UserWarning: The value of the smallest subnormal for <class 'numpy.float64'> type is zero.
  return self._float_to_str(self.smallest_subnormal)
~/.conda/envs/infinigen/lib/python3.10/site-packages/numpy/core/getlimits.py:549: UserWarning: The value of the smallest subnormal for <class 'numpy.float32'> type is zero.
  setattr(self, word, getattr(machar, word).flat[0])
~/.conda/envs/infinigen/lib/python3.10/site-packages/numpy/core/getlimits.py:89: UserWarning: The value of the smallest subnormal for <class 'numpy.float32'> type is zero.
  return self._float_to_str(self.smallest_subnormal)
[17:09:39.758] [acceleratesupport] [INFO] | No OpenGL_accelerate module loaded: No module named 'OpenGL_accelerate'
[17:09:40.451] [init] [INFO] | Available devices have types=['CPU']
[17:09:40.451] [init] [WARNING] | Render will use CPU-only, only found types=['CPU']
[17:09:40.483] [generate_individual_assets] [INFO] | Building scene for AntSwarmFactory 0
[17:09:40.639] [nurbs] [WARNING] | Failed to import compiled `bnurbs` package, either installation failed or we are running a minimal install
[17:09:40.698] [generate_individual_assets] [INFO] | Found AntSwarmFactory in ~/infinigen/infinigen/assets/objects/creatures
Traceback (most recent call last):
  File "~/.conda/envs/infinigen/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "~/.conda/envs/infinigen/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "~/infinigen/infinigen_examples/generate_individual_assets.py", line 711, in <module>
    main(args)
  File "~/infinigen/infinigen_examples/generate_individual_assets.py", line 517, in main
    mapfunc(build_and_save_asset, targets, args)
  File "~/infinigen/infinigen_examples/generate_individual_assets.py", line 437, in mapfunc
    return [f(i) for i in its]
  File "~/infinigen/infinigen_examples/generate_individual_assets.py", line 437, in <listcomp>
    return [f(i) for i in its]
  File "~/infinigen/infinigen_examples/generate_individual_assets.py", line 263, in build_and_save_asset
    asset = build_scene_asset(args, factory_name, idx)
  File "~/infinigen/infinigen_examples/generate_individual_assets.py", line 91, in build_scene_asset
    fac = fac(idx)
TypeError: AntSwarmFactory.__init__() missing 1 required positional argument: 'bvh'
Error: Not freed memory blocks: 26067, total unfreed memory 8.622105 MB
```

### Platform
- OS & OS Version: Linux
- GPU (?) : None

**Comment by araistrick** [comment]
Hello,

This asset isnt suitable for use with generate_individual_objects, it create an animated swarm and depends on knowing the bvh of the terrain to collide with.

Same goes for FishSchoolFactory and FlyingBirdFactory.

I presume you arrived on using this factory via the ALL_ASSETS option. This option is overzealous with which generators it tries to use. As part of v1.5.1 I have replaced it with `-f tests/assets/list_nature_meshs.txt` and `-f tests/assets/list_indoor_meshes.txt`which contains a more conservative list of which assets are safe to use.
