### ISSUE TITLE
A Question about "the algorithm does not support larger-than-90-degree fov yet"

### ISSUE THREAD

**Issue by zhaojinjian0000** [princeton-vl/infinigen#286]
Hello, thank you for taking the time to read my question. I am currently looking to create a 360-degree panoramic scene for a specific area (such as taking a 360-degree photo around a tree).

The first step in my code is to keep the camera location fixed while rotating the camera's yaw angle through 360 degrees to capture multiple images. Therefore, I have defined the function spawn_camera_rigs and attempted to rotate the camera through 360 degrees to obtain multiple images. However, I encountered an assert problem stating "the algorithm does not support larger-than-90-degree fov yet."

I found that this could be resolved by modifying the get_expanded_fov function in get_caminfo, which merges the fields of view from all cameras to obtain an extremely large FOV. My question is, what is the relationship between this FOV and the various Meshers, and why do they only support FOVs within 90 degrees? Currently, I am only using the FOV from camera 1, what issues might this cause?

I am looking forward to your response. Thank you very much!

### What version of the code were you using? 
```
commit c537e245f3e475e89f975a51279ed1d8bff622ac (HEAD -> main, origin/main, origin/HEAD)
Merge: 931d1e5b e692ce8a
Author: pvl-bot <bot@infinigen.org>
Date:   Fri Jul 12 18:44:56 2024 -0400
    Merge pull request from branch 'develop'
    v1.5.1
```

### What command did you run?
```
python -m infinigen.datagen.manage_jobs \
        --output_folder outputs/$out_name \
        --num_scenes 1 \
        --specific_seed 0 \
        --configs desert.gin  simple.gin  my_demo.gin \
        --pipeline_configs local_64GB.gin  blender_gt.gin  my_demo_pipeline.gin  \
        --pipeline_overrides LocalScheduleHandler.use_gpu=True
```

- my_demo_pipeline.gin
 ```
include 'infinigen/datagen/configs/data_schema/stereo.gin'
iterate_scene_tasks.cam_id_ranges =(1, 360)
```

- my_demo.gin
```
wirte my own spawn_camera_rigs func's args
it generate 360 cams,  location=[0, 0, 0], rotation_euler = (0, rot, 0), rot from 0 to 2 pi.


```
such as below
logger.info(f"[zjj change] camera {cam.location=}  {cam.rotation_euler=}")
(In fact, it is to cut 0 to 360 degrees into 120 cameras and repeat three times, but theoretically there will be no difference)
```
[15:09:13.542] [camera] [INFO] | [zjj change] camera cam.location=Vector((0.0, 0.0, 0.0))  cam.rotation_euler=Euler((0.0, 0.0, 0.0), 'XYZ')
[15:09:13.621] [camera] [INFO] | [zjj change] camera cam.location=Vector((0.0, 0.0, 0.0))  cam.rotation_euler=Euler((0.0, 0.05235987901687622, 0.0), 'XYZ')
... ...
[15:09:45.218] [camera] [INFO] | [zjj change] camera cam.location=Vector((0.0, 0.0, 0.0))  cam.rotation_euler=Euler((0.0, 6.230825424194336, 0.0), 'XYZ')

```

### What are your FULL output logs?
Provide the FULL output logs from your command as a txt file.
```
Traceback (most recent call last):
  File "/home/myname/miniconda3/envs/infinigen3/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/myname/miniconda3/envs/infinigen3/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/myname/mycodepath/infinigen/infinigen/infinigen_examples/generate_nature.py", line 1090, in <module>
    main(args)
  File "/home/myname/mycodepath/infinigen/infinigen/infinigen_examples/generate_nature.py", line 1029, in main
    execute_tasks.main(
  File "/home/myname/mycodepath/infinigen/infinigen/infinigen/core/execute_tasks.py", line 310, in main
    execute_tasks(
  File "/home/myname/miniconda3/envs/infinigen3/lib/python3.10/site-packages/gin/config.py", line 1605, in gin_wrapper
    utils.augment_exception_message_and_reraise(e, err_str)
  File "/home/myname/miniconda3/envs/infinigen3/lib/python3.10/site-packages/gin/utils.py", line 41, in augment_exception_message_and_reraise
    raise proxy.with_traceback(exception.__traceback__) from None
  File "/home/myname/miniconda3/envs/infinigen3/lib/python3.10/site-packages/gin/config.py", line 1582, in gin_wrapper
    return fn(*new_args, **new_kwargs)
  File "/home/myname/mycodepath/infinigen/infinigen/infinigen/core/execute_tasks.py", line 222, in execute_tasks
    terrain.fine_terrain(
  File "/home/myname/mycodepath/infinigen/infinigen/infinigen/terrain/core.py", line 440, in fine_terrain
    fine_meshes, _ = self.export(dynamic=True, cameras=cameras)
  File "/home/myname/miniconda3/envs/infinigen3/lib/python3.10/site-packages/gin/config.py", line 1605, in gin_wrapper
    utils.augment_exception_message_and_reraise(e, err_str)
  File "/home/myname/miniconda3/envs/infinigen3/lib/python3.10/site-packages/gin/utils.py", line 41, in augment_exception_message_and_reraise
    raise proxy.with_traceback(exception.__traceback__) from None
  File "/home/myname/miniconda3/envs/infinigen3/lib/python3.10/site-packages/gin/config.py", line 1582, in gin_wrapper
    return fn(*new_args, **new_kwargs)
  File "/home/myname/mycodepath/infinigen/infinigen/infinigen/terrain/core.py", line 207, in export
    mesher = OpaqueSphericalMesher(cameras, self.bounds)
  File "/home/myname/miniconda3/envs/infinigen3/lib/python3.10/site-packages/gin/config.py", line 1605, in gin_wrapper
    utils.augment_exception_message_and_reraise(e, err_str)
  File "/home/myname/miniconda3/envs/infinigen3/lib/python3.10/site-packages/gin/utils.py", line 41, in augment_exception_message_and_reraise
    raise proxy.with_traceback(exception.__traceback__) from None
  File "/home/myname/miniconda3/envs/infinigen3/lib/python3.10/site-packages/gin/config.py", line 1582, in gin_wrapper
    return fn(*new_args, **new_kwargs)
  File "/home/myname/mycodepath/infinigen/infinigen/infinigen/terrain/mesher/spherical_mesher.py", line 83, in __init__
    SphericalMesher.__init__(self, cameras, bounds)
  File "/home/myname/miniconda3/envs/infinigen3/lib/python3.10/site-packages/gin/config.py", line 1605, in gin_wrapper
    utils.augment_exception_message_and_reraise(e, err_str)
  File "/home/myname/miniconda3/envs/infinigen3/lib/python3.10/site-packages/gin/utils.py", line 41, in augment_exception_message_and_reraise
    raise proxy.with_traceback(exception.__traceback__) from None
  File "/home/myname/miniconda3/envs/infinigen3/lib/python3.10/site-packages/gin/config.py", line 1582, in gin_wrapper
    return fn(*new_args, **new_kwargs)
  File "/home/myname/mycodepath/infinigen/infinigen/infinigen/terrain/mesher/spherical_mesher.py", line 50, in __init__
    self.fov[0] < np.pi / 2 and self.fov[1] < np.pi / 2
AssertionError: the algorithm does not support larger-than-90-degree fov yet
  In call to configurable 'SphericalMesher' (<class 'infinigen.terrain.mesher.spherical_mesher.SphericalMesher'>)
  In call to configurable 'OpaqueSphericalMesher' (<class 'infinigen.terrain.mesher.spherical_mesher.OpaqueSphericalMesher'>)
  In call to configurable 'export' (<function Terrain.export at 0x7f28292788b0>)
  In call to configurable 'execute_tasks' (<function execute_tasks at 0x7f2828b61240>)
```

**Comment by jujumo** [comment]
I encounter the same problem, in a slightly different situation: I use config files to spawn multiple single cameras spread into the scene. It leads to the same.

I think the problem is scene generation: 

```
# WARNING: Large camera rig translations or rotations require special handling. 
#    if your cameras are not all approximately forward facing within a few centimeters, you must either:
#    -  configure the pipeline to generate assets / terrain for each camera separately, rather than sharing it between the whole rig
#    -  or, treat your camera rig as multiple camera rigs each with one camera, and implement code to positon them correctly
```
--  https://github.com/princeton-vl/infinigen/blob/4a4411e92611d059f2476f4384141de3529d1f9f/infinigen_examples/configs_nature/base.gin#L81

I wonder how to configure the pipeline to generate assets / terrain for each camera separately ?

Did you find any solution ?

**Comment by mazeyu** [comment]
We fixed it in the new release. Specifically, as we added in the doc, use `-p fine_terrain.mesher_backend="OcMesher"`.

**Comment by wmkai** [comment]
> We fixed it in the new release. Specifically, as we added in the doc, use `-p fine_terrain.mesher_backend="OcMesher"`.我们在新版本中修复了它。具体来说，正如我们在文档中添加的那样，使用 `-p fine_terrain.mesher_backend="OcMesher"` 。

Hi, @mazeyu Could you explain in detail what fine_terrain.mesher_backend="OcMesher" does?

**Comment by mazeyu** [comment]
It sets the mesh extraction algorithm to OcMesher, which is an octree based multi-resolution mesh extraction algorithm considering multiple camera views; whereas the other option SphericalMesher only extract mesh based on the spherical coordinate in one camera view

**Comment by wmkai** [comment]
> spawn_camera_rigs

```
# WARNING: Large camera rig translations or rotations require special handling. 
#    if your cameras are not all approximately forward facing within a few centimeters, you must either:
#    -  configure the pipeline to generate assets / terrain for each camera separately, rather than sharing it between the whole rig
#    -  or, treat your camera rig as multiple camera rigs each with one camera, and implement code to positon them correctly
```

Thanks for your explanation. With OcMesher, when I need to handle the situation of large camera rig translation or rotation:
1. I must modify the python code in `generate_nature.py` to use multiple camera rigs each with one camera like this:
```
loc_base = camera_rigs[0].location
rot_base = camera_rigs[0].rotation_euler
for i in range(len(camera_rigs)):
    camera_rigs[i].location = (loc_base[0], loc_base[1], loc_base[2])
    camera_rigs[i].rotation_euler = (rot_base[0], rot_base[1], rot_base[2] + i * math.pi / 2)
```

2. or I just need to modify the config file to set many sub cameras in a single camera rig like this:
```
camera.spawn_camera_rigs.n_camera_rigs = 1
camera.spawn_camera_rigs.camera_rig_config = [
    {'loc': (0, 0, 0), 'rot_euler': (0, 0, 0)},
    {'loc': (0, 0, 0), 'rot_euler': (0, math.pi / 2, 0)},
    {'loc': (0, 0, 0), 'rot_euler': (0, math.pi, 0)},
    {'loc': (0, 0, 0), 'rot_euler': (0, math.pi * 3/2, 0)}
]
```

**Comment by wmkai** [comment]
> > spawn_camera_rigs 产卵相机装备
> 
> Thanks for your explanation.谢谢你的解释。
> 
> Considering the instructions in base.gin:考虑 base.gin 中的说明：
> 
> ```
> # WARNING: Large camera rig translations or rotations require special handling. 
> #    if your cameras are not all approximately forward facing within a few centimeters, you must either:
> #    -  configure the pipeline to generate assets / terrain for each camera separately, rather than sharing it between the whole rig
> #    -  or, treat your camera rig as multiple camera rigs each with one camera, and implement code to positon them correctly
> ```
> 
> I have a question: 我有一个问题： I want to keep the camera location fixed while rotating the camera's yaw angle through 360 degrees to capture multiple images. With OcMesher, when I need to handle this situation of large camera rig translation or rotation:我想保持相机位置固定，同时将相机的偏航角旋转 360 度以捕获多个图像。使用 OcMesher，当我需要处理大型相机装置平移或旋转的情况时：
> 
> 1. I must modify the python code in `generate_nature.py` to use multiple camera `rigs camera.spawn_camera_rigs.n_camera_rigs = 4` each with one camera like this:我必须修改`generate_nature.py`中的python代码才能使用多个相机 `rigs camera.spawn_camera_rigs.n_camera_rigs = 4` 每个人都有一个像这样的相机：
> 
> ```
> loc_base = camera_rigs[0].location
> rot_base = camera_rigs[0].rotation_euler
> for i in range(len(camera_rigs)):
>     camera_rigs[i].location = (loc_base[0], loc_base[1], loc_base[2])
>     camera_rigs[i].rotation_euler = (rot_base[0], rot_base[1], rot_base[2] + i * math.pi / 2)
> ```
> 
> Meanwhile, I don't know whether just commenting the following code of `run_stage` of `pose_cameras` and `animate_cameras` and then adding the code above is the right way.同时，我不知道只注释`pose_cameras`和`animate_cameras`的`run_stage`的以下代码然后添加上面的代码是否是正确的方法。
> 
> ```
> p.run_stage(
>       "pose_cameras",
>       lambda: cam_util.configure_cameras(
>           camera_rigs, scene_preprocessed, init_bounding_box=bbox
>       ),
>       use_chance=False,
>   )
> ```
> 
> and 和
> 
> ```
> p.run_stage(
>     "animate_cameras",
>     animate_cameras,
>     use_chance=False,
> )
> ```
> 
> 2. or I just need to modify the config file to set many sub cameras in a single camera rig like this:或者我只需要修改配置文件即可在单个相机装备中设置许多子相机，如下所示：
> 
> ```
> camera.spawn_camera_rigs.n_camera_rigs = 1
> camera.spawn_camera_rigs.camera_rig_config = [
>     {'loc': (0, 0, 0), 'rot_euler': (0, 0, 0)},
>     {'loc': (0, 0, 0), 'rot_euler': (0, math.pi / 2, 0)},
>     {'loc': (0, 0, 0), 'rot_euler': (0, math.pi, 0)},
>     {'loc': (0, 0, 0), 'rot_euler': (0, math.pi * 3/2, 0)}
> ]
> ```
> 
> Thank you so much!  太感谢了！@mazeyu @araistrick

I have tried the method 1 and got 4 all-black rendered images. I changed the following code:
1. modify `cam_id_ranges` in `monocular.py` from `[1,1]` to `[4,1]`
`iterate_scene_tasks.cam_id_ranges = [4,1]`

2. add
```
loc_base = camera_rigs[0].location
rot_base = camera_rigs[0].rotation_euler
for i in range(len(camera_rigs)):
    camera_rigs[i].location = (loc_base[0], loc_base[1], loc_base[2])
    camera_rigs[i].rotation_euler = (rot_base[0], rot_base[1], rot_base[2] + i * math.pi / 2)
```
before
```
p.run_stage(
    "pose_cameras",
    lambda: cam_util.configure_cameras(
        camera_rigs, scene_preprocessed, init_bounding_box=bbox
    ),
    use_chance=False,
)
```
and then comment
```
p.run_stage(
    "pose_cameras",
    lambda: cam_util.configure_cameras(
        camera_rigs, scene_preprocessed, init_bounding_box=bbox
    ),
    use_chance=False,
)
```
and
```
p.run_stage(
    "animate_cameras",
    animate_cameras,
    use_chance=False,
)
```

3. modify `base.gin`:
set `camera.spawn_camera_rigs.n_camera_rigs = 4` and
set 
camera.spawn_camera_rigs.camera_rig_config = [
    {'loc': (0, 0, 0), 'rot_euler': (0, 0, 0)},
]

I read many related issues but didn't find a suitable solution. I believe many people will have the requirement to keep the camera location fixed while rotating the camera's yaw angle through 360 degrees to capture multiple images or a single video.
