### ISSUE TITLE
error when run command  $BLENDER --noaudio --background --python generate.py ...

### ISSUE THREAD

**Issue by jh369973** [princeton-vl/infinigen#29]
**Describe the bug**
when I run the command `$BLENDER -noaudio --background --python generate.py -- --seed 0 --task coarse -g desert simple --output_folder outputs/helloworld/coarse` python raise an error

- What are your output logs? 
```
Blender 3.3.1 (hash b292cfe5a936 built 2022-10-05 00:14:35)
Read prefs: /home/kim/.config/blender/3.3/config/userpref.blend
Error: Python: Traceback (most recent call last):
  File "/home/kim/infinigen/worldgen/generate.py", line 22, in <module>
    from tqdm import tqdm
ModuleNotFoundError: No module named 'tqdm'

Blender quit
Blender 3.3.1 (hash b292cfe5a936 built 2022-10-05 00:14:35)
Read prefs: /home/kim/.config/blender/3.3/config/userpref.blend
Error: Python: Traceback (most recent call last):
  File "/home/kim/infinigen/worldgen/generate.py", line 22, in <module>
    from tqdm import tqdm
ModuleNotFoundError: No module named 'tqdm'

Blender quit
Blender 3.3.1 (hash b292cfe5a936 built 2022-10-05 00:14:35)
Read prefs: /home/kim/.config/blender/3.3/config/userpref.blend
Error: Python: Traceback (most recent call last):
  File "/home/kim/infinigen/worldgen/generate.py", line 22, in <module>
    from tqdm import tqdm
ModuleNotFoundError: No module named 'tqdm'

Blender quit
Blender 3.3.1 (hash b292cfe5a936 built 2022-10-05 00:14:35)
Read prefs: /home/kim/.config/blender/3.3/config/userpref.blend
Error: Python: Traceback (most recent call last):
  File "/home/kim/infinigen/worldgen/generate.py", line 22, in <module>
    from tqdm import tqdm
ModuleNotFoundError: No module named 'tqdm'

Blender quit
```

I find that the python version of conda is 3.10.11, while blender use python3.10.2 to run the file. I don't know if it is the reason, I followed every step in the readme strictly.

**Platform**
- OS & OS Version: Ubuntu 22.04.2 LTS

**Comment by tms-gvd** [comment]
Did you try to install tqdm ?

**Comment by cswiger** [comment]
I am having same issue - here is my full install.sh log    
https://gist.github.com/cswiger/68ff98d9c339bdda246fa65737cb853e

checked after first build and found 
source/cpu/soil_machine/layermap.h:37:10: fatal error: glm/glm.hpp: No such file or directory

so did
$ sudo apt install libglm-dev

but still getting 
  File "/home/chuck/src/infinigen/worldgen/generate.py", line 22, in <module>
    from tqdm import tqdm
ModuleNotFoundError: No module named 'tqdm'

**Comment by araistrick** [comment]
'skipping cuda' just means you will not be able to use the `cuda_terrain` config, rendering on the GPU will still work once the CPU work of generating the scene is complete. 

RE tqdm, check in the logs if _either_ of the _two_ pip install commands is failing, we pip install the packages into both conda's python and blender's python to it can be a little confusing

**Comment by andzejsp** [comment]
im having same thing after running 
```
$BLENDER -noaudio --background --python generate.py -- --seed 0 --task coarse -g desert simple --output_folder outputs/helloworld/coarse
```


```
(infinigen) sd2@sd2:/mnt/5a88e793-90e0-4a46-a01b-cd29f52170cb/infinigen$ cd worldgen/
(infinigen) sd2@sd2:/mnt/5a88e793-90e0-4a46-a01b-cd29f52170cb/infinigen/worldgen$ $BLENDER -noaudio --background --python generate.py -- --seed 0 --task coarse -g desert simple --output_folder outputs/helloworld/coarse
Blender 3.3.1 (hash b292cfe5a936 built 2022-10-05 00:14:35)
Error: Python: Traceback (most recent call last):
  File "/mnt/5a88e793-90e0-4a46-a01b-cd29f52170cb/infinigen/worldgen/generate.py", line 22, in <module>
    from tqdm import tqdm
ModuleNotFoundError: No module named 'tqdm'

Blender quit
(infinigen) sd2@sd2:/mnt/5a88e793-90e0-4a46-a01b-cd29f52170cb/infinigen/worldgen$ pip install tqdm
Requirement already satisfied: tqdm in /home/sd2/.local/lib/python3.10/site-packages (4.65.0)
(infinigen) sd2@sd2:/mnt/5a88e793-90e0-4a46-a01b-cd29f52170cb/infinigen/worldgen$ pip3 install tqdm
Requirement already satisfied: tqdm in /home/sd2/.local/lib/python3.10/site-packages (4.65.0)
(infinigen) sd2@sd2:/mnt/5a88e793-90e0-4a46-a01b-cd29f52170cb/infinigen/worldgen$ 
```

Any help would be appreciated
