### ISSUE TITLE
FileNotFoundError: Could not find singleroom.gin or singleroom in any of ['infinigen_examples/configs_nature']" 

### ISSUE THREAD

**Issue by Boltzmachine** [princeton-vl/infinigen#303]
# Describe the bug
FileNotFoundError:  Could not find singleroom.gin or singleroom in any of ['infinigen_examples/configs_nature']" node=None fatal=True 

## Steps to Reproduce
Run the command in HelloRoom.md
python -m infinigen.datagen.manage_jobs --output_folder outputs/my_dataset --num_scenes 1 --pipeline_configs local_256GB.gin monocular.gin blender_gt.gin indoor_background_configs.gin --configs singleroom.gin --pipeline_overrides get_cmd.driver_script='infinigen_examples.generate_indoors' manage_datagen_jobs.num_concurrent=16 --overrides compose_indoors.restrict_single_supported_roomtype=True 

### What version of the code were you using? 
Tell us the commit & commit hash from `git log`

### What are your FULL output logs?
Provide the FULL output logs from your command as a txt file.
```
Device with name Apple M2 Max supports metal minimum requirements
WARNING:root:SMB_AUTH envvar is not set, smb_client upload will not work. Ignore this message if not using upload
WARNING:infinigen.datagen.job_funcs:process_mesh_path=PosixPath('/Users/qiuweikang/dev/infinigen/infinigen/datagen/customgt/build/customgt') does not exist, if opengl_gt is enabled it will fail
Traceback (most recent call last):
  File "/opt/homebrew/Caskroom/miniconda/base/envs/infinigen/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/homebrew/Caskroom/miniconda/base/envs/infinigen/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/Users/qiuweikang/dev/infinigen/infinigen/datagen/manage_jobs.py", line 870, in <module>
    raise FileExistsError(
FileExistsError: --output_folder outputs/my_dataset already exists! Please delete it, specify a different --output_folder, or use --overwrite
  infinigen git:(main)✗ ✗ rm -rf outputs/my_dataset/                                                       (infinigen)
  infinigen git:(main)✗  python -m infinigen.datagen.manage_jobs --output_folder outputs/my_dataset --num_scenes 1 --pipeline_configs local_256GB.gin monocular.gin blender_gt.gin indoor_background_configs.gin --configs singleroom.gin --pipeline_overrides get_cmd.driver_script='infinigen_examples.generate_indoors' manage_datagen_jobs.num_concurrent=16 --overrides compose_indoors.restrict_single_supported_roomtype=True --pipeline_overrides LocalScheduleHandler.use_gpu=False
Device with name Apple M2 Max supports metal minimum requirements
WARNING:root:SMB_AUTH envvar is not set, smb_client upload will not work. Ignore this message if not using upload
WARNING:infinigen.datagen.job_funcs:process_mesh_path=PosixPath('/Users/qiuweikang/dev/infinigen/infinigen/datagen/customgt/build/customgt') does not exist, if opengl_gt is enabled it will fail
Using get_slurm_banned_nodes()=[]
outputs/my_dataset 08/22 02:18PM -> 08/22 02:18PM
============================================================
control_state/curr_concurrent_max : 16
control_state/disk_usage       : 0.01
control_state/n_in_flight      : 0
control_state/try_to_launch    : 16
control_state/will_launch      : 1
------------------------------------------------------------
outputs/my_dataset 08/22 02:18PM -> 08/22 02:18PM
============================================================
control_state/curr_concurrent_max : 16
control_state/disk_usage       : 0.01
control_state/n_in_flight      : 1
control_state/try_to_launch    : 15
control_state/will_launch      : 0
running/coarse                 : 1
running/total                  : 1
------------------------------------------------------------
WARNING:root:SMB_AUTH envvar is not set, smb_client upload will not work. Ignore this message if not using upload
WARNING:infinigen.datagen.job_funcs:process_mesh_path=PosixPath('/Users/qiuweikang/dev/infinigen/infinigen/datagen/customgt/build/customgt') does not exist, if opengl_gt is enabled it will fail
outputs/my_dataset 08/22 02:18PM -> 08/22 02:18PM
============================================================
control_state/curr_concurrent_max : 16
control_state/disk_usage       : 0.01
control_state/n_in_flight      : 1
control_state/try_to_launch    : 15
control_state/will_launch      : 0
running/coarse                 : 1
running/total                  : 1
------------------------------------------------------------
outputs/my_dataset 08/22 02:18PM -> 08/22 02:18PM
Crashed: 08/22 02:18PM outputs/my_dataset/6b612b91/logs/coarse.err reason="FileNotFoundError:  Could not find singleroom.gin or singleroom in any of ['infinigen_examples/configs_nature']" node=None fatal=True

============================================================
control_state/curr_concurrent_max : 16
control_state/disk_usage       : 0.01
control_state/n_in_flight      : 0
control_state/try_to_launch    : 16
control_state/will_launch      : 0
crashed/coarse                 : 1
crashed/total                  : 1
------------------------------------------------------------
```

**Comment by araistrick** [comment]
I wasnt able to reproduce this, could you try again on latest `main` and show us the command again?

**Comment by lorjul** [comment]
I have the same error ("Could not find singleroom.gin) when using the latest commit (d55e29724c890dde57e29b664bc01e0d1ecab383). I've noticed that this is somehow related to the `--pipeline_overrides LocalScheduleHandler.use_gpu=False` argument. If I add this override, I get the same error as OP. Without it, it runs fine.

This is the command I used:

    python -m infinigen.datagen.manage_jobs  --output_folder outputs/justone --num_scenes 1 --pipeline_configs local_16GB.gin monocular.gin blender_gt.gin indoor_background_configs.gin --configs singleroom.gin --pipeline_overrides get_cmd.driver_script=infinigen_examples.generate_indoors manage_datagen_jobs.num_concurrent=16 --overrides compose_indoors.restrict_single_supported_roomtype=True --pipeline_overrides LocalScheduleHandler.use_gpu=False --overwrite

And this is the error message:

```
Failed to open dir (No such file or directory): /run/user/1000/gvfs/
/home/lorenjul/miniconda3/envs/infinigen/lib/python3.10/site-packages/numpy/core/getlimits.py:549: UserWarning: The value of the smallest subnormal for <class 'numpy.float64'> type is zero.
  setattr(self, word, getattr(machar, word).flat[0])
/home/lorenjul/miniconda3/envs/infinigen/lib/python3.10/site-packages/numpy/core/getlimits.py:89: UserWarning: The value of the smallest subnormal for <class 'numpy.float64'> type is zero.
  return self._float_to_str(self.smallest_subnormal)
/home/lorenjul/miniconda3/envs/infinigen/lib/python3.10/site-packages/numpy/core/getlimits.py:549: UserWarning: The value of the smallest subnormal for <class 'numpy.float32'> type is zero.
  setattr(self, word, getattr(machar, word).flat[0])
/home/lorenjul/miniconda3/envs/infinigen/lib/python3.10/site-packages/numpy/core/getlimits.py:89: UserWarning: The value of the smallest subnormal for <class 'numpy.float32'> type is zero.
  return self._float_to_str(self.smallest_subnormal)
WARNING:root:SMB_AUTH envvar is not set, smb_client upload will not work. Ignore this message if not using upload
Using get_slurm_banned_nodes()=[]
outputs/justone 09/23 02:50PM -> 09/23 02:50PM
============================================================
control_state/curr_concurrent_max : 1
control_state/disk_usage       : 0.75
control_state/n_in_flight      : 0
control_state/try_to_launch    : 1
control_state/will_launch      : 1
------------------------------------------------------------
outputs/justone 09/23 02:50PM -> 09/23 02:50PM
============================================================
control_state/curr_concurrent_max : 1
control_state/disk_usage       : 0.75
control_state/n_in_flight      : 1
control_state/try_to_launch    : 0
control_state/will_launch      : 0
running/coarse                 : 1
running/total                  : 1
------------------------------------------------------------
outputs/justone 09/23 02:50PM -> 09/23 02:50PM
============================================================
control_state/curr_concurrent_max : 1
control_state/disk_usage       : 0.75
control_state/n_in_flight      : 1
control_state/try_to_launch    : 0
control_state/will_launch      : 0
running/coarse                 : 1
running/total                  : 1
------------------------------------------------------------
outputs/justone 09/23 02:50PM -> 09/23 02:50PM
Slurm accounting storage is disabled
WARNING:__main__:sacct threw Command '['/usr/bin/sacct', '-j', '97825222274', '--format', 'Node', '--noheader']' returned non-zero exit status 1.
Crashed: 09/23 02:50PM outputs/justone/4e5986fe/logs/coarse.err reason="FileNotFoundError:  Could not find singleroom.gin or singleroom in any of ['infinigen_examples/configs_nature']" node=None fatal=True

============================================================
control_state/curr_concurrent_max : 1
control_state/disk_usage       : 0.75
control_state/n_in_flight      : 0
control_state/try_to_launch    : 1
control_state/will_launch      : 0
crashed/coarse                 : 1
crashed/total                  : 1
------------------------------------------------------------
```

Hope this helps.
