### ISSUE TITLE
[BUG] KeyError:'bpy_prop_collection[key]: key "subdivision" not found

### ISSUE THREAD

**Issue by JiangZfeng** [princeton-vl/infinigen#32]
when running command:
`BLENDER -noaudio --background --python generate.py -- --seed 0 --task coarse -g desert simple --output_folder outputs/helloworld/coarse`

error occurs:

`
[20:30:28.830] [root] [INFO] | CUDA_VISIBLE_DEVICES=None

[20:30:28.830] [times] [INFO] | [MAIN TOTAL] 
[20:30:28.831] [root] [INFO] | Processing frames 1 through 1 inclusive 
[20:30:28.836] [times] [INFO] | [Create terrain] 
[20:30:28.836] [root] [INFO] | Terrain using only on the fly  on_the_fly_asset_folder=PosixPath('/home/lab632/data_win/632_workspace/jzf/infinigen-main/worldgen/outputs/helloworld/coarse/assets') 
[20:30:30.187] [times] [INFO] | [Create terrain] failed with <class 'KeyError'> 
[20:30:30.187] [times] [INFO] | [MAIN TOTAL] failed with <class 'KeyError'> 
错误: Python: Traceback (most recent call last):
  File "/home/lab632/data_win/632_workspace/jzf/infinigen-main/worldgen/generate.py", line 409, in <module>
    main()
  File "/home/lab632/data_win/632_workspace/jzf/infinigen-main/worldgen/generate.py", line 399, in main
    infinigen.main(
  File "/home/lab632/data_win/632_workspace/jzf/infinigen-main/worldgen/core.py", line 425, in main
    execute_tasks(
  File "/home/lab632/data_win/632_workspace/jzf/infinigen-main/blender/3.3/python/lib/python3.10/site-packages/gin/config.py", line 1605, in gin_wrapper
    utils.augment_exception_message_and_reraise(e, err_str)
  File "/home/lab632/data_win/632_workspace/jzf/infinigen-main/blender/3.3/python/lib/python3.10/site-packages/gin/utils.py", line 41, in augment_exception_message_and_reraise
    raise proxy.with_traceback(exception.__traceback__) from None
  File "/home/lab632/data_win/632_workspace/jzf/infinigen-main/blender/3.3/python/lib/python3.10/site-packages/gin/config.py", line 1582, in gin_wrapper
    return fn(*new_args, **new_kwargs)
  File "/home/lab632/data_win/632_workspace/jzf/infinigen-main/worldgen/core.py", line 275, in execute_tasks
    terrain = Terrain(scene_seed, surface.registry, task=task, on_the_fly_asset_folder=output_folder/"assets")
  File "/home/lab632/data_win/632_workspace/jzf/infinigen-main/blender/3.3/python/lib/python3.10/site-packages/gin/config.py", line 1605, in gin_wrapper
    utils.augment_exception_message_and_reraise(e, err_str)
  File "/home/lab632/data_win/632_workspace/jzf/infinigen-main/blender/3.3/python/lib/python3.10/site-packages/gin/utils.py", line 41, in augment_exception_message_and_reraise
    raise proxy.with_traceback(exception.__traceback__) from None
  File "/home/lab632/data_win/632_workspace/jzf/infinigen-main/blender/3.3/python/lib/python3.10/site-packages/gin/config.py", line 1582, in gin_wrapper
    return fn(*new_args, **new_kwargs)
  File "/home/lab632/data_win/632_workspace/jzf/infinigen-main/worldgen/terrain/core.py", line 82, in __init__
    self.elements, scene_infos = scene(seed, Path(on_the_fly_asset_folder), asset_path, device)
  File "/home/lab632/data_win/632_workspace/jzf/infinigen-main/blender/3.3/python/lib/python3.10/site-packages/gin/config.py", line 1605, in gin_wrapper
    utils.augment_exception_message_and_reraise(e, err_str)
  File "/home/lab632/data_win/632_workspace/jzf/infinigen-main/blender/3.3/python/lib/python3.10/site-packages/gin/utils.py", line 41, in augment_exception_message_and_reraise
    raise proxy.with_traceback(exception.__traceback__) from None
  File "/home/lab632/data_win/632_workspace/jzf/infinigen-main/blender/3.3/python/lib/python3.10/site-packages/gin/config.py", line 1582, in gin_wrapper
    return fn(*new_args, **new_kwargs)
  File "/home/lab632/data_win/632_workspace/jzf/infinigen-main/worldgen/terrain/scene.py", line 43, in scene
    caves = Caves(on_the_fly_asset_folder / Assets.Caves, reused_asset_folder / Assets.Caves)
  File "/home/lab632/data_win/632_workspace/jzf/infinigen-main/blender/3.3/python/lib/python3.10/site-packages/gin/config.py", line 1605, in gin_wrapper
    utils.augment_exception_message_and_reraise(e, err_str)
  File "/home/lab632/data_win/632_workspace/jzf/infinigen-main/blender/3.3/python/lib/python3.10/site-packages/gin/utils.py", line 41, in augment_exception_message_and_reraise
    raise proxy.with_traceback(exception.__traceback__) from None
  File "/home/lab632/data_win/632_workspace/jzf/infinigen-main/blender/3.3/python/lib/python3.10/site-packages/gin/config.py", line 1582, in gin_wrapper
    return fn(*new_args, **new_kwargs)
  File "/home/lab632/data_win/632_workspace/jzf/infinigen-main/worldgen/terrain/elements/caves.py", line 44, in __init__
    n_instances, N, float_data = self.load_assets()
  File "/home/lab632/data_win/632_workspace/jzf/infinigen-main/blender/3.3/python/lib/python3.10/site-packages/gin/config.py", line 1605, in gin_wrapper
    utils.augment_exception_message_and_reraise(e, err_str)
  File "/home/lab632/data_win/632_workspace/jzf/infinigen-main/blender/3.3/python/lib/python3.10/site-packages/gin/utils.py", line 41, in augment_exception_message_and_reraise
    raise proxy.with_traceback(exception.__traceback__) from None
  File "/home/lab632/data_win/632_workspace/jzf/infinigen-main/blender/3.3/python/lib/python3.10/site-packages/gin/config.py", line 1582, in gin_wrapper
    return fn(*new_args, **new_kwargs)
  File "/home/lab632/data_win/632_workspace/jzf/infinigen-main/worldgen/terrain/elements/caves.py", line 66, in load_assets
    caves_asset(self.on_the_fly_asset_folder / f"{i}")
  File "/home/lab632/data_win/632_workspace/jzf/infinigen-main/blender/3.3/python/lib/python3.10/site-packages/gin/config.py", line 1605, in gin_wrapper
    utils.augment_exception_message_and_reraise(e, err_str)
  File "/home/lab632/data_win/632_workspace/jzf/infinigen-main/blender/3.3/python/lib/python3.10/site-packages/gin/utils.py", line 41, in augment_exception_message_and_reraise
    raise proxy.with_traceback(exception.__traceback__) from None
  File "/home/lab632/data_win/632_workspace/jzf/infinigen-main/blender/3.3/python/lib/python3.10/site-packages/gin/config.py", line 1582, in gin_wrapper
    return fn(*new_args, **new_kwargs)
  File "/home/lab632/data_win/632_workspace/jzf/infinigen-main/worldgen/terrain/assets/caves/core.py", line 188, in caves_asset
    add_cave(rescale=1, cave_z=0)
  File "/home/lab632/data_win/632_workspace/jzf/infinigen-main/worldgen/terrain/assets/caves/core.py", line 170, in add_cave
    cave.add_subdivision("firstsub", 2)
  File "/home/lab632/data_win/632_workspace/jzf/infinigen-main/worldgen/terrain/assets/caves/core.py", line 108, in add_subdivision
    bpy.context.object.modifiers["Subdivision"].name = name
KeyError: 'bpy_prop_collection[key]: key "Subdivision" not found'
  In call to configurable 'caves_asset' (<function caves_asset at 0x7f0287dfc430>)
  In call to configurable 'load_assets' (<function Caves.load_assets at 0x7f0287dfc9d0>)
  In call to configurable 'Caves' (<class 'terrain.elements.caves.Caves'>)
  In call to configurable 'scene' (<function scene at 0x7f029051ecb0>)
  In call to configurable 'Terrain' (<class 'terrain.core.Terrain'>)
  In call to configurable 'execute_tasks' (<function execute_tasks at 0x7f0283132c20>)
`
actually the command succeed at the first time, the scene is generated and can open in blender. But this command does not run successfully the second time and the above error occurs.

**Comment by JiangZfeng** [comment]
The problem was fixed after I changed the language from Chinese to English, probably a blender bug

**Comment by GreatWildFire** [comment]
> The problem was fixed after I changed the language from Chinese to English, probably a blender bug

hey buddy,i have the same error, can you tell me how to  changed the language from Chinese to English? Thanks.
