### ISSUE TITLE
Unable to generate helloworld scene by installing Infinigen as a Blender Python script

### ISSUE THREAD

**Issue by ngchikit** [princeton-vl/infinigen#343]
## Steps to Reproduce
If this relates to running the codebase, please provide steps to reproduce:

>> When I running this command: 
# Generate a scene layout
python -m infinigen.launch_blender -m infinigen_examples.generate_nature -- --seed 0 --task coarse -g desert.gin simple.gin --output_folder outputs/hello_world/coarse

### What version of the code were you using? 
Tell us the commit & commit hash from `git log`

commit 85db7b5e2c3815097847009e8a622fd7b2e89d9e (HEAD -> main, origin/main, origin/HEAD)

Author: Zeyu Ma <zeyum@princeton.edu>
Date:   Mon Sep 23 16:24:55 2024 -0400

    add config to disable landlab

commit f033891e1405bb8cdd021dae3753b98003de4bc3
Author: Alexander Raistrick <araistrick@princeton.edu>
Date:   Sun Sep 22 12:23:48 2024 -0400

    Fix misleading CPU-only warning message (#325), remove screen from example commands

commit b3ab846052eec7139d1e95f97890d06a2d74ac44
Author: Alexander Raistrick <araistrick@princeton.edu>
Date:   Sat Sep 21 17:04:20 2024 -0400

    Add more specific error message for trycatch landlab ImportError

commit d55e29724c890dde57e29b664bc01e0d1ecab383
Merge: a231df30 0cf999c0
Author: pvl-bot <136786582+pvl-bot@users.noreply.github.com>

### What are your FULL output logs?
Provide the FULL output logs from your command as a txt file.

### If this is your first time running Infinigen, what are the full install logs?**
Run `pip install -v -e . > logs.txt 2>&1` and send logs.txt as an attachment.

### Platform
- OS & OS Version: Ubuntu 24.04 LTS
- GPU (?) : NVIDIA GeForce RTX 4070, 8GB
- GPU Driver Version (?) : OpenGL version string: 4.6 (Compatibility Profile) Mesa 24.0.9-0ubuntu0.1
- RAM (GB): 15Gi

# Additional context

[10:18:05.140] [logging] [INFO] | [MAIN TOTAL] failed with <class 'OSError'>
Error: Python: Traceback (most recent call last):
  File "/home/kit/Documents/infinigen/infinigen_examples/generate_nature.py", line 1025, in <module>
    main(args)
  File "/home/kit/Documents/infinigen/infinigen_examples/generate_nature.py", line 963, in main
    execute_tasks.main(
  File "/home/kit/Documents/infinigen/infinigen/core/execute_tasks.py", line 360, in main
    execute_tasks(
  File "/home/kit/Documents/infinigen/blender/3.6/python/lib/python3.10/site-packages/gin/config.py", line 1605, in gin_wrapper
    utils.augment_exception_message_and_reraise(e, err_str)
  File "/home/kit/Documents/infinigen/blender/3.6/python/lib/python3.10/site-packages/gin/utils.py", line 41, in augment_exception_message_and_reraise
    raise proxy.with_traceback(exception.__traceback__) from None
  File "/home/kit/Documents/infinigen/blender/3.6/python/lib/python3.10/site-packages/gin/config.py", line 1582, in gin_wrapper
    return fn(*new_args, **new_kwargs)
  File "/home/kit/Documents/infinigen/infinigen/core/execute_tasks.py", line 243, in execute_tasks
    info = compose_scene_func(output_folder, scene_seed)
  File "/home/kit/Documents/infinigen/blender/3.6/python/lib/python3.10/site-packages/gin/config.py", line 1605, in gin_wrapper
    utils.augment_exception_message_and_reraise(e, err_str)
  File "/home/kit/Documents/infinigen/blender/3.6/python/lib/python3.10/site-packages/gin/utils.py", line 41, in augment_exception_message_and_reraise
    raise proxy.with_traceback(exception.__traceback__) from None
  File "/home/kit/Documents/infinigen/blender/3.6/python/lib/python3.10/site-packages/gin/config.py", line 1582, in gin_wrapper
    return fn(*new_args, **new_kwargs)
  File "/home/kit/Documents/infinigen/infinigen_examples/generate_nature.py", line 110, in compose_nature
    terrain, terrain_mesh = p.run_stage(
  File "/home/kit/Documents/infinigen/infinigen/core/util/pipeline.py", line 89, in run_stage
    ret = fn(*args, **kwargs)
  File "/home/kit/Documents/infinigen/infinigen_examples/generate_nature.py", line 100, in add_coarse_terrain
    terrain = Terrain(
  File "/home/kit/Documents/infinigen/blender/3.6/python/lib/python3.10/site-packages/gin/config.py", line 1605, in gin_wrapper
    utils.augment_exception_message_and_reraise(e, err_str)
  File "/home/kit/Documents/infinigen/blender/3.6/python/lib/python3.10/site-packages/gin/utils.py", line 41, in augment_exception_message_and_reraise
    raise proxy.with_traceback(exception.__traceback__) from None
  File "/home/kit/Documents/infinigen/blender/3.6/python/lib/python3.10/site-packages/gin/config.py", line 1582, in gin_wrapper
    return fn(*new_args, **new_kwargs)
  File "/home/kit/Documents/infinigen/infinigen/terrain/core.py", line 128, in __init__
    dll = load_cdll(
  File "/home/kit/Documents/infinigen/infinigen/terrain/utils/ctype_util.py", line 35, in load_cdll
    return CDLL(root / path, mode=RTLD_LOCAL)
  File "/home/kit/Documents/infinigen/blender/3.6/python/lib/python3.10/ctypes/__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /home/kit/Documents/infinigen/infinigen/terrain/lib/cpu/elements/waterbody.so: cannot open shared object file: No such file or directory
  In call to configurable 'Terrain' (<class 'infinigen.terrain.core.Terrain'>)
  In call to configurable 'compose_nature' (<function compose_nature at 0x7cd9ff58bac0>)
  In call to configurable 'execute_tasks' (<function execute_tasks at 0x7cd98eb10790>)

Blender quit

**Comment by araistrick** [comment]
My best guess is that terrain isnt installed.

What command did you run when doing the blender installation? IE did you run `INFINIGEN_MINIMAL_INSTALL=True bash scripts/install/interactive_blender.sh` or just `bash scripts/install/interactive_blender.sh`? If its the former then this wont install terrain and you cant run hello world, you need to do the latter which is the non-minimal version

**Comment by ngchikit** [comment]
Thanks for prompt response. I am trying to install blender. It dose have error to compile SoilMachine.o 
I attached a log file.

I tried to compile it separately.
(infinigen) kit@kit:~/Documents/infinigen$ g++ -c lib/cpu/soil_machine/SoilMachine.cpp -o lib/cpu/soil_machine/SoilMachine.o
cc1plus: fatal error: lib/cpu/soil_machine/SoilMachine.cpp: No such file or directory
compilation terminated.

Thank you~
