### ISSUE TITLE
[BUG]cpu/soil_machine/SoilMachine.so: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by zhangguochang** [princeton-vl/infinigen#84]
(infinigen) root@zgc-System-Product-Name:/home/zgc/ai_project/infinigen/worldgen# $BLENDER -noaudio --background --python generate.py -- --seed 0 --task coarse -g desert simple --output_folder outputs/helloworld/coarse
Blender 3.3.1 (hash b292cfe5a936 built 2022-10-05 00:14:35)
[00:45:49.978] [root] [INFO] | Converted args.seed='0' to scene_seed=0, parsed as hexadecimal
[00:45:49.988] [root] [INFO] | infinigen version 1.0.1
[00:45:49.988] [root] [INFO] | CUDA_VISIBLE_DEVICES=None
[00:45:49.988] [times] [INFO] | [MAIN TOTAL]
[00:45:49.990] [root] [INFO] | Processing frames 1 through 1 inclusive
[00:45:49.993] [times] [INFO] | [Create terrain]
[00:45:49.993] [root] [INFO] | Terrain using only on the fly on_the_fly_asset_folder=PosixPath('/home/zgc/ai_project/infinigen/worldgen/outputs/helloworld/coarse/assets')
[00:46:51.283] [times] [INFO] | [Create terrain] failed with <class 'OSError'>
[00:46:51.283] [times] [INFO] | [MAIN TOTAL] failed with <class 'OSError'>
Error: Python: Traceback (most recent call last):
  File "/home/zgc/ai_project/infinigen/worldgen/generate.py", line 410, in <module>
    main()
  File "/home/zgc/ai_project/infinigen/worldgen/generate.py", line 400, in main
    infinigen.main(
  File "/home/zgc/ai_project/infinigen/worldgen/core.py", line 425, in main
    execute_tasks(
  File "/home/zgc/ai_project/infinigen/blender/3.3/python/lib/python3.10/site-packages/gin/config.py", line 1605, in gin_wrapper
    utils.augment_exception_message_and_reraise(e, err_str)
  File "/home/zgc/ai_project/infinigen/blender/3.3/python/lib/python3.10/site-packages/gin/utils.py", line 41, in augment_exception_message_and_reraise
    raise proxy.with_traceback(exception.__traceback__) from None
  File "/home/zgc/ai_project/infinigen/blender/3.3/python/lib/python3.10/site-packages/gin/config.py", line 1582, in gin_wrapper
    return fn(*new_args, **new_kwargs)
  File "/home/zgc/ai_project/infinigen/worldgen/core.py", line 275, in execute_tasks
    terrain = Terrain(scene_seed, surface.registry, task=task, on_the_fly_asset_folder=output_folder/"assets")
  File "/home/zgc/ai_project/infinigen/blender/3.3/python/lib/python3.10/site-packages/gin/config.py", line 1605, in gin_wrapper
    utils.augment_exception_message_and_reraise(e, err_str)
  File "/home/zgc/ai_project/infinigen/blender/3.3/python/lib/python3.10/site-packages/gin/utils.py", line 41, in augment_exception_message_and_reraise
    raise proxy.with_traceback(exception.__traceback__) from None
  File "/home/zgc/ai_project/infinigen/blender/3.3/python/lib/python3.10/site-packages/gin/config.py", line 1582, in gin_wrapper
    return fn(*new_args, **new_kwargs)
  File "/home/zgc/ai_project/infinigen/worldgen/terrain/core.py", line 82, in __init__
    self.elements, scene_infos = scene(seed, Path(on_the_fly_asset_folder), asset_path, device)
  File "/home/zgc/ai_project/infinigen/blender/3.3/python/lib/python3.10/site-packages/gin/config.py", line 1605, in gin_wrapper
    utils.augment_exception_message_and_reraise(e, err_str)
  File "/home/zgc/ai_project/infinigen/blender/3.3/python/lib/python3.10/site-packages/gin/utils.py", line 41, in augment_exception_message_and_reraise
    raise proxy.with_traceback(exception.__traceback__) from None
  File "/home/zgc/ai_project/infinigen/blender/3.3/python/lib/python3.10/site-packages/gin/config.py", line 1582, in gin_wrapper
    return fn(*new_args, **new_kwargs)
  File "/home/zgc/ai_project/infinigen/worldgen/terrain/scene.py", line 56, in scene
    elements[ElementNames.LandTiles] = LandTiles(device, caves, on_the_fly_asset_folder, reused_asset_folder)
  File "/home/zgc/ai_project/infinigen/blender/3.3/python/lib/python3.10/site-packages/gin/config.py", line 1605, in gin_wrapper
    utils.augment_exception_message_and_reraise(e, err_str)
  File "/home/zgc/ai_project/infinigen/blender/3.3/python/lib/python3.10/site-packages/gin/utils.py", line 41, in augment_exception_message_and_reraise
    raise proxy.with_traceback(exception.__traceback__) from None
  File "/home/zgc/ai_project/infinigen/blender/3.3/python/lib/python3.10/site-packages/gin/config.py", line 1582, in gin_wrapper
    return fn(*new_args, **new_kwargs)
  File "/home/zgc/ai_project/infinigen/worldgen/terrain/elements/landtiles.py", line 95, in __init__
    n_instances, tile_size, N, float_data = self.load_assets()
  File "/home/zgc/ai_project/infinigen/blender/3.3/python/lib/python3.10/site-packages/gin/config.py", line 1605, in gin_wrapper
    utils.augment_exception_message_and_reraise(e, err_str)
  File "/home/zgc/ai_project/infinigen/blender/3.3/python/lib/python3.10/site-packages/gin/utils.py", line 41, in augment_exception_message_and_reraise
    raise proxy.with_traceback(exception.__traceback__) from None
  File "/home/zgc/ai_project/infinigen/blender/3.3/python/lib/python3.10/site-packages/gin/config.py", line 1582, in gin_wrapper
    return fn(*new_args, **new_kwargs)
  File "/home/zgc/ai_project/infinigen/worldgen/terrain/elements/landtiles.py", line 127, in load_assets
    landtile_asset(self.on_the_fly_asset_folder / tile / f"{i}", tile, device=self.device)
  File "/home/zgc/ai_project/infinigen/worldgen/terrain/assets/landtiles/core.py", line 142, in landtile_asset
    ant_landscape_asset(folder, preset_name, tile_size, resolution)
  File "/home/zgc/ai_project/infinigen/worldgen/terrain/assets/landtiles/ant_landscape.py", line 69, in ant_landscape_asset
    if erosion: run_erosion(folder)
  File "/home/zgc/ai_project/infinigen/blender/3.3/python/lib/python3.10/site-packages/gin/config.py", line 1605, in gin_wrapper
    utils.augment_exception_message_and_reraise(e, err_str)
  File "/home/zgc/ai_project/infinigen/blender/3.3/python/lib/python3.10/site-packages/gin/utils.py", line 41, in augment_exception_message_and_reraise
    raise proxy.with_traceback(exception.__traceback__) from None
  File "/home/zgc/ai_project/infinigen/blender/3.3/python/lib/python3.10/site-packages/gin/config.py", line 1582, in gin_wrapper
    return fn(*new_args, **new_kwargs)
  File "/home/zgc/ai_project/infinigen/worldgen/terrain/land_process/erosion.py", line 28, in run_erosion
    dll = load_cdll(f"terrain/lib/cpu/soil_machine/SoilMachine.so")
  File "/home/zgc/ai_project/infinigen/worldgen/terrain/utils/ctype_util.py", line 28, in load_cdll
    return CDLL(Path(sys.path[-1]) / path, mode=RTLD_LOCAL)
  File "/home/zgc/ai_project/infinigen/blender/3.3/python/lib/python3.10/ctypes/__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /home/zgc/ai_project/infinigen/worldgen/terrain/lib/cpu/soil_machine/SoilMachine.so: cannot open shared object file: No such file or directory
  In call to configurable 'run_erosion' (<function run_erosion at 0x7fcf8e080700>)
  In call to configurable 'load_assets' (<function LandTiles.load_assets at 0x7fcf8b147d00>)
  In call to configurable 'LandTiles' (<class 'terrain.elements.landtiles.LandTiles'>)
  In call to configurable 'scene' (<function scene at 0x7fcf97a6b7f0>)
  In call to configurable 'Terrain' (<class 'terrain.core.Terrain'>)
  In call to configurable 'execute_tasks' (<function execute_tasks at 0x7fcf8ab688b0>)

I use ubuntu

**Comment by xw0** [comment]
I encounter the same issue

**Comment by xw0** [comment]
Found a fix:
```
sudo apt install libglm-dev
cd worldgen/terrain
chmod +x install_terrain.sh
./install_terrain.sh
```
Run the above scripts to build `SoilMachine.so`
