### ISSUE TITLE
[BUG] Numpy types are deprecated

### ISSUE THREAD

**Issue by tms-gvd** [princeton-vl/infinigen#88]
**Describe the bug**
Deprecated numpy types after moving to v1.0.1

**Steps to Reproduce**
- What version of the code were you using? Tell us the output of `git log -n 1`
'''
commit aa22d4d1d4cb30de12f6aac453e6f49b87b787db (HEAD -> main, origin/main, origin/HEAD)
Author: Lahav Lipson <llipson@princeton.edu>
Date:   Mon Jul 3 01:22:06 2023 -0400
...
'''

- What command did you run?
```
$BLENDER -noaudio --background --python generate.py -- --seed 0 --task coarse -g desert simple --output_folder outputs/helloworld/coarse
```

- What are your output logs? 
```Blender 3.3.1 (hash b292cfe5a936 built 2022-10-05 00:14:35)
/opt/infinigen/worldgen/terrain/utils/kernelizer_util.py:78: FutureWarning: In the future `np.bool` will be defined as the corresponding NumPy scalar.. The issue is probably coming from __init__.py:300
  AttributeType.Boolean: np.bool,
Error: Python: Traceback (most recent call last):
  File "/opt/infinigen/worldgen/generate.py", line 27, in <module>
    from terrain import Terrain
  File "/opt/infinigen/worldgen/terrain/__init__.py", line 7, in <module>
    from .core import Terrain
  File "/opt/infinigen/worldgen/terrain/core.py", line 15, in <module>
    from terrain.mesher import OpaqueSphericalMesher, TransparentSphericalMesher, UniformMesher
  File "/opt/infinigen/worldgen/terrain/mesher/__init__.py", line 7, in <module>
    from .uniform_mesher import UniformMesher
  File "/opt/infinigen/worldgen/terrain/mesher/uniform_mesher.py", line 12, in <module>
    from terrain.utils import ASDOUBLE, ASINT, Mesh
  File "/opt/infinigen/worldgen/terrain/utils/__init__.py", line 7, in <module>
    from .mesh import Mesh, write_attributes, Vars, move_modifier
  File "/opt/infinigen/worldgen/terrain/utils/mesh.py", line 20, in <module>
    from .kernelizer_util import ATTRTYPE_DIMS, ATTRTYPE_FIELDS, NPTYPEDIM_ATTR, Vars
  File "/opt/infinigen/worldgen/terrain/utils/kernelizer_util.py", line 78, in <module>
    AttributeType.Boolean: np.bool,
  File "/opt/infinigen/blender/3.3/python/lib/python3.10/site-packages/numpy/__init__.py", line 305, in __getattr__
    raise AttributeError(__former_attrs__[attr])
AttributeError: module 'numpy' has no attribute 'bool'.
`np.bool` was a deprecated alias for the builtin `bool`. To avoid this error in existing code, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations. Did you mean: 'bool_'?

Blender quit
```
Fixed by replacing `np.bool` by `bool` at https://github.com/princeton-vl/infinigen/blob/aa22d4d1d4cb30de12f6aac453e6f49b87b787db/worldgen/terrain/utils/kernelizer_util.py#L78
Yet, another AttributeError is then raised:
```
Blender 3.3.1 (hash b292cfe5a936 built 2022-10-05 00:14:35)
Error: Python: Traceback (most recent call last):
  File "/opt/infinigen/worldgen/generate.py", line 27, in <module>
    from terrain import Terrain
  File "/opt/infinigen/worldgen/terrain/__init__.py", line 7, in <module>
    from .core import Terrain
  File "/opt/infinigen/worldgen/terrain/core.py", line 16, in <module>
    from terrain.scene import scene, transfer_scene_info
  File "/opt/infinigen/worldgen/terrain/scene.py", line 10, in <module>
    from terrain.elements.landtiles import LandTiles, Volcanos, FloatingIce
  File "/opt/infinigen/worldgen/terrain/elements/landtiles.py", line 12, in <module>
    from terrain.assets.landtiles import assets_to_data, landtile_asset
  File "/opt/infinigen/worldgen/terrain/assets/landtiles/__init__.py", line 7, in <module>
    from .core import assets_to_data, landtile_asset
  File "/opt/infinigen/worldgen/terrain/assets/landtiles/core.py", line 15, in <module>
    from .ant_landscape import ant_landscape_asset
  File "/opt/infinigen/worldgen/terrain/assets/landtiles/ant_landscape.py", line 13, in <module>
    from terrain.land_process.snowfall import run_snowfall
  File "/opt/infinigen/worldgen/terrain/land_process/snowfall.py", line 11, in <module>
    from landlab.components import FlowDirectorSteepest, TransportLengthHillslopeDiffuser
  File "/opt/infinigen/blender/3.3/python/lib/python3.10/site-packages/landlab/components/__init__.py", line 1, in <module>
    from .bedrock_landslider import BedrockLandslider
  File "/opt/infinigen/blender/3.3/python/lib/python3.10/site-packages/landlab/components/bedrock_landslider/__init__.py", line 1, in <module>
    from .bedrock_landslider import BedrockLandslider
  File "/opt/infinigen/blender/3.3/python/lib/python3.10/site-packages/landlab/components/bedrock_landslider/bedrock_landslider.py", line 13, in <module>
    from .cfuncs import _landslide_runout
  File "landlab/components/bedrock_landslider/cfuncs.pyx", line 5, in init landlab.components.bedrock_landslider.cfuncs
  File "/opt/infinigen/blender/3.3/python/lib/python3.10/site-packages/numpy/__init__.py", line 305, in __getattr__
    raise AttributeError(__former_attrs__[attr])
AttributeError: module 'numpy' has no attribute 'int'.
`np.int` was a deprecated alias for the builtin `int`. To avoid this error in existing code, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional in
formation.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations

Blender quit
```

** (If this is your first time running Infinigen) What are the full output logs of `install.sh` ?**
Running with Docker container, the errors are raised independently of the config (CUDA, OpenGL)

**Platform**
- OS & OS Version: Ubuntu 22.04.2 LTS 
- GPU (?) : NVIDIA TITAN RTX
- GPU Driver Version (?) : 530.30.02
- RAM (GB): 64

**Additional context**
It might come from the changes in `requirements.txt` of commit aa22d4d1d4cb30de12f6aac453e6f49b87b787db

**Comment by araistrick** [comment]
Hello, it seems you are correct, this change slipped through but did not work on all platforms. Thankyou for catching it, please pull main and I hope this resolves your issue.

**Comment by tms-gvd** [comment]
Thanks for the fix. FYI, I have now a new line in the logs, at each step of the helloworld tutorial (running inside a docker container with opengl and no gpu). Yet, I get the expected outputs when generating GT with OpenGL
```
Blender 3.3.1 (hash b292cfe5a936 built 2022-10-05 00:14:35)
COULD NOT LOAD RichDEM ENGINE! NOTHING WILL WORK!
...
```
